### ISSUE TITLE
OSS Gate Workshop: akatsuki: 2019-02-07: piroor: RxJS: Work log

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1086]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by piroor** [comment]
Googleで「RxJS」で検索した。
結果の上から見ていって、4番目に公式らしいものがあった。
https://rxjs-dev.firebaseapp.com/

**Comment by piroor** [comment]
https://rxjs-dev.firebaseapp.com/ を見てみた。
一番下までスクロールしたら、「Code licensed under an Apache-2.0 License.」と書いてあった。
なので、OSSと言える。
このプロジェクトにとりくむことにする。

**Comment by piroor** [comment]
トップページに「GET STARTED」というリンクがあるので、それを開いた。
Introdcutionがあって、その次にFirst Examplesというセクションがあった。
ボタンにイベントを割り当てる、みたいなことができるライブラリらしい。
最後まで見た後左を見ると、OVERVIEWの下に「Installation」というのがあったので
くりっくしてみた

**Comment by piroor** [comment]
Installation Instructions というところに説明があるので、やってみる。

```
npm install rxjs
```

**Comment by piroor** [comment]
index.jsを作って、最初の例を貼り付けてみた。

**Comment by piroor** [comment]
```
node index.js
/tmp/rxjstry/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as rxjs from 'rxjs';
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

実行したらエラーになった

**Comment by piroor** [comment]
```
$ npm install rxjs babel-cli babel-preset-env
$ ./node_modules/.bin/babel-node --presets babel-preset-env index.js
```

動くが、結果が出ない

**Comment by piroor** [comment]
```
import * as rxjs from 'rxjs';
rxjs.of(1, 2, 3).subscribe(x => console.log(x));
```

としたら、

```
/node_modules/.bin/babel-node --presets babel-preset-env index.js
```

で

```
1
2
3
```

という結果を得られた

**Comment by piroor** [comment]
再現手順 Steps to reproduce

1. mkdir /tmp/rxjstry
2. cd txjstry
3. npm install rxjs
4. index.jsを書いた
5. node index.js と実行

期待される結果 expected result

実行してちゃんと動いた事が分かる

実際に得られた結果 actual result

エラー：...

環境 Environment

Ubuntu 16.04
Node 10.15.1

**Comment by piroor** [comment]
Subject: The examples in the installation document should be more descrptive for beginners.

I couldn't try initial example in the page: https://rxjs-dev.firebaseapp.com/guide/installation

# Steps to reproduce

1. Create a working directory: `mkdir /tmp/rxjstry`
2. Cd to the working directory: `cd /tmp/rxjstry`
3. Run `npm install rxjs`
4. Create `index.js` with the contents:
   ```
   import * as rxjs from 'rxjs';
   
   rxjs.of(1, 2, 3);
   ```
5. Run example with `node index.js`

# Expected result

Got something output that indicates RxJS is correctly working.

# Actual result:

```
$ node index.js
/tmp/rxjstry/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as rxjs from 'rxjs';
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
```

# Environment

* Ubuntu 16.04LTS
* Node.js 10.15.1, installed via `n 10.15.1`

# Additional information

Finally I had to do more steps to run:

```
npm init
npm install --save-dev babel-cli babel-preset-env
```

before running.

I had to modify the last line of the `index.js` as `rxjs.of(1, 2, 3).subscribe(x => console.log(x));` to get output.
And I had to run `./node_modules/.bin/babel-node --presets babel-preset-env index.js` to execute the `index.js` as an ES6 file.

# Proposal

I think the installation document should have enough information to run the example script from scratch, and examples should have output to detect the example is working as expected or not.
