### ISSUE TITLE
OSS Gate Workshop: akatsuki: 2019-02-18: piroor: RxJS: Work log

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1098]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by piroor** [comment]
RxJS取り組んでみます
https://rxjs.dev/
Google検索で https://github.com/ReactiveX/rxjs から辿り着いた
ページの下の方を見るとライセンスは「Apache 2.0」と書いてあるなのでOSS。

**Comment by piroor** [comment]
Get Started
というボタンがあったのでその先に進んだ

**Comment by piroor** [comment]
https://rxjs.dev/guide/overview
イントロダクション、プロジェクトそのものの説明が書かれている

**Comment by piroor** [comment]
イントロダクションが終わってメニューを開いたら「INSTALLATION」というリンクがあったので、そちらを見てみる

**Comment by piroor** [comment]
```console
npm install rxjs
```

とコマンドを実行するとインストールできると書いてあるので、実行した

```console
$ npm install rxjs
npm WARN saveError ENOENT: no such file or directory, open '/tmp/rxjstry/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/tmp/rxjstry/package.json'
npm WARN rxjstry No description
npm WARN rxjstry No repository field.
npm WARN rxjstry No README data
npm WARN rxjstry No license field.

+ rxjs@6.4.0
added 2 packages in 3.046s
```

**Comment by piroor** [comment]
```javascript
import * as rxjs from 'rxjs';

rxjs.of(1, 2, 3);
```

最初のサンプルがこれだったので、index.jsという名前でファイルを作ってサンプルを貼り付けて実行してみた

```console
$ node index.js 
/tmp/rxjstry/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as rxjs from 'rxjs';
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
```

**Comment by piroor** [comment]
どうやら、babelを使ってJavaScriptのコードを変換しないといけないらしい

```console
$ npm init .
$ npm install --save-dev babel-cli babel-presets-env
```

でbabelをインストールして、

```console
babel-node --presets babel-preset-env index.js 
```

としたら、エラーにならずに実行が完了した。

**Comment by piroor** [comment]
実行しても結果が出ないので分かりにくい。

```javascript
import * as rxjs from 'rxjs';

rxjs.of(1, 2, 3).subscribe(result => console.log(result));
```

としたら、結果が

```console
1
2
3
```
とでるようになった。

**Comment by piroor** [comment]
最初からすぱっと一発で動いて欲しい

動いた後に、ちゃんと動いたという事が分かるようになっていて欲しい

**Comment by piroor** [comment]
再現手順

 1. `npm install rxjs`
 2. サンプルコードをindex.jsの名前で保存した
 3. `node index.js`と実行した

期待する結果

 * エラーにならない
 * 実行されて、正常に動作した事が分かる

実際の結果

 * エラーになった

```
...
```
