### ISSUE TITLE
OSS Gate Workshop: akatsuki: 2019-02-25: piroor: rxjs: Work log

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1112]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by piroor** [comment]
「rxjs」で検索した
オフィシャルサイトが出てこない！
「rxjs official」で検索したら、ReactiveXのオフィシャルサイトが出た
プラットフォーム別のリンクを見たらJavaScriptの所に「RxJS」があった
https://rxjs.dev/

**Comment by piroor** [comment]
「Get Started」というリンクをクリックした
概要の説明はあったが、試すには情報がない
メニューを開いたら「Installation」というリンクがあったのでそれをクリックした
サンプルコマンドが書かれているので、ここから始められそう

**Comment by piroor** [comment]
書いてあるサンプル

```javascript
import * as rxjs from 'rxjs';

rxjs.of(1, 2, 3);
```

これを動かしてみる

```console
mkdir rxjstry
cd rxjstry
npm install rxjs
```

と実行して、「index.js」に上の例を貼り付けて

node index.js

で実行した

**Comment by piroor** [comment]
```console
$ node index.js 
/tmp/rxjstry/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as rxjs from 'rxjs';
                                                                     ^

SyntaxError: Unexpected token *
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
```

こんなエラーが出た

**Comment by piroor** [comment]
「babel」で変換しないといけない。

```javascript
npm install --save-dev babel-cli
babel-node index.js
```

とするとbabelで変換して実行できる。

**Comment by piroor** [comment]
babelにES6用のルール？を入れないといけない。

```
npm install --save-de babel-preset-env
babel-node --presets babel-preset-env index.js
```

とすると、ES6の書式のファイルを変換して実行できる。

**Comment by piroor** [comment]
実行してたが、何も出力がない。
成功したのかどうなのかよくわからない。

**Comment by piroor** [comment]
```javascript
import * as rxjs from 'rxjs';

rxjs.of(1, 2, 3).subscribe(result => console.log(result));
```

`.subscribe(result => console.log(result))` の所を書き足して実行すると、

```console
$ babel-node --presets babel-preset-env index.js
1
2
3
```

と、結果が出た。
動いているらしい事が分かった。

**Comment by piroor** [comment]
サンプルスクリプトがいきなり動かなかった
動かすための準備を整えても、出力がないので、成功したか失敗したかわからなかった
わかるようになっていてほしい

**Comment by piroor** [comment]
再現手順

オフィシャルサイトのINSTALLATIONのページに書いてあったとおり

npm install rxjs
vi index.js

サンプルを貼り付けて

node index.js

で実行した

期待される結果

実行できる事
実行した結果、何かしら出力があって、成功したと分かる

実際の結果

エラーになった

```console
...
```

**Comment by piroor** [comment]
再現手順

https://rxjs.dev/guide/installation を開いた

npm install rxjs
vi index.js

```javascript
import * as rxjs from 'rxjs';

rxjs.of(1, 2, 3);
```

保存した

node index.js

で実行した

期待される結果

実行できる事
実行した結果、何かしら出力があって、成功したと分かる

実際の結果

エラーになった

**Comment by piroor** [comment]
# Steps to reproduce

 * Environment: Ubuntu 16.04LTS, node v10.2.1
 * Go to https://rxjs.dev/guide/installation
 * Run `npm install rxjs` as described
 * Prepare index.js as:
    ```javascript
    import * as rxjs from 'rxjs';
    rxjs.of(1, 2, 3);
    ```
 * Save the file
 * Run `node index.js`

# Expected result

 * Print something to know that the rxjs correctly works. For example: `1, 2, 3`

# Actual result

* Error from node.js
* No output
