### ISSUE TITLE
OSS Gate Workshop: osaka: 2019-03-09: baramatsubonzo: Ruby on Rails: 

### ISSUE THREAD

**Issue by baramatsubonzo** [oss-gate/workshop#1135]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by baramatsubonzo** [comment]
railsを対象にしたい
railsのリポジトリがどこにあるか
https://github.com/rails/railsにあった

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by baramatsubonzo** [comment]
LICENSEを確認した
READEMEの一番下にかいてある
MIT　LICENSEと記載あり

**Comment by baramatsubonzo** [comment]
readmeにしたがってすすめる
 $ gem install rails
はすでに行っていたのでとばした
$ rails new myapp
をした
 $ cd myapp
 $ rails server
をおこない、myappのサーバーを立ち上げた。

**Comment by baramatsubonzo** [comment]
ブラウザで、ローカル
http://192.168.33.10:3000/
に接続した
以下のerrorメッセージがでた
```
Puma caught this error: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.5/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:12:in `<main>'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/connection_specification.rb:191:in `spec'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:952:in `establish_connection'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:60:in `establish_connection'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `each'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/base.rb:328:in `<module:ActiveRecord>'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/base.rb:27:in `<main>'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.2/lib/active_record/query_cache.rb:29:in `run'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:27:in `before'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `catch'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:199:in `block in halting'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `each'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:110:in `run!'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:72:in `block in run!'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `tap'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2/lib/active_support/execution_wrapper.rb:69:in `run!'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by baramatsubonzo** [comment]
2018年11月頃までは使えていたが、2019年2月以降確認すると、このエラーがでるようになっていた。

**Comment by baramatsubonzo** [comment]
gemで複数のバージョン混ざってる可能性があるので、bundle execしてあげるといい。

**Comment by baramatsubonzo** [comment]
$ bundle exec rails s
すると
```

1007 1008 1009 1010 1011 1012 | def retrieve_connection(spec_name) #:nodoc:         pool = retrieve_connection_pool(spec_name)         raise ConnectionNotEstablished, "No connection pool with '#{spec_name}' found." unless pool         pool.connection       end
-- | --



```
と怒られる

**Comment by baramatsubonzo** [comment]
ActiveRecord::ConnectionNotEstablished
No connection pool with 'primary' found.
のエラーがでる。
ソースコードはコピーできないようなので、スクショをとっておいた

**Comment by baramatsubonzo** [comment]
最初のerrorについて、今回あFBを送ることを目的とする

**Comment by baramatsubonzo** [comment]
planeな環境でできるかどうかを試してみようかな。悩んでいる

**Comment by ShinjiEnoki** [comment]
西山さんに相談したら、クリーンな環境では起こらないけども、いろいろ使っていると起こりうるらしいです。フィードバックするネタとしては他の方がよさそうですね

**Comment by baramatsubonzo** [comment]
https://qiita.com/Kta-M/items/254a1ba141827a989cb7をみつける　エラーでぐぐった

**Comment by znz** [comment]
https://rubygems.org/gems/rails で 5.2 系は 2018-12-04 が最新リリース
修正が 5-2-stable ブランチにはマージされているそうなので、 http://ruby.studio-kingdom.com/bundler/gemfile/ の `gem "rails", :github => "rails/rails", :branch => "branch_name"` の `branch_name` に `5-2-stable` を指定して試せそう

**Comment by znz** [comment]
bundler 公式だと https://bundler.io/v2.0/guides/git.html に例があった。

**Comment by baramatsubonzo** [comment]
Gemfileの内容を、
```
gem 'rails', :github => "rails/rails", :branch=> "5-2-stable"

```
にしてみる。するとうまくいった。

**Comment by baramatsubonzo** [comment]
このエラーを解消する方法としては、
①sqlite3のgemのバージョンを1.3.6に指定してあげる
②5-2-stableのbranchでは、解消されてるので、それをgemfileで指定してあげる。そのやり方が上のやりかた。

**Comment by baramatsubonzo** [comment]
https://github.com/rails/rails/issues/35153
https://github.com/rails/rails/pull/35154
ですでに議論されていた。

**Comment by baramatsubonzo** [comment]
この問題については、officialな場所で公開してほしい。

**Comment by baramatsubonzo** [comment]
ただ、どこに、公開してほしいかで今なやんでいる

**Comment by baramatsubonzo** [comment]
https://guides.rubyonrails.org/getting_started.html
このあたりが適切かなぁ。
ただ、バージョン毎の問題をこういった形で公開してもらうべきかどうかでまた悩みがある

**Comment by ShinjiEnoki** [comment]
Getting Started は、5.2.1向けの記述になっているようなので、そのアップデートとして提案してみる手はありそうですね。

**Comment by baramatsubonzo** [comment]
https://github.com/rails/rails/issues/35153
を見てみたけど、公式でどこを参照にしたらいいかについて書いてある場所がないっぽい。
もう一つをみてみる。

**Comment by ShinjiEnoki** [comment]
どこかに追記してという話はできそうですね。

**Comment by baramatsubonzo** [comment]
もうひとつをみてみたけど、特に必要な情報はなかった。

**Comment by baramatsubonzo** [comment]
なので、どこかに追記してほしいという内容でissueをたてようとおもいます。

**Comment by baramatsubonzo** [comment]
このあと、日本語で作ってレビューもらって、英語版をつくるまでやる！

**Comment by ShinjiEnoki** [comment]
https://github.com/rails/rails/blob/master/CONTRIBUTING.md

**Comment by baramatsubonzo** [comment]
↑をみてみる。
とりあえず、issueでいいのかもしれない。
まずは日本語でつくってみる。

**Comment by baramatsubonzo** [comment]
要望　Sqlite3のerror問題に直面した人が参照する場所を示して欲しい
目的　今後同じエラーが発生した人が悩まないため

改善点　現状この問題が発生した際には、https://github.com/rails/rails/issues/35153　を参照してほしいとしているが、READMEや、Ruby on Rails Guidesなど、どこかわかりやすい場所にこの問題と、対処法を掲載するようにしてほしい。

**Comment by baramatsubonzo** [comment]
問題　[この問題](https://github.com/rails/rails/issues/35153)は、$ rails new するときに直面しやすい問題である。わかりやすい場所に参照を用意してほしい。
改善案　READMEもしくはドキュメントに、[この問題](https://github.com/rails/rails/issues/35153)の説明orリンクを用意してほしい。

**Comment by baramatsubonzo** [comment]
rails(5-2-2)の場合
```
Puma caught this error: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
```
のエラーがでる
なので、
gemfile で
gem 'sqlite3', '~> 1.3.6'
に書き換えてbundle install する
といい。
詳しくは
https://github.com/rails/rails/issues/35153

**Comment by baramatsubonzo** [comment]
rails 5.2.2の場合
gemfile
```
gem 'sqlite3', '~> 1.3.6'
```
に書き換えて```bundle install```するといい
詳しくは　rails/rails#35153

**Comment by baramatsubonzo** [comment]
問題　この問題は、`$ rails new` するときに直面しやすい問題である。release版が出るまでわかりやすい場所に対処法を用意してほしい。
要望　READMEもしくはドキュメントに、この問題の説明orリンクを用意してほしい。
改善案
rails 5.2.xの場合、gemfileを
`gem 'sqlite3', '~> 1.3.x'`
に指定して、bundle installするといい。
詳しくはrails/rails#35153

**Comment by baramatsubonzo** [comment]
問題点　
要望　READMEorドキュメントに、この問題の対策を掲載してほしい。
改善案
rails 5.2.xの場合、gemfileでsqliteを
`gem 'sqlite3', '~> 1.3.x'`
に指定して、bundle installするといい。
詳しくはrails/rails#35153

**Comment by baramatsubonzo** [comment]
問題点　Rails 5.2.xの場合、rails/rails#35153の問題に多くの人が直面していると考える。なぜならいくつものissueが報告されている
要望　READMEorドキュメントに、この問題の対策を掲載してほしい。
改善案
rails 5.2.xの場合、gemfileでsqliteを
gem 'sqlite3', '~> 1.3.x'
に指定して、bundle installするといい。
詳しくはrails/rails#35153

**Comment by baramatsubonzo** [comment]
Update Document 'Error loading the 'sqlite3''
In case of Rails 5.2.x, many people seem to face [this problem](https://github.com/rails/rails/issues/35153).
Please the approach to this problem post on READEME or other documents .
example
In case of rails 5.2.x 
in Gemfile you update `gem sqlite3`
` gem 'sqlite3', '~> 1.3.x'`
after it 
`bundle install`
see also [#35153](https://github.com/rails/rails/issues/35153)

**Comment by ShinjiEnoki** [comment]
https://github.com/rails/rails/issues/35551

**Comment by baramatsubonzo** [comment]
In case of Rails 5.2.2, many people seem to face [this problem](https://github.com/rails/rails/issues/35153)
Please post the solution to this problem on README or other documents .
example
In case of rails 5.2.2
in Gemfile you update gem sqlite3
`gem 'sqlite3', '~> 1.3.6'`
after that, run
`$ bundle install`

see also [#35153](https://github.com/rails/rails/issues/35153)

thank you very much .

**Comment by baramatsubonzo** [comment]
を投稿する

**Comment by baramatsubonzo** [comment]
rails のISSUE_TEMPLATEで作成する
