### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2019-04-27: kantarow: Charty: Work log

### ISSUE THREAD

**Issue by kantarow** [oss-gate/workshop#1188]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by kantarow** [comment]
ライセンスを確認したらMITでした
https://github.com/red-data-tools/charty/blob/master/LICENSE
https://opensource.org/licenses

**Comment by kantarow** [comment]
https://github.com/red-data-tools/charty#ubuntu--pyenv
上記リンクを参照してコマンドを実行

```
$ pyenv uninstall 3.7.2
$ sudo apt install -y tk-dev python3-tk
$ CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.2
```
実行結果
```
$ pyenv uninstall 3.7.2
pyenv: remove /home/kantarow/.pyenv/versions/3.7.2?

$ sudo apt install -y tk-dev python3-tk
[sudo] password for kantarow: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tk-dev is already the newest version (8.6.0+9).
python3-tk is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 402 not upgraded.

$ CONFIGURE_OPTS="--enable-shared" pyenv install 3.7.2
pyenv: /home/kantarow/.pyenv/versions/3.7.2 already exists
continue with installation? (y/N) y
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
Installed Python-3.7.2 to /home/kantarow/.pyenv/versions/3.7.2
```

python3.7.2が無事インストールされました

**Comment by kantarow** [comment]
https://github.com/red-data-tools/charty#with-matplotlib

```
sudo gem install charty --pre
sudo gem install matplotlib
sudo apt install python3-pip
sudo python3 -m pip install -U pip matplotlib
```

実行結果

```
$ sudo gem install charty --pre
[sudo] password for kantarow: 
Fetching: charty-0.1.2.dev.gem (100%)
Successfully installed charty-0.1.2.dev
Parsing documentation for charty-0.1.2.dev
Installing ri documentation for charty-0.1.2.dev
Done installing documentation for charty after 0 seconds
1 gem installed

$ sudo gem install matplotlib
Fetching: pycall-1.2.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed pycall-1.2.1
Fetching: matplotlib-1.0.0.gem (100%)
Successfully installed matplotlib-1.0.0
Parsing documentation for pycall-1.2.1
Installing ri documentation for pycall-1.2.1
Parsing documentation for matplotlib-1.0.0
Installing ri documentation for matplotlib-1.0.0
Done installing documentation for pycall, matplotlib after 0 seconds
2 gems installed

$ sudo apt install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2.3~ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 402 not upgraded.

$ sudo python3 -m pip install -U pip matplotlib
The directory '/home/kantarow/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/kantarow/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/f9/fb/863012b13912709c13cf5cfdbfb304fa6c727659d6290438e1a88df9d848/pip-19.1-py2.py3-none-any.whl (1.4MB)
    100% |################################| 1.4MB 702kB/s 
Collecting matplotlib
  Downloading https://files.pythonhosted.org/packages/e9/69/f5e05f578585ed9935247be3788b374f90701296a70c8871bcd6d21edb00/matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0MB)
    100% |################################| 13.0MB 93kB/s 
Collecting numpy>=1.10.0 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/c1/e2/4db8df8f6cddc98e7d7c537245ef2f4e41a1ed17bf0c3177ab3cc6beac7f/numpy-1.16.3-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |################################| 17.3MB 73kB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl (62kB)
    100% |################################| 71kB 5.9MB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/f8/a1/5742b56282449b1c0968197f63eae486eca2c35dcd334bab75ad524e0de1/kiwisolver-1.1.0-cp36-cp36m-manylinux1_x86_64.whl (90kB)
    100% |################################| 92kB 4.4MB/s 
Requirement already up-to-date: cycler>=0.10 in /home/kantarow/.local/lib/python3.6/site-packages (from matplotlib)
Collecting python-dateutil>=2.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |################################| 235kB 2.3MB/s 
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib)
  Downloading https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
    100% |################################| 583kB 1.7MB/s 
Collecting six (from cycler>=0.10->matplotlib)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: pip, numpy, pyparsing, setuptools, kiwisolver, six, python-dateutil, matplotlib
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: numpy 1.15.2
    Uninstalling numpy-1.15.2:
      Successfully uninstalled numpy-1.15.2
  Found existing installation: pyparsing 2.2.2
    Uninstalling pyparsing-2.2.2:
      Successfully uninstalled pyparsing-2.2.2
  Found existing installation: setuptools 39.0.1
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: kiwisolver 1.0.1
    Uninstalling kiwisolver-1.0.1:
      Successfully uninstalled kiwisolver-1.0.1
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: python-dateutil 2.7.3
    Uninstalling python-dateutil-2.7.3:
      Successfully uninstalled python-dateutil-2.7.3
  Found existing installation: matplotlib 3.0.0
    Uninstalling matplotlib-3.0.0:
      Successfully uninstalled matplotlib-3.0.0
Successfully installed kiwisolver-1.1.0 matplotlib-3.0.3 numpy-1.16.3 pip-19.1 pyparsing-2.4.0 python-dateutil-2.8.0 setuptools-41.0.1 six-1.12.0
```

pyenvを使っている場合, `sudo python3 -m pip install -U pip matplotlib`でインストールされない.  
pyenvを参照するために`-E`オプションを付けると成功する

**Comment by kantarow** [comment]
```
$ ruby charty.rb 
Traceback (most recent call last):
	7: from charty.rb:2:in `<main>'
	6: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/charty-0.1.2.dev/lib/charty.rb:10:in `new'
	5: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/charty-0.1.2.dev/lib/charty.rb:10:in `new'
	4: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/charty-0.1.2.dev/lib/charty/plotter.rb:6:in `initialize'
	3: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/charty-0.1.2.dev/lib/charty/plotter.rb:6:in `require_relative'
	2: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/charty-0.1.2.dev/lib/charty/matplot.rb:1:in `<top (required)>'
	1: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/kantarow/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- matplotlib/pyplot (LoadError)
```

rbenvのrubyからmatplotlibが見えていないので, インストール時にsudoを外したほうが良さそう.

実行し直したコマンド

```
gem install charty --pre
gem install matplotlib
apt install python3-pip
python3 -m pip install -U pip matplotlib
```

**Comment by kantarow** [comment]
```
$ ruby charty.rb
Traceback (most recent call last):
	4: from charty.rb:13:in `<main>'
	3: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/charty-0.1.2.dev/lib/charty/plotter.rb:243:in `render'
	2: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/charty-0.1.2.dev/lib/charty/matplot.rb:34:in `render'
	1: from /home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pycall-1.2.1/lib/pycall/pyobject_wrapper.rb:43:in `method_missing'
/home/kantarow/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/pycall-1.2.1/lib/pycall/pyobject_wrapper.rb:43:in `savefig': <class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'sample_images/bar_matplot.png' (PyCall::PyError)
  File "/home/kantarow/.pyenv/versions/3.7.2/lib/python3.7/site-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/kantarow/.pyenv/versions/3.7.2/lib/python3.7/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/kantarow/.pyenv/versions/3.7.2/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/home/kantarow/.pyenv/versions/3.7.2/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 521, in print_png
    cbook.open_file_cm(filename_or_obj, "wb") as fh:
  File "/home/kantarow/.pyenv/versions/3.7.2/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/kantarow/.pyenv/versions/3.7.2/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 407, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/home/kantarow/.pyenv/versions/3.7.2/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 392, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
```
ディレクトリが見つからない.  
無かったら作るか, わかりやすいエラーメッセージが欲しい

`mkdir sample_images`で解決.

**Comment by yuseitahara** [comment]
A result of this workshop. red-data-tools/charty#12

**Comment by yamashun** [comment]
pull rquestまでいってすごいです
