### ISSUE TITLE
OSS Gateワークショップ 2016-09-24: kg86: boostnote: 作業ログ

### ISSUE THREAD

**Issue by kg86** [oss-gate/workshop#119]
OSS Gate へようこそ。

OSS Gateワークショップでは一人ずつ issue を作り、そこに作業ログを残しながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed
## この issue 作成時点でまずやること
- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です
## 作業ログを書くタイミング

作業ログを書くタイミングは次のタイミングです。
- 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
- 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
- issueを出したとき
- pull requestを出したとき
## 作業ログに書く内容

作業ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。
- 作業（やること、やっていること、やったこと。）
- 思っていること（そのときどう思っているか。）
- 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

```
* 作業：（ここにやること、やっていること、やったことを書く）
* 思っていること：（今どう思っているかを書く）

備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）
```

例1（備考なし）：

```
* 作業：インストールを始めた
* 思っていること：ドキュメント通りに進めれば大丈夫だろう
```

例2：

``````
* 作業：インストールが失敗した
* 思っていること：ドキュメントに手順が足りない？

備考：エラーメッセージは次の通り

```text
XXX is not found
```

必要なファイルが足りないのかなぁ。
``````
## ふりかえり

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。
- ビギナーは作業ログの内容を順にメンターに説明する。
- メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）
- ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
- ビギナーが困っていることについて、解決策を一緒に考えてくれます。
- 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
- ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
- ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

**Comment by kg86** [comment]
対象OSS:https://github.com/BoostIO

どのリポジトリは分かったけどどのブランチから取ってくれば良いのか分からない。
branchがmasterとv0.7.0がある

**Comment by kg86** [comment]
v0.7.0はリリース前みたいだし、この場合はmasterで良いのではとメンターから聞いたのでmasterをダウンロードする。

**Comment by kg86** [comment]
ダウンロード完了。

READMEを読む。
Developementという項目が合ったのでそこを読む。

```We use Webpack HMR to develop Boostnote. ```
webpackは聞いたことがある、HMRはなんだろう？
とりあえず、書いてあるコマンドを実行してみる。

**Comment by kg86** [comment]
一つ目のコマンドを実行する`webpack-dev-serverがない`とエラーが出た。
```
% npm run webpack                                                                                                          [master ~/tmp/Boostnote]

> boost@0.6.8 webpack /Users/kgoto/tmp/Boostnote
> webpack-dev-server --hot --inline --config webpack.config.js

sh: webpack-dev-server: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "webpack"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! boost@0.6.8 webpack: `webpack-dev-server --hot --inline --config webpack.config.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the boost@0.6.8 webpack script 'webpack-dev-server --hot --inline --config webpack.config.js'.
npm ERR! This is most likely a problem with the boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls boost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kgoto/tmp/Boostnote/npm-debug.log
```

**Comment by kg86** [comment]
`npm install -g webpack-dev-server`を実行

再度実行する。
今度はwebpackがないと起こられる。

```
% npm run webpack                                                                                                          [master ~/tmp/Boostnote]

> boost@0.6.8 webpack /Users/kgoto/tmp/Boostnote
> webpack-dev-server --hot --inline --config webpack.config.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kgoto/tmp/Boostnote/webpack-skeleton.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "webpack"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.3
npm ERR! code ELIFECYCLE
npm ERR! boost@0.6.8 webpack: `webpack-dev-server --hot --inline --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boost@0.6.8 webpack script 'webpack-dev-server --hot --inline --config webpack.config.js'.
npm ERR! This is most likely a problem with the boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls boost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kgoto/tmp/Boostnote/npm-debug.log
/Users/kgoto/tmp/Boostnote% npm -g install webpack                                                                                                   [master ~/tmp/Boostnote]
npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "-g" "install" "webpack"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.3
npm ERR! path /opt/local/bin/webpack
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall unlink

npm ERR! Error: EACCES: permission denied, unlink '/opt/local/bin/webpack'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, unlink '/opt/local/bin/webpack']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'unlink',
npm ERR!   path: '/opt/local/bin/webpack' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES: permission denied, unlink '/opt/local/bin/webpack'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES: permission denied, unlink '/opt/local/bin/webpack']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   syscall: 'unlink',
npm ERR! error rolling back   path: '/opt/local/bin/webpack' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kgoto/tmp/Boostnote/npm-debug.log
```

今度は`npm -g install webpack `を実行

再度コマンドを動かす。
が同じエラーが表示される。

```
% npm run webpack                                                                                                          [master ~/tmp/Boostnote]

> boost@0.6.8 webpack /Users/kgoto/tmp/Boostnote
> webpack-dev-server --hot --inline --config webpack.config.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kgoto/tmp/Boostnote/webpack-skeleton.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "webpack"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.3
npm ERR! code ELIFECYCLE
npm ERR! boost@0.6.8 webpack: `webpack-dev-server --hot --inline --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boost@0.6.8 webpack script 'webpack-dev-server --hot --inline --config webpack.config.js'.
npm ERR! This is most likely a problem with the boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls boost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kgoto/tmp/Boostnote/npm-debug.log
```

**Comment by kg86** [comment]
`-g`が怪しいのではという指摘をメンターから受け、`npm install webpack`を実行。

違うエラーが出たが、先程のエラーはなくなった。


```
% npm run webpack                                                                                                          [master ~/tmp/Boostnote]

> boost@0.6.8 webpack /Users/kgoto/tmp/Boostnote
> webpack-dev-server --hot --inline --config webpack.config.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'nib'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/kgoto/tmp/Boostnote/webpack-skeleton.js:23:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "webpack"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.3
npm ERR! code ELIFECYCLE
npm ERR! boost@0.6.8 webpack: `webpack-dev-server --hot --inline --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the boost@0.6.8 webpack script 'webpack-dev-server --hot --inline --config webpack.config.js'.
npm ERR! This is most likely a problem with the boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline --config webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls boost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kgoto/tmp/Boostnote/npm-debug.log
```

**Comment by kg86** [comment]
`npm install nib`を実行し、`npm run webpack`を再実行。

`webpack: bundle is now VALID.`が表示され正常に動作した。

次の指示通り`npm run hot`を実行する。

以下のエラーが出た。

```
% npm run hot                                                                                                             [master ~/tmp/Boostnote]

> boost@0.6.8 hot /Users/kgoto/tmp/Boostnote
> electron ./index.js --hot

sh: electron: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "run" "hot"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! boost@0.6.8 hot: `electron ./index.js --hot`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the boost@0.6.8 hot script 'electron ./index.js --hot'.
npm ERR! This is most likely a problem with the boost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron ./index.js --hot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs boost
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls boost
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kgoto/tmp/Boostnote/npm-debug.log
```

**Comment by kg86** [comment]
`npm install electron`して再度実行、つぎは`lodash`がないと起こられる。

```
% npm run hot                                                                                                             [master ~/tmp/Boostnote]

> boost@0.6.8 hot /Users/kgoto/tmp/Boostnote
> electron ./index.js --hot

App threw an error during load
Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/kgoto/tmp/Boostnote/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kgoto/tmp/Boostnote/lib/main-app.js:8:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by kg86** [comment]
- `npm install lodash`
- `electron-gh-releases`がないと怒られる。
- `npm install electron-gh-releases`
- `node-ipc`がないと怒られる。
- `npm install node-ipc`

エラーが表示されずにGUIが立ち上がった。

が、ずっとLoadingが表示される。

エラーはどこにも吐かれていないので今後どうするべきか、、、

**Comment by kg86** [comment]
- 同じような現象がissueとして報告されていないか調べる。
- OpneとClosedどちらもざっと目を通したがbuiildに関するエラー報告はなされていなかった。
- build指示をもう一度読み返してみる

**Comment by kg86** [comment]
タイポを見つけた。

- ```Actually the app can be start with `npm start@. However, the app will use the compiled script.```
- @は「`」だと思う。

**Comment by kg86** [comment]
- これまでbuild中に○○のパッケージがないと表示される問題は`npm install`すれば全て解決することがわかった。
- 無事、buildして起動することが出来た。

**Comment by kg86** [comment]
これまでに気づいたことを整理してみる
buildドキュメントについて以下の改善すべきポイントを見つけた。
簡単なことだが、それに気づかず多くの時間を使う人もいる（今回の自分のように）。

- typoがある
- buildの前に必要なパッケージをインストールするため`npm install`する必要がある
- readmeで見づらい点がある（箇条書きだが改行されていない）。

**Comment by kg86** [comment]
英文を書いてレビューを受ける。
3つの指摘をした

- typo
- npm installが必要
- コマンドとコマンドログが混同しそうだったので、コマンドの先頭に$を挿入する。

forkして自分のリポジトリに変更点をpushして、pull requestを送った。

**Comment by Rokt33r** [comment]
PRありがとうございます！
もし、分からないとかおかしい部分が見つけたらいつでも突っ込んでください！

**Comment by kg86** [comment]
取り入れて貰いありがとうございます！
boostnoteはお気に入りのアプリなので、今後も改善することがあればどんどん貢献していきたいと思います！
