### ISSUE TITLE
OSS Gate Workshop: tokyo: 2019-07-27: kasajima_k: knowledge: Work log

### ISSUE THREAD

**Issue by kasajimakengo** [oss-gate/workshop#1226]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by pocke** [comment]
よろしくおねがいします！

**Comment by kasajimakengo** [comment]
よろしくお願いします！

**Comment by kasajimakengo** [comment]
Licenseの確認
https://github.com/support-project/knowledge/blob/v1/LICENSE
Apache License 2.0は下記に含まれている。

https://opensource.org/licenses/alphabetical

**Comment by kasajimakengo** [comment]
readmeからset-upのリンクに飛んだ。
javaとtomcatが必要なので、ない場合はインストールする。
https://github.com/support-project/knowledge/wiki/How-to-set-up-(japanese)

**Comment by kasajimakengo** [comment]
macにtomcatを入れる。
https://qiita.com/R1ck29/items/9729b0b2abb9020c31eb

**Comment by kasajimakengo** [comment]
次のknowledge.war をダウンロードの項目だが、リンクがあるといいと思った。

**Comment by kasajimakengo** [comment]
knowledge.warはファイルを検索しても出てこなかった。
webで調べて、下記の記事を発見した。
https://qiita.com/htakeda/items/a9d3e2dfad67dffb7262

そこで。Releasesの所にwarがあるということを知った。
https://github.com/support-project/knowledge/releases

**Comment by kasajimakengo** [comment]
tomcatを起動した状態で、knowleage.warを配備しても
http://localhost:8080/knowledge
は404

**Comment by kasajimakengo** [comment]
shutdown.shして再起動したけど、起動しなかった。

**Comment by kasajimakengo** [comment]
見た目上同じ現象だが、ログの種類がちがう。
https://github.com/support-project/knowledge/issues/550

**Comment by kasajimakengo** [comment]
java12とtomcat8の組み合わせで、下記のエラーになった。
[catalina.out.zip](https://github.com/oss-gate/workshop/files/3437791/catalina.out.zip)

**Comment by kasajimakengo** [comment]
うまくいきました。
最新版以外のjavaを落とせるように下記を実行して、

> homebrew-cask-versionsの導入

```
brew tap homebrew/cask-versions
```

AdoptOpenJDK 8のインストールを行った。

`brew cask install adoptopenjdk8
`
Java SE 8
```
$ export JAVA_HOME=`/usr/libexec/java_home -v "1.8"`
$ PATH=${JAVA_HOME}/bin:${PATH}

```
https://qiita.com/ringo/items/db58b34dc02a941b297f

**Comment by kasajimakengo** [comment]
フィードバックするとしたら
①How-to-set-upのインストール > knowledge.war
ファイルの場所がわからず、web検索してしまったので、リンクをつけてあげるのがいい。
https://github.com/support-project/knowledge/wiki/How-to-set-up-(japanese)

②How-to-set-upのインストール > Java version 8 以降をインストール
java12をダウンロードした所tomcatの起動時にエラーになったので、明記するのが良い。

**Comment by asonas** [comment]
細かくメモが書かれていてよかったです :+1:
READMEを読んでいたらJDKのバージョンが8以降、と書いてあったけど最新版を使うとだめそう、という風に読めました。
JDKのバージョンが新しすぎるのか？または、Knowledge側が対応できていないのかは、ちょっとわからなかったのでそのあたりを切り分けできるとよいかな？ 🤔

**Comment by kasajimakengo** [comment]
開発者にとってわかりやすくなるように編集する。
✓作業メモを開く
✓フィードバック対象を決める
✓自分の気持ちを作業メモに追記
✓サポーターに確認依頼

**Comment by kasajimakengo** [comment]
Title:
How to set up (japanese)の編集提案

Description:
knowledgeのセットアップ手順のwikiですが、初学者にとって下記の文書ではファイルの場所を特定できず不便と感じました。
https://github.com/support-project/knowledge/wiki/How-to-set-up-(japanese)

> knowledge.war をダウンロード

下記のようにwikiを修正したいのですが、よろしいでしょうか。

修正文言

> knowledge.war をダウンロード

修正方法
下記のリンクを追加する。
(https://github.com/support-project/knowledge/releases)

**Comment by kasajimakengo** [comment]
Title:
java12でローカルにインストールしたknowledgeが実行できない。

Description:
実行環境
OS:mac OS mojave 0.14.5
java Version:Java SE 12
tomcat:tomcat-8.5

https://github.com/support-project/knowledge/wiki/How-to-set-up-(japanese)
上記リンク内の手順を行い、tomcatを起動した所下記のようなエラーがcatalina.outに出力され、knowledgeにアクセスできませんでした。
```
[2;36m INFO[m 2019-07-27 11:52:34,952 Intercepter(220)   <Cause>
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1360)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3143)
	at java.base/java.lang.Class.getConstructor0(Class.java:3348)
	at java.base/java.lang.Class.newInstance(Class.java:571)
	at org.support.project.common.serialize.SerializeUtils.getSerializerInstanse(SerializeUtils.java:58)
	at org.support.project.common.serialize.SerializeUtils.getSerializer(SerializeUtils.java:298)
	at org.support.project.common.serialize.SerializeUtils.bytesToObject(SerializeUtils.java:406)
	at org.support.project.ormapping.config.impl.ConnectionConfigXmlLoader.load(ConnectionConfigXmlLoader.java:43)
	at org.support.project.ormapping.config.impl.ConnectionConfigXmlLoader.load(ConnectionConfigXmlLoader.java:29)
	at org.support.project.ormapping.connection.ConnectionManager.getConnection(ConnectionManager.java:271)
	at org.support.project.ormapping.transaction.TransactionManager.start(TransactionManager.java:64)
	at org.support.project.ormapping.transaction.Transaction.invoke(Transaction.java:39)
	at org.support.project.knowledge.deploy.InitDB.init(InitDB.java:127)
	at org.support.project.knowledge.deploy.InitializationListener.contextInitialized(InitializationListener.java:41)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```
javaのバーションが新しいことが原因と考え、javaのバージョンを8にした所knowledgeを開くことができました。

下記のjavaのversionには8以降に対応しているとありますが、java12では実行できませんでしたので、wikiに明記または、上位のjavaに対応する修正をする必要があると考えています。
https://github.com/support-project/knowledge/wiki/How-to-set-up-(japanese)

参考サイト
https://sun0range.com/information-technology/jaxb-exception

**Comment by kasajimakengo** [comment]
アクセスできませんでした。→　エラーメッセージ404

やらなかったことを明記する。
java8,12で検証した。→8,12でのみ検証したことを伝わるようにする。

**Comment by kasajimakengo** [comment]
投稿してみました。
https://github.com/support-project/knowledge/issues/1079
https://github.com/support-project/knowledge/issues/1078
