### ISSUE TITLE
    OSS Gate Workshop: Tokyo: 2019-09-14: neko314: sorcery: Work log

### ISSUE THREAD

**Issue by neko314** [oss-gate/workshop#1298]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by neko314** [comment]
Sorceryの[Rails 5 request specs login_user method undefined](https://github.com/Sorcery/sorcery/issues/106)について、動作確認することにした

**Comment by neko314** [comment]
[Sample app](https://github.com/Sorcery/sorcery-example-app)をclone

**Comment by neko314** [comment]
`docker-compose up`

**Comment by neko314** [comment]
`docker exec -it sorcery_example bash`して
`bin/rails db:migrate`
`bundle install`

**Comment by neko314** [comment]
`bin/rails test`でテストが落ちる

```sh
# bin/rails test
Run options: --seed 31025

# Running:

.....E

Error:
UsersControllerTest#test_should_show_user:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:29:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:27

E

Error:
UsersControllerTest#test_should_update_user:
ArgumentError: unknown keywords: id, user
    test/functional/users_controller_test.rb:41:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:39

E

Error:
UsersControllerTest#test_should_create_user:
ArgumentError: unknown keyword: user
    test/functional/users_controller_test.rb:21:in `block (2 levels) in <class:UsersControllerTest>'
    test/functional/users_controller_test.rb:20:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:19

.E

Error:
UsersControllerTest#test_should_destroy_user:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:48:in `block (2 levels) in <class:UsersControllerTest>'
    test/functional/users_controller_test.rb:47:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:45

E

Error:
UsersControllerTest#test_should_get_edit:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:35:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:33

E

Error:
UsersControllerTest#test_should_get_index:
NoMethodError: assigns has been extracted to a gem. To continue using it,
        add `gem 'rails-controller-testing'` to your Gemfile.
    test/functional/users_controller_test.rb:11:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:8



Finished in 0.893892s, 13.4244 runs/s, 10.0683 assertions/s.
12 runs, 9 assertions, 0 failures, 6 errors, 0 skips
```

**Comment by neko314** [comment]
エラーメッセージ通り`gem 'rails-controller-testing`を追加してみる

**Comment by neko314** [comment]
通るテストが1つ増えたけどまだ5個落ちる
```
# bin/rails test
Run options: --seed 2864

# Running:

....E

Error:
UsersControllerTest#test_should_get_edit:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:35:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:33

..E

Error:
UsersControllerTest#test_should_update_user:
ArgumentError: unknown keywords: id, user
    test/functional/users_controller_test.rb:41:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:39

E

Error:
UsersControllerTest#test_should_create_user:
ArgumentError: unknown keyword: user
    test/functional/users_controller_test.rb:21:in `block (2 levels) in <class:UsersControllerTest>'
    test/functional/users_controller_test.rb:20:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:19

E

Error:
UsersControllerTest#test_should_destroy_user:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:48:in `block (2 levels) in <class:UsersControllerTest>'
    test/functional/users_controller_test.rb:47:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:45

E

Error:
UsersControllerTest#test_should_show_user:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:29:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:27

.

Finished in 1.145968s, 10.4715 runs/s, 8.7262 assertions/s.
12 runs, 10 assertions, 0 failures, 5 errors, 0 skips
```

**Comment by neko314** [comment]
localhostに接続して、アプリケーションの挙動としては問題ないことを確認。
引き続きテストの修正をやることにする。

**Comment by tdtds** [comment]
サンプルアプリにはライセンスが設定されていないという問題はありましたが、ここはいちおう親プロジェクトに準拠すると判断して進めてしまいましょう。「ライセンスを設定してくれ」というissueをあげてもよいかも知れませんね。

**Comment by neko314** [comment]
@tdtds 
ありがとうございます。
ライセンスについては提案のIssue立ててみます。
テストは直せそうなので時間内に修正できたらPRとして作成できるように作業進めてみます。

**Comment by neko314** [comment]
testコードを見てみるとこのようになっている。
```ruby
get :edit, id: @user.to_param
```

でも、[Railsガイド](https://railsguides.jp/testing.html#%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%A9%E3%81%AE%E6%A9%9F%E8%83%BD%E3%83%86%E3%82%B9%E3%83%88)ではこのように書いている。

```ruby
get article_url, params: { id: 12 }, headers: { "HTTP_REFERER" => "http://example.com/home" }et article_url, params: { id: 12 }, headers: { "HTTP_REFERER" => "http://example.com/home" }
```

テスト中のパタメータの書き方を直したらテスト通りそう。

**Comment by neko314** [comment]
直したら通った。

**Comment by neko314** [comment]
gemの追加とテストの修正は別のPRにする。（ほうがいいといサポーターさんから教えていただいた）

**Comment by neko314** [comment]
> gemの追加とテストの修正は別のPRにする。

と思ったが、どちらもRails 4系から5系へアップデートしたときの修正漏れなのでまとめてもよさそう。

**Comment by neko314** [comment]
リポジトリをfolkして、` improve-rails-5-test-support`というブランチで修正をコミットした。

**Comment by neko314** [comment]
## 再現方法
```
docker-compose up
docker exec -it sorcery_example bash
bin/rails db:migrate
bundle install
```

```sh
# bin/rails test
Run options: --seed 31025

# Running:

.....E

Error:
UsersControllerTest#test_should_show_user:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:29:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:27

E

Error:
UsersControllerTest#test_should_update_user:
ArgumentError: unknown keywords: id, user
    test/functional/users_controller_test.rb:41:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:39

E

Error:
UsersControllerTest#test_should_create_user:
ArgumentError: unknown keyword: user
    test/functional/users_controller_test.rb:21:in `block (2 levels) in <class:UsersControllerTest>'
    test/functional/users_controller_test.rb:20:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:19

.E

Error:
UsersControllerTest#test_should_destroy_user:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:48:in `block (2 levels) in <class:UsersControllerTest>'
    test/functional/users_controller_test.rb:47:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:45

E

Error:
UsersControllerTest#test_should_get_edit:
ArgumentError: unknown keyword: id
    test/functional/users_controller_test.rb:35:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:33

E

Error:
UsersControllerTest#test_should_get_index:
NoMethodError: assigns has been extracted to a gem. To continue using it,
        add `gem 'rails-controller-testing'` to your Gemfile.
    test/functional/users_controller_test.rb:11:in `block in <class:UsersControllerTest>'


bin/rails test test/functional/users_controller_test.rb:8



Finished in 0.893892s, 13.4244 runs/s, 10.0683 assertions/s.
12 runs, 9 assertions, 0 failures, 6 errors, 0 skips
```

**Comment by neko314** [comment]
# Fix
* Add `gem 'rails-controller-testing'`
* All parameters should be passed to the methods with param hashes

**Comment by neko314** [comment]
PR作った
https://github.com/Sorcery/sorcery-example-app/pull/8

**Comment by neko314** [comment]
”ライセンス設定してほしい”Issueの文章を考える

**Comment by neko314** [comment]
Add LICENSE.md.
Please consider to license this repository explicitly

**Comment by neko314** [comment]
Issue 立てた
https://github.com/Sorcery/sorcery-example-app/issues/9

**Comment by ryoon** [comment]
今日はありがとうございました。私も大変勉強になりました。

**Comment by neko314** [comment]
@ryoon 
こちらこそ、本当にありがとうございました！
今日はPRとか出せましたが、最初にやろうと思っていた動作確認はできてないので、明日以降は今日教えてもらったことを参考にして自分でやってみたいと思います✨
