### ISSUE TITLE
OSS Gate Workshop: Online: 2020-09-12: mogumogu-tatsugoro: rspec-core: Work log

### ISSUE THREAD

**Issue by mogumogu-tatsugoro** [oss-gate/workshop#1421]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mogumogu-tatsugoro** [comment]
rspec-core が OSS なのかを確認します

**Comment by ogom** [comment]
サポータです。よろしくお願いします。

**Comment by mogumogu-tatsugoro** [comment]
よろしくお願いいたします 🙏

**Comment by mogumogu-tatsugoro** [comment]
https://github.com/rspec/rspec-core/blob/main/LICENSE.md

> The MIT License (MIT)

上記から MIT License (MIT) であることがわかったので
MIT License (MIT) がオープンソースライセンスなのかを確認します！

**Comment by mogumogu-tatsugoro** [comment]
https://opensource.org/licenses/alphabetical

> MIT License (MIT)

オープンソースライセンスであることがわかりました 👀

**Comment by mogumogu-tatsugoro** [comment]
https://github.com/rspec/rspec-core#install

上記を参照し、ローカルで動作させて参ります！

**Comment by mogumogu-tatsugoro** [comment]
% gem install rspec
Fetching rspec-3.9.0.gem
Fetching rspec-mocks-3.9.1.gem
Fetching rspec-support-3.9.3.gem
Fetching rspec-core-3.9.2.gem
Fetching diff-lcs-1.4.4.gem
Fetching rspec-expectations-3.9.2.gem
Successfully installed rspec-support-3.9.3
Successfully installed rspec-core-3.9.2
Successfully installed diff-lcs-1.4.4
Successfully installed rspec-expectations-3.9.2
Successfully installed rspec-mocks-3.9.1
Successfully installed rspec-3.9.0
Parsing documentation for rspec-support-3.9.3
Installing ri documentation for rspec-support-3.9.3
Parsing documentation for rspec-core-3.9.2
Installing ri documentation for rspec-core-3.9.2
Parsing documentation for diff-lcs-1.4.4
Installing ri documentation for diff-lcs-1.4.4
Parsing documentation for rspec-expectations-3.9.2
Installing ri documentation for rspec-expectations-3.9.2
Parsing documentation for rspec-mocks-3.9.1
Installing ri documentation for rspec-mocks-3.9.1
Parsing documentation for rspec-3.9.0
Installing ri documentation for rspec-3.9.0
Done installing documentation for rspec-support, rspec-core, diff-lcs, rspec-expectations, rspec-mocks, rspec after 13 seconds
6 gems installed

**Comment by mogumogu-tatsugoro** [comment]
```
gem install rspec-core
Successfully installed rspec-core-3.9.2
Parsing documentation for rspec-core-3.9.2
Done installing documentation for rspec-core after 2 seconds
1 gem installed
```

**Comment by mogumogu-tatsugoro** [comment]
```
% rspec --help
Usage: rspec [options] [files or directories]

    -I PATH                            Specify PATH to add to $LOAD_PATH (may be used more than once).
    -r, --require PATH                 Require a file.
    -O, --options PATH                 Specify the path to a custom options file.
        --order TYPE[:SEED]            Run examples by the specified order type.
                                         [defined] examples and groups are run in the order they are defined
                                         [rand]    randomize the order of groups and examples
                                         [random]  alias for rand
                                         [random:SEED] e.g. --order random:123
        --seed SEED                    Equivalent of --order rand:SEED.
        --bisect[=verbose]             Repeatedly runs the suite in order to isolate the failures to the
                                         smallest reproducible case.
        --[no-]fail-fast[=COUNT]       Abort the run after a certain number of failures (1 by default).
        --failure-exit-code CODE       Override the exit code used when there are failing specs.
    -X, --[no-]drb                     Run examples via DRb.
        --drb-port PORT                Port to connect to the DRb server.

  **** Output ****

    -f, --format FORMATTER             Choose a formatter.
                                         [p]rogress (default - dots)
                                         [d]ocumentation (group and example names)
                                         [h]tml
                                         [j]son
                                         [f]ailures ("file:line:reason", suitable for editors integration)
                                         custom formatter class name
    -o, --out FILE                     Write output to a file instead of $stdout. This option applies
                                         to the previously specified --format, or the default format
                                         if no format is specified.
        --deprecation-out FILE         Write deprecation warnings to a file instead of $stderr.
    -b, --backtrace                    Enable full backtrace.
        --force-color, --force-colour  Force the output to be in color, even if the output is not a TTY
        --no-color, --no-colour        Force the output to not be in color, even if the output is a TTY
    -p, --[no-]profile [COUNT]         Enable profiling of examples and list the slowest examples (default: 10).
        --dry-run                      Print the formatter output of your suite without
                                         running any examples or hooks
    -w, --warnings                     Enable ruby warnings

  **** Filtering/tags ****

    In addition to the following options for selecting specific files, groups, or
    examples, you can select individual examples by appending the line number(s) to
    the filename:

      rspec path/to/a_spec.rb:37:87

    You can also pass example ids enclosed in square brackets:

      rspec path/to/a_spec.rb[1:5,1:6] # run the 5th and 6th examples/groups defined in the 1st group

        --only-failures                Filter to just the examples that failed the last time they ran.
    -n, --next-failure                 Apply `--only-failures` and abort after one failure.
                                         (Equivalent to `--only-failures --fail-fast --order defined`)
    -P, --pattern PATTERN              Load files matching pattern (default: "spec/**/*_spec.rb").
        --exclude-pattern PATTERN      Load files except those matching pattern. Opposite effect of --pattern.
    -e, --example STRING               Run examples whose full nested names include STRING (may be
                                         used more than once)
    -E, --example-matches REGEX        Run examples whose full nested names match REGEX (may be
                                         used more than once)
    -t, --tag TAG[:VALUE]              Run examples with the specified tag, or exclude examples
                                       by adding ~ before the tag.
                                         - e.g. ~slow
                                         - TAG is always converted to a symbol
        --default-path PATH            Set the default path where RSpec looks for examples (can
                                         be a path to a file or a directory).

  **** Utility ****

        --init                         Initialize your project with RSpec.
    -v, --version                      Display the version.
    -h, --help                         You're looking at it.
```

**Comment by mogumogu-tatsugoro** [comment]
普段 Rails の中でしか利用をしたことがないので、単体での利用方法を確認中です 👀

**Comment by mogumogu-tatsugoro** [comment]
https://github.com/rspec/rspec-core#the-rspec-command
> The rspec Command
When you install the rspec-core gem, it installs the rspec executable, which you'll use to run rspec. The rspec command comes with many useful options. Run rspec --help to see the complete list.

rspec-core を入れると `rspec` コマンドを利用できるようになる
オプションは `rspec --help` で確認

**Comment by mogumogu-tatsugoro** [comment]
https://github.com/rspec/rspec-core#get-started

上記確認して参ります！

**Comment by mogumogu-tatsugoro** [comment]
> Address the failure by defining a skeleton of the Calculator class:
# in lib/calculator.rb
class Calculator
  def add(a, b)
  end
end

上記作成しました！

**Comment by mogumogu-tatsugoro** [comment]
少し手順書と順番が前後してしまいましたが、以下を作成いたしました！

```
# in spec/calculator_spec.rb
RSpec.describe Calculator do
  describe '#add' do
    it 'returns the sum of its arguments' do
      expect(Calculator.new.add(1, 2)).to eq(3)
    end
  end
end
```

**Comment by mogumogu-tatsugoro** [comment]
`readme` の通り、テストが落ちることを確認

```
% rspec spec/calculator_spec.rb

An error occurred while loading ./spec/calculator_spec.rb.
Failure/Error:
  RSpec.describe Calculator do
    describe '#add' do
      it 'returns the sum of its arguments' do
        expect(Calculator.new.add(1, 2)).to eq(3)
      end
    end
  end

NameError:
  uninitialized constant Calculator
# ./spec/calculator_spec.rb:2:in `<top (required)>'
No examples found.


Finished in 0.00007 seconds (files took 0.3673 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

**Comment by mogumogu-tatsugoro** [comment]
以下を `spec/calculator_spec.rb` に追記いたしました！

```
# in spec/calculator_spec.rb
# - RSpec adds ./lib to the $LOAD_PATH
require "calculator"
```

**Comment by mogumogu-tatsugoro** [comment]
テストが期待値と違うことで落ちていることを確認いたしました！

```
% rspec spec/calculator_spec.rb
F

Failures:

  1) Calculator#add returns the sum of its arguments
     Failure/Error: expect(Calculator.new.add(1, 2)).to eq(3)

       expected: 3
            got: nil

       (compared using ==)
     # ./spec/calculator_spec.rb:6:in `block (3 levels) in <top (required)>'

Finished in 0.05996 seconds (files took 0.38288 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/calculator_spec.rb:5 # Calculator#add returns the sum of its arguments
```

**Comment by mogumogu-tatsugoro** [comment]
`lib/calculator.rb` の add メソッドの修正を行いました！

```
def add(a, b)
  a + b
end
```

**Comment by mogumogu-tatsugoro** [comment]
無事テストが通り、動作確認ができました 🎉 
```
rspec spec/calculator_spec.rb
.

Finished in 0.0152 seconds (files took 0.37692 seconds to load)
1 example, 0 failures
```

**Comment by mogumogu-tatsugoro** [comment]
以下も確認できました！

```
% rspec spec/calculator_spec.rb --format doc
Calculator
  #add
    returns the sum of its arguments

Finished in 0.00454 seconds (files took 0.32838 seconds to load)
1 example, 0 failures
```

**Comment by mogumogu-tatsugoro** [comment]
テスト駆動の考え方から伝えてくれている素敵な readme だなと思いました ✨

**Comment by mogumogu-tatsugoro** [comment]
とにかく `rspec` を動かしたくてテスト駆動の `readme` 流れを無視してしまった 💦

**Comment by mogumogu-tatsugoro** [comment]
母国語でないので、コードからあたりをつけてとにかくデータを作ろうとしてしまったのかもしれない 💭

**Comment by mogumogu-tatsugoro** [comment]
上記のような部分を言語化しておかないと、慣れて忘れてしまうのでメモ大切なので、普段の開発に活かして参ります！

**Comment by mogumogu-tatsugoro** [comment]
ogom さんはなんでも触れる Ruby や TypeScript や python などなんでも利用されている

**Comment by mogumogu-tatsugoro** [comment]
ライブラリを書いたりもなされている

**Comment by mogumogu-tatsugoro** [comment]
OSS 活動はやりたい時にできる！！！！！

**Comment by mogumogu-tatsugoro** [comment]
普段PRを送る動機
新しいライブラリでバグを踏んだり、機能が欲しくてPR送ったり

**Comment by mogumogu-tatsugoro** [comment]
今回の作業の中で readme に課題があるリポジトリとかもあると思うので、そういうところでも修正することができそう

**Comment by mogumogu-tatsugoro** [comment]
普段から課題を見つける意識を持つことが大切そう

**Comment by mogumogu-tatsugoro** [comment]
やりたいことに対して疑問があるので後ほど教えていただけると助かります 🙇 

## 疑問点
やりたいこと特別なことでないので過去にも議論がありそうだと思うのですが、その辺りの調査方法は issue を見るとかになるのでしょうか 👀 

## 課題だと感じていること
以下の `to` メソッドは `not_to` があるのですが、 `and` した際には `not` することができないのが課題だと思っています。

```
  expect { subject }.to change { x }.by(1).
                    and change { y }.by(2)
```

## できるようにしたい
```
  expect { subject }.not_to change { x }.by(1).
                    and_not change { y }.by(2)
```

**Comment by mogumogu-tatsugoro** [comment]
ハクトーバーフェスト 👀

**Comment by mogumogu-tatsugoro** [comment]
Issue をやるよりは、自分の要望が多そう？
似た Issue が上がっていればコメント

**Comment by mogumogu-tatsugoro** [comment]
コントリビューターとして実績を積むためにとかの動機もありそう

**Comment by mogumogu-tatsugoro** [comment]
とりあえず課題を見付けたら報告

**Comment by mogumogu-tatsugoro** [comment]
反応なければ原因特定してパッチ修正送ってしまってもいいかも

**Comment by mogumogu-tatsugoro** [comment]
リアクションの雰囲気はリポジトリの大きさやクローズ具合とかを見るといいかも

**Comment by mogumogu-tatsugoro** [comment]
> ワークショップ内でフリートークの時間を組み込んでもいいかもしれない
@piroor さんのワークショップに対する課題意識も高くて見習って行きたい 👀

**Comment by mogumogu-tatsugoro** [comment]
メモは対象リポジトリをフォークして、そこでなさっているのか確認しよう 👀

**Comment by mogumogu-tatsugoro** [comment]
困っていることの具体例とこうして欲しいという希望を記載すると伝わりやすいとのことなので、記載して参ります！

**Comment by mogumogu-tatsugoro** [comment]
```
class Example
  attr_accessor :a, :b, :c

  def init
    @a = 'not_changed_with_change_c'
    @b = 'not_changed_with_change_c'
  end

  def change_c(c)
    @c = 'changed_with_change_c'
  end
end
```

```
describe Example do
  subject { ex.change_c }
  let(:ex) { Example.new }

  expect { subject }.not_to change { ex.a }.
    and_not change { ex.b }.
    and change { ex.c }
end
```

**Comment by mogumogu-tatsugoro** [comment]
正常疎通させる例と、こう書きたいがこう書くと落ちてしまうというのを記載してまいります！

**Comment by mogumogu-tatsugoro** [comment]
https://github.com/oss-gate/workshop/issues/1421#issuecomment-691431852 の後の例の実行結果です！
```
% rspec
F

Failures:

  1) Example#change_c change only ex.c
     Failure/Error:
       expect{ subject }.to change{ ex.c }.to('changed_with_change_c').
         and_not change{ ex.a }.
         and_not change{ ex.b }
     
     NoMethodError:
       undefined method `and_not' for #<RSpec::Matchers::BuiltIn::Change:0x00007fe68b884180>
     # ./spec/example_spec.rb:10:in `block (3 levels) in <top (required)>'

Finished in 0.02387 seconds (files took 0.63064 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/example_spec.rb:8 # Example#change_c change only ex.c
```

**Comment by ogom** [comment]
rspec の and は & の記号に置きかえることできます。

**Comment by ogom** [comment]
and_not は &! になるかも

**Comment by ogom** [comment]
`RSpec::Matchers.define_negated_matcher :not_change, :change` を試してください。
https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/define-negated-matcher

**Comment by mogumogu-tatsugoro** [comment]
ドキュメントをすみまで読むことで見付けられる

**Comment by mogumogu-tatsugoro** [comment]
Changelog で見つかることも

**Comment by mogumogu-tatsugoro** [comment]
everydayrails に `not_change` の記載はなさそう 👀 
-> everydayrails にフィードバックしてもよさそう

**Comment by mogumogu-tatsugoro** [comment]
OSS はたくさんの人が幸せになる世界を目指している ✨

**Comment by mogumogu-tatsugoro** [comment]
今回困ったこと
- `and not_change` を使いたかった
- `RSpec::Matchers.define_negated_matcher :not_change, :change` を定義すれば `and not_change` を解決できる問題だった
- [ドキュメント](https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/define-negated-matcher)に記載はあるものの、検索して見つけることが困難だった

**Comment by mogumogu-tatsugoro** [comment]
https://github.com/oss-gate/workshop/issues/1421#issuecomment-691442227
これを見付けやすくしたい

**Comment by mogumogu-tatsugoro** [comment]
どこに送るのが適切か

**Comment by ogom** [comment]
https://rspec.info/

**Comment by mogumogu-tatsugoro** [comment]
https://github.com/rspec/rspec-expectations 
上記ドキュメントがある

**Comment by mogumogu-tatsugoro** [comment]
日本語の手順サイトが欲しいというのを書いておけばよかった

**Comment by mogumogu-tatsugoro** [comment]
Github の `readme` を I18n みたいによしなにしてくれたらとてもうれしい

**Comment by mogumogu-tatsugoro** [comment]
日本語のドキュメントは減っている
-> メンテナンスコストが高いので

**Comment by mogumogu-tatsugoro** [comment]
Sidekiq の日本語の保守は @ogom さんがされている ✨

**Comment by mogumogu-tatsugoro** [comment]
znz さんが Ruby の日本語の責任者をされている ✨

**Comment by ogom** [comment]
Rubyリファレンスマニュアル刷新計画

https://github.com/rurema

**Comment by knokmki612** [comment]
おつかれさまでした！
