### ISSUE TITLE
OSS Gate Workshop: online: 2020-10-31: piroor: spader: Work log (demo)

### ISSUE THREAD

**Issue by piroor** [oss-gate/workshop#1427]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by piroor** [comment]
https://twitter.com/RubygemsN/status/1320806514127376384
Twitterで「WebExtensions」の検索結果を見ていたら流れてきた。
https://rubygems.org/gems/spader
Gemのページを見ると、複数のブラウザに対応したWebExtensionsな拡張機能を作るフレームワークと書いてある。
気になる。

**Comment by piroor** [comment]
Gemのページからプロジェクトやリポジトリへのリンクがない。
アカウント名 `cosmic-shovel` プロジェクト名 `spader` でGitHubを見てみたら、リポジトリがあった。
https://github.com/cosmic-shovel/spader

**Comment by piroor** [comment]
READMEを見てみたが、インストール手順は特に書かれていない。
Gemのページには`gem install spader`と書いてあったので、やってみる。

```sh
piro@piro-cf-sv7:~/codes$ mkdir try-spader
piro@piro-cf-sv7:~/codes$ cd try-spader/
piro@piro-cf-sv7:~/codes/try-spader$ gem install spader
ERROR:  Could not find a valid gem 'spader' (>= 0) in any repository
ERROR:  Possible alternatives: shader, spacer, spade, spamer, spider
```

インストールできない。なぜ？

**Comment by piroor** [comment]
バージョンが「0.0.1.pre.pre」となっているせいだろうか。
バージョンを明示してみた。

```sh
piro@piro-cf-sv7:~/codes/try-spader$ gem install spader -v 0.0.1.pre.pre
Fetching: spader-0.0.1.pre.pre.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory.
```

今度はパッケージが見つかった。
ただ、書き込み権限がないので入れられなかった。

```sh
piro@piro-cf-sv7:~/codes/try-spader$ sudo gem install spader -v 0.0.1.pre.pre
[sudo] piro のパスワード:
Fetching: spader-0.0.1.pre.pre.gem (100%)
Successfully installed spader-0.0.1.pre.pre
Parsing documentation for spader-0.0.1.pre.pre
Installing ri documentation for spader-0.0.1.pre.pre
Done installing documentation for spader after 0 seconds
1 gem installed
```

sudoしたらいけた。

**Comment by piroor** [comment]
https://github.com/cosmic-shovel/spader#commands

READMEの最後にコマンドの使い方が少し書いてある。
`spader generate <project_path>` とあるので、やってみる。

```sh
piro@piro-cf-sv7:~/codes/try-spader$ spader generate example
Traceback (most recent call last):
        8: from /usr/local/bin/spader:23:in `<main>'
        7: from /usr/local/bin/spader:23:in `load'
        6: from /var/lib/gems/2.5.0/gems/spader-0.0.1.pre.pre/bin/spader:7:in `<top (required)>'
        5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from /var/lib/gems/2.5.0/gems/spader-0.0.1.pre.pre/lib/spader.rb:12:in `<top (required)>'
        2: from /var/lib/gems/2.5.0/gems/spader-0.0.1.pre.pre/lib/spader.rb:20:in `<module:Spader>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- sassc (LoadError)
```

依存ライブラリが足りてないと言われた。

**Comment by piroor** [comment]
sasscを入れてからやってみた。
native extensionのビルドで結構待たされた……

```sh
piro@piro-cf-sv7:~/codes/try-spader$ sudo gem install sassc
Fetching: sassc-2.4.0.gem (100%)
Building native extensions. This could take a while...
Successfully installed sassc-2.4.0
Parsing documentation for sassc-2.4.0
Installing ri documentation for sassc-2.4.0
Done installing documentation for sassc after 2 seconds
1 gem installed
piro@piro-cf-sv7:~/codes/try-spader$ spader generate example
Traceback (most recent call last):
        8: from /usr/local/bin/spader:23:in `<main>'
        7: from /usr/local/bin/spader:23:in `load'
        6: from /var/lib/gems/2.5.0/gems/spader-0.0.1.pre.pre/bin/spader:7:in `<top (required)>'
        5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        3: from /var/lib/gems/2.5.0/gems/spader-0.0.1.pre.pre/lib/spader.rb:12:in `<top (required)>'
        2: from /var/lib/gems/2.5.0/gems/spader-0.0.1.pre.pre/lib/spader.rb:21:in `<module:Spader>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- uglifier (LoadError)
```

またエラー。今度はuglifierがない。

```sh
piro@piro-cf-sv7:~/codes/try-spader$ sudo gem install uglifier
Fetching: execjs-2.7.0.gem (100%)
Successfully installed execjs-2.7.0
Fetching: uglifier-4.2.0.gem (100%)
Successfully installed uglifier-4.2.0
Parsing documentation for execjs-2.7.0
Installing ri documentation for execjs-2.7.0
Parsing documentation for uglifier-4.2.0
Installing ri documentation for uglifier-4.2.0
Done installing documentation for execjs, uglifier after 3 seconds
2 gems installed
piro@piro-cf-sv7:~/codes/try-spader$ spader generate example
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:135: warning: Insecure world writable dir /home/piro/.local/bin in PATH, mode 040777
What is the name of your extension?
```

uglifierを入れたら動いた。
名前を聞かれた。
exampleと入れてみた。


```sh
piro@piro-cf-sv7:~/codes/try-spader$ spader generate example
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:135: warning: Insecure world writable dir /home/piro/.local/bin in PATH, mode 040777
What is the name of your extension?
example
RUNNING Spader::GenerateCommand
Generating "example" into /mnt/c/Users/piro/codes/try-spader/example/
```

なんかできた。

**Comment by piroor** [comment]
READMEには、`Build a project: spader build <project_path> [options]` と書いてある。
とりあえず何もオプションを指定せずにやってみた。

```sh
piro@piro-cf-sv7:~/codes/try-spader$ cd example
piro@piro-cf-sv7:~/codes/try-spader/example$ ls
_locales  dist  font  html  icon  js  manifest  promo  scss  spader.json  txt
piro@piro-cf-sv7:~/codes/try-spader/example$ spader build .
/var/lib/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:135: warning: Insecure world writable dir /home/piro/.local/bin in PATH, mode 040777
RUNNING Spader::BuildCommand
Building /mnt/c/Users/piro/codes/try-spader/example/ @ v0.0.0/development for 5 browser(s).
Output dir: /mnt/c/Users/piro/codes/try-spader/example/dist/development/chrome/
Output dir: /mnt/c/Users/piro/codes/try-spader/example/dist/development/edge/
Output dir: /mnt/c/Users/piro/codes/try-spader/example/dist/development/firefox/
Output dir: /mnt/c/Users/piro/codes/try-spader/example/dist/development/opera/
Output dir: /mnt/c/Users/piro/codes/try-spader/example/dist/development/safari/
```

なんかできた。
