### ISSUE TITLE
OSS Gate Workshop: online: 2021-7-31: koukikitamura: wicked_pdf: Work log

### ISSUE THREAD

**Issue by koukikitamura** [oss-gate/workshop#1479]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by koukikitamura** [comment]
OSSは[wickec_pdf](https://github.com/mileszs/wicked_pdf) にします!

**Comment by koukikitamura** [comment]
```
$ gem install wicked_pdf
Fetching wicked_pdf-2.1.0.gem
Successfully installed wicked_pdf-2.1.0
Parsing documentation for wicked_pdf-2.1.0
Installing ri documentation for wicked_pdf-2.1.0
Done installing documentation for wicked_pdf after 0 seconds
1 gem installed
```

**Comment by koukikitamura** [comment]
一旦動かしてみます!

```
require 'wicked_pdf'

pdf = WickedPdf.new.pdf_from_string('<h1>Hello There!</h1>')

save_path = 'test.pdf'
File.open(save_path, 'wb') do |file|
  file << pdf
end
```

```
$ ruby test.rb 
Traceback (most recent call last):
        2: from test.rb:3:in `<main>'
        1: from test.rb:3:in `new'
/Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:30:in `initialize': Location of wkhtmltopdf unknown (RuntimeError)
```

**Comment by koukikitamura** [comment]
バイナリがなかったのでwkhtmltopdfのinstall

```
$ gem install wkhtmltopdf-binary
Fetching wkhtmltopdf-binary-0.12.6.5.gem
Successfully installed wkhtmltopdf-binary-0.12.6.5
Parsing documentation for wkhtmltopdf-binary-0.12.6.5
Installing ri documentation for wkhtmltopdf-binary-0.12.6.5
Done installing documentation for wkhtmltopdf-binary after 0 seconds
1 gem installed
```

```
$ wkhtmltopdf --version
wkhtmltopdf 0.12.6 (with patched qt)
```

**Comment by koukikitamura** [comment]
日本語で動かしてみました!

```ruby
require 'wicked_pdf'

WickedPdf.config = {
  exe_path: '/Users/koukikitamura/.rbenv/shims/wkhtmltopdf',
  enable_local_file_access: true
}

pdf = WickedPdf.new.pdf_from_string('<h1>こんにちは!</h1>')

save_path = 'test.pdf'
File.open(save_path, 'wb') do |file|
  file << pdf
end
```

文字化けしました

**Comment by koukikitamura** [comment]
```
require 'wicked_pdf'

WickedPdf.config = {
  exe_path: '/Users/koukikitamura/.rbenv/shims/wkhtmltopdf',
  enable_local_file_access: true
}

pdf = WickedPdf.new.pdf_from_html_file('./test.html')

save_path = 'test.pdf'
File.open(save_path, 'wb') do |file|
  file << pdf
end
```

```
$ ruby test.rb 
Traceback (most recent call last):
        2: from test.rb:8:in `<main>'
        1: from /Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:38:in `pdf_from_html_file'
/Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:82:in `pdf_from_url': PDF could not be generated! (RuntimeError)
 Command Error: Loading pages (1/6)
Error: Failed to load file:///test.html, with network status code 203 and http status code 0 - Error opening /test.html: No such file or directory
Error: Failed loading page file:///./test.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: ContentNotFoundError
        3: from test.rb:8:in `<main>'
        2: from /Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:38:in `pdf_from_html_file'
        1: from /Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:84:in `pdf_from_url'
/Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:85:in `rescue in pdf_from_url': Failed to execute: (RuntimeError)
["/Users/koukikitamura/.rbenv/shims/wkhtmltopdf", "--enable-local-file-access", "file:///./test.html", "/var/folders/hh/b9qbtnsd2r7dzfw8dhsfhn240000gn/T/wicked_pdf_generated_file20210731-69636-1n9kt5s.pdf"]
Error: PDF could not be generated!
 Command Error: Loading pages (1/6)
Error: Failed to load file:///test.html, with network status code 203 and http status code 0 - Error opening /test.html: No such file or directory
Error: Failed loading page file:///./test.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: ContentNotFoundError
```

**Comment by koukikitamura** [comment]
絶対パスに修正

**Comment by koukikitamura** [comment]
meta tagをコメントアウトすると再び文字化けしました!

**Comment by ryomo56** [comment]
https://github.com/mileszs/wicked_pdf/issues/937

**Comment by ryomo56** [comment]
OSSの確認忘れてました（汗
https://opensource.org/licenses/alphabetical

**Comment by koukikitamura** [comment]
MITでした :bow:
https://github.com/mileszs/wicked_pdf/blob/master/LICENSE.txt

**Comment by koukikitamura** [comment]
- issueの説明
- 期待する動作
- 環境


```
## Issue description

## Expected or desired behavior

## System specifications

wicked_pdf gem version (output of `cat Gemfile.lock | grep wicked_pdf`):

wkhtmltopdf version (output of `wkhtmltopdf --version`):

whtmltopdf [provider gem](https://rubygems.org/search?utf8=%E2%9C%93&query=wkhtmltopdf) and version if one is used:

platform/distribution and version (e.g. Windows 10 / Ubuntu 16.04 / Heroku cedar):
```

**Comment by koukikitamura** [comment]
候補
- htmlファイルの指定が絶対パス指定のみだが、相対パスも良いかも

**Comment by koukikitamura** [comment]
本番環境を想定してrubyのdocker image(Debian系)で動作するか検証

```
docker run --name ruby -i -t -v `pwd`:test.rb  -v `pwd  ruby /bin/bash
```

ファイル修正

```
require 'wicked_pdf'

WickedPdf.config = {
  exe_path: '/usr/local/bundle/bin/wkhtmltopdf',
  enable_local_file_access: true
}

pdf = WickedPdf.new.pdf_from_html_file('/var/ruby/test.html')

save_path = 'test.pdf'
File.open(save_path, 'wb') do |file|
  file << pdf
end

文字化けした

![Screen Shot 2021-07-31 at 14 25 56](https://user-images.githubusercontent.com/32995684/127729738-e002064f-74b6-4a0e-ab22-33a4cdd59ad0.png)

```

**Comment by koukikitamura** [comment]
htmlファイルの指定が絶対パス指定のみだが、相対パスも良いかも


## Issue description
`pdf = WickedPdf.new.pdf_from_html_file`を使ってファイルシステム内にあるhtmlファイルからpdfを生成する際に絶対パスだけでなく相対パスでも指定できた方が良いと思います。

## Expected or desired behavior
pdfに変換するhtmlファイルを相対パスで指定できる。

```ruby
require 'wicked_pdf'

WickedPdf.config = {
  exe_path: '/usr/local/bundle/bin/wkhtmltopdf',
  enable_local_file_access: true
}

pdf = WickedPdf.new.pdf_from_html_file('./relative/path/here.html')

save_path = 'filename.pdf'
File.open(save_path, 'wb') do |file|
  file << pdf
end
```

## System specifications
環境依存はありません。

**Comment by koukikitamura** [comment]
issue送りました

https://github.com/mileszs/wicked_pdf/issues/981

**Comment by koukikitamura** [comment]
binaryが見つからなかったときのエラーメッセージがわかりにくい

## Issue description
実行時にwkhtmltopdfのバイナリが見つからない場合のエラーメッセージがわかりにくい

```
$ ruby test.rb
Traceback (most recent call last):
        2: from test.rb:3:in `<main>'
        1: from test.rb:3:in `new'
/Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:30:in `initialize': Location of wkhtmltopdf unknown (RuntimeError)
```

## Expected or desired behavior
詳細なエラーメッセージが表示される。

```
$ ruby test.rb
Not found wkhtmltopdf binary in your system, please download and set it in config.
Traceback (most recent call last):
        2: from test.rb:3:in `<main>'
        1: from test.rb:3:in `new'
/Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:30:in `initialize': Location of wkhtmltopdf unknown (RuntimeError)
```

## System specifications
環境依存はありません。

**Comment by koukikitamura** [comment]
## Issue description
The error message when the wkhtmltopdf binary is not found at runtime is confusing.

```
$ ruby test.rb
Traceback (most recent call last):
        2: from test.rb:3:in `<main>'
        1: from test.rb:3:in `new'
/Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:30:in `initialize': Location of wkhtmltopdf unknown (RuntimeError)
```

## Expected or desired behavior
Detail error message is displayed.

```
$ ruby test.rb
Not found wkhtmltopdf binary in your system, please download and set it in config.
Traceback (most recent call last):
        2: from test.rb:3:in `<main>'
        1: from test.rb:3:in `new'
/Users/koukikitamura/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/wicked_pdf-2.1.0/lib/wicked_pdf.rb:30:in `initialize': Location of wkhtmltopdf unknown (RuntimeError)
```

## System specifications
There is no environment dependence.

**Comment by ryomo56** [comment]
フォントオプション指定のイシューがありました
https://github.com/mileszs/wicked_pdf/issues/883

**Comment by koukikitamura** [comment]
READMEに文字化けするときの説明を追加しました

https://github.com/mileszs/wicked_pdf/pull/983

**Comment by koukikitamura** [comment]
エラーメッセージのissueです

https://github.com/mileszs/wicked_pdf/issues/982
