### ISSUE TITLE
OSS Gate Workshop: online: 2021-07-31: quzq: Redux Toolkit: Work log

### ISSUE THREAD

**Issue by quzq** [oss-gate/workshop#1481]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by quzq** [comment]
git clone https://github.com/reduxjs/redux-toolkit.git
ossをcloneしました。

**Comment by quzq** [comment]
ライセンスファイルを開き、MITライセンスであることを確認した。

**Comment by quzq** [comment]
package.jsonを開き、ビルドコマンドを見つけた。
```
  "scripts": {
    "build": "yarn build:packages",
    "test": "yarn test:packages",
    "build:examples": "yarn workspaces foreach --include '@reduxjs/*' --include '@examples-query-react/*' -vtp run build",
    "build:docs": "yarn workspace website run build",
    "build:packages": "yarn workspaces foreach --include '@reduxjs/*' --include '@rtk-query/*' --topological-dev run build",
    "test:packages": "yarn workspaces foreach --include '@reduxjs/*' --include '@rtk-query/*' run test",
    "dev:docs": "yarn workspace website run start"
  }
```

**Comment by quzq** [comment]
npm iを実行した。

**Comment by quzq** [comment]
build前に必要なpackageをインストールするため。

**Comment by quzq** [comment]
`package-lock.json`が生成されたことを確認した。

**Comment by quzq** [comment]
yarn.lockの存在を確認したので、node_modulesフォルダとpackage-lock.jsonを削除し、npmインストールを取り消した。

**Comment by quzq** [comment]
開発方法を公式サイトで探すも見つけられなかったので、githubに移動し、CONTRIBUTING.mdを見つけた。
中身を確認すると、手順の記述があった。

**Comment by quzq** [comment]
yarn

**Comment by ogom** [comment]
実際に参照したURLのリンクを記載するとよいです。

**Comment by quzq** [comment]
ありがとうございます。修正してurlを埋めました。

**Comment by quzq** [comment]
`yarn test`を実行すると、エラーが発生した。
```
 YN0000:     console.error
➤ YN0000:       Error: rejected
➤ YN0000:           at Object.<anonymous> (C:\Users\USER\repos\redux-toolkit\packages\toolkit\src\query\tests\retry.test.ts:294:37)
➤ YN0000:           at Object.asyncJestTest (C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
➤ YN0000:           at C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:45:12
➤ YN0000:           at new Promise (<anonymous>)
➤ YN0000:           at mapper (C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
➤ YN0000:           at C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:75:41
➤ YN0000:           at runMicrotasks (<anonymous>)
➤ YN0000:           at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000:
➤ YN0000:       315 |         )
➤ YN0000:       316 |       } else {
➤ YN0000:     > 317 |         console.error(error)
➤ YN0000:           |                 ^
➤ YN0000:       318 |       }
➤ YN0000:       319 |       throw error
➤ YN0000:       320 |     }
➤ YN0000:
➤ YN0000:       at BufferedConsole.consoleObject.<computed> [as error] (../../node_modules/filter-console/index.js:46:4)
➤ YN0000:       at executeEndpoint (src/query/core/buildThunks.ts:317:17)
➤ YN0000:           at runMicrotasks (<anonymous>)
```

**Comment by quzq** [comment]
テスト結果ログを確認すると、すべてpassしており、test失敗ではなかった。

**Comment by quzq** [comment]
`yarn build`してビルド結果を確認した。

**Comment by quzq** [comment]
```
$ yarn build
➤ YN0000: Build artifact: dist\redux-toolkit.modern.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\redux-toolkit.esm.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\redux-toolkit.modern.development.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\redux-toolkit.cjs.development.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\redux-toolkit.modern.production.min.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\redux-toolkit.cjs.production.min.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\redux-toolkit.umd.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\redux-toolkit.umd.min.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\rtk-query.modern.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\query\rtk-query.modern.production.min.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\query\rtk-query.cjs.production.min.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\rtk-query.cjs.development.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\rtk-query.modern.development.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\query\rtk-query.esm.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\rtk-query.umd.min.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\rtk-query.umd.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.modern.production.min.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.cjs.development.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.modern.development.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.modern.js, settings:  { target: 'es2017', output: 'ES2017' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.esm.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.cjs.production.min.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.umd.min.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build artifact: dist\query\react\rtk-query-react.umd.js, settings:  { target: 'es2015', output: 'ES5' }
➤ YN0000: Build "graphqlRequestBaseQuery" to dist:
➤ YN0000:         345 B: index.cjs.gz
➤ YN0000:         305 B: index.cjs.br
➤ YN0000:         288 B: index.modern.js.gz
➤ YN0000:         249 B: index.modern.js.br
➤ YN0000:         356 B: index.module.js.gz
➤ YN0000:         315 B: index.module.js.br
➤ YN0000:         432 B: index.umd.js.gz
➤ YN0000:         368 B: index.umd.js.br
➤ YN0000: Done in 2m 33s
```

**Comment by quzq** [comment]
build すると、packages/toolkit/distに結果が出力された。

**Comment by quzq** [comment]
失敗ではないがtestコマンドの結果にエラー出力されると、エラーが失敗したと勘違いするかもしれない。

**Comment by quzq** [comment]
test suiteが１つスキップされているのも気になる。

**Comment by quzq** [comment]
test実行ログ内のエラー出力を行っているコードは以下。
```
      if (error instanceof HandledError) {
        return rejectWithValue(error.value, { baseQueryMeta: error.meta })
      }
      if (
        typeof process !== 'undefined' &&
        process.env.NODE_ENV === 'development'
      ) {
        console.error(
          `An unhandled error occured processing a request for the endpoint "${arg.endpointName}".
In the case of an unhandled error, no tags will be "provided" or "invalidated".`,
          error
        )
      } else {
        console.error(error)
      }
```
この`console.error(error)`に関して、テスト実行中に出力しないようにできないだろうか。

**Comment by quzq** [comment]
issueを`console.error(error)`で検索すると、`log unhandled errors during request to console 
`という１件が見つかる。
内容を確認し、 Files changedを確認すると、該当箇所の変更がなされた部分だった。
```
      if (error instanceof HandledError) {
        return rejectWithValue(error.value, { baseQueryMeta: error.meta })
      }
      if (
        typeof process !== 'undefined' &&
        process.env.NODE_ENV === 'development'
      ) {
        console.error(`An unhandled error occured processing a request for the endpoint "${arg.endpointName}".
In the case of an unhandled error, no tags will be "provided" or "invalidated".`, error)
      } else {
        console.error(error)
      } 
      throw error
    }
  }
```

**Comment by quzq** [comment]
https://github.com/reduxjs/redux-toolkit/pull/1251/files

**Comment by quzq** [comment]
テストコマンド実行時、ログに不要なエラーがコンソール出力される

I run tests for all packages with `yarn test`.

ログ内に以下のようなconsole.error()が出力された。
```
➤ YN0000:     console.error
➤ YN0000:       Error: rejected
➤ YN0000:           at Object.<anonymous> (C:\Users\USER\repos\redux-toolkit\packages\toolkit\src\query\tests\retry.test.ts:74:37)
➤ YN0000:           at Object.asyncJestTest (C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:106:37)
➤ YN0000:           at C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:45:12
➤ YN0000:           at new Promise (<anonymous>)
➤ YN0000:           at mapper (C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:28:19)
➤ YN0000:           at C:\Users\USER\repos\redux-toolkit\node_modules\jest-jasmine2\build\queueRunner.js:75:41
➤ YN0000:           at runMicrotasks (<anonymous>)
➤ YN0000:           at processTicksAndRejections (internal/process/task_queues.js:97:5)
➤ YN0000:
➤ YN0000:       315 |         )
➤ YN0000:       316 |       } else {
➤ YN0000:     > 317 |         console.error(error)
➤ YN0000:           |                 ^
➤ YN0000:       318 |       }
➤ YN0000:       319 |       throw error
➤ YN0000:       320 |     }
```

console.error()が出力されず、純粋なテストログを出力してほしい。

[log unhandled errors during request to console #1251](https://github.com/reduxjs/redux-toolkit/pull/1251) にて、[buildThunks.ts](https://github.com/reduxjs/redux-toolkit/pull/1251/files#diff-0ffe77a934f2eff0ea79dcc0022def9a4888740a0ce9f2cc82e3f61212753a61)が変更されて以降に発生するようになった現象と思われます。

**Comment by quzq** [comment]
テストコマンド実行時、ログに不要なエラーがコンソール出力される
Unnecessary errors in the log are consoled when running test commands

I run tests for all packages with yarn test.

ログ内に以下のようなconsole.error()が出力された。
The following console.error() was output in the log.

console.error()が出力されず、純粋なテストログを出力してほしい。
Console.error() is not output, and I want you to output a pure test log.

log unhandled errors during request to console #1251 にて、buildThunks.tsが変更されて以降に発生するようになった現象と思われます。
Log unhandled errors during request to console #1251 seems to occur since buildThunks.ts changed.

**Comment by quzq** [comment]
テストコマンド実行時、ログに不要なエラーがコンソール出力される
Unnecessary errors in the log are consoled when running test commands

I run tests for all packages with yarn test.

ログ内に以下のようなconsole.error()が出力された。
The following console.error() was output in the log.

log unhandled errors during request to console #1251 にて、buildThunks.tsが変更されて以降に発生するようになった現象と思われます。

It shows from [buildThunks.ts](https://github.com/reduxjs/redux-toolkit/pull/1251/files#diff-0ffe77a934f2eff0ea79dcc0022def9a4888740a0ce9f2cc82e3f61212753a61) changed in [log unhandled errors during request to console #1251](https://github.com/reduxjs/redux-toolkit/pull/1251).

**Comment by edvakf** [comment]
This has started to occur since buildThunks.ts was changed in log unhandled errors during request to console #1251.

**Comment by quzq** [comment]
[issue](https://github.com/reduxjs/redux-toolkit/issues/1369)として報告した。
