### ISSUE TITLE
OSS Gate Workshop: PHP Lovers: 2023-10-09:  ast.: goodby/csv: Work log

### ISSUE THREAD

**Issue by astandkaya** [oss-gate/workshop#1710]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by astandkaya** [comment]
goodby/csvに決めました
https://packagist.org/packages/goodby/csv

**Comment by astandkaya** [comment]
ドキュメントページは無し
README.mdに使用方法などの記載があった
https://github.com/goodby/csv/blob/master/README.md

**Comment by astandkaya** [comment]
composerはインストールされているので、下記の`composer.json`ファイルを作った
```
{
    "require": {
        "goodby/csv": "*"
    }
}
```

**Comment by astandkaya** [comment]
ドキュメントには`php composer.phar install`を実行するように書いてあるが、すでにcomposerが入っているので`composer install`を実行する。
（ここはちょっと不親切？　それとも常に最新のcomposerを使ってほしいということ？）

**Comment by astandkaya** [comment]
一旦成功した。（worningが出てる？）

全文
```
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking goodby/csv (1.3.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' (21.01+) may remediate them.
  - Downloading goodby/csv (1.3.0)
  - Installing goodby/csv (1.3.0): Extracting archive
Generating autoload files
```

worning部分
```
As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' or '7z' (21.01+) may remediate them.
```

**Comment by astandkaya** [comment]
`unzip`か`7z`が必要？

必須ではないっぽいのでrequirementsには書いてない（？）
https://github.com/goodby/csv#requirements

**Comment by astandkaya** [comment]
そういえば`composer.json`をわざわざ手動で作成しているが`composer require goodby/csv`でも良さそうな気がした

**Comment by astandkaya** [comment]
`example`ディレクトリがあった。
非常にありがたいです。
https://github.com/goodby/csv/tree/master/example

**Comment by astandkaya** [comment]
`example`ディレクトリをコピーしてきた
`cp -r vendor/goodby/csv/example ./`

**Comment by astandkaya** [comment]
`tsv-sample.php`以外のサンプルはDBが必要そうなので、いったん`tsv-sample.php`を実行してみる。
https://github.com/goodby/csv/blob/master/example/tsv-sample.php

`php example/tsv-sample.php`

**Comment by astandkaya** [comment]
エラーが出た
ライブラリの問題？こちらの環境の問題？
```
PHP Fatal error:  Uncaught RuntimeException: SplFileObject::__construct(temperature.tsv): Failed to open stream: No such file or directory in /home/kasugai/20231009/work/vendor/goodby/csv/src/Goodby/CSV/Import/Standard/Lexer.php:52
Stack trace:
#0 /home/kasugai/20231009/work/vendor/goodby/csv/src/Goodby/CSV/Import/Standard/Lexer.php(52): SplFileObject->__construct()
#1 /home/kasugai/20231009/work/example/tsv-sample.php(28): Goodby\CSV\Import\Standard\Lexer->parse()
#2 {main}
  thrown in /home/kasugai/20231009/work/vendor/goodby/csv/src/Goodby/CSV/Import/Standard/Lexer.php on line 52
```

**Comment by astandkaya** [comment]
通常のインストールは問題なさそうなので、contributing側を試す。

**Comment by astandkaya** [comment]
cloneしてくる
`https://github.com/goodby/csv.git`

**Comment by astandkaya** [comment]
`composer install`する。

ドキュメントでは`composer.phar install --dev`と書いてある（composerはすでに入っているので個人的にはちょっと分かりにくい？）

**Comment by astandkaya** [comment]
`composer install`を実行してエラーが出た

```
In RootPackageLoader.php line 160:

  require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstrea
  m instead.


update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]
```

**Comment by astandkaya** [comment]
composer.jsonのrequire-devに`mikey179/vfsStream`と大文字を混ぜてしまっているため、`mikey179/vfsstream`に修正

**Comment by astandkaya** [comment]
再度インストールして、無事通った。
```
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Lock file operations: 12 installs, 0 updates, 0 removals
  - Locking mikey179/vfsstream (v1.6.11)
  - Locking mockery/mockery (0.7.2)
  - Locking phpunit/php-code-coverage (1.2.18)
  - Locking phpunit/php-file-iterator (1.4.5)
  - Locking phpunit/php-text-template (1.2.1)
  - Locking phpunit/php-timer (1.0.8)
  - Locking phpunit/php-token-stream (1.2.2)
  - Locking phpunit/phpunit (3.7.38)
  - Locking phpunit/phpunit-mock-objects (1.2.3)
  - Locking suin/php-expose (1.0)
  - Locking symfony/polyfill-ctype (v1.28.0)
  - Locking symfony/yaml (v2.8.52)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Downloading mikey179/vfsstream (v1.6.11)
  - Downloading mockery/mockery (0.7.2)
  - Downloading phpunit/php-token-stream (1.2.2)
  - Downloading symfony/yaml (v2.8.52)
  - Downloading phpunit/php-text-template (1.2.1)
  - Downloading phpunit/phpunit-mock-objects (1.2.3)
  - Downloading phpunit/php-timer (1.0.8)
  - Downloading phpunit/php-file-iterator (1.4.5)
  - Downloading phpunit/php-code-coverage (1.2.18)
  - Downloading phpunit/phpunit (3.7.38)
  - Downloading suin/php-expose (1.0)
  - Installing mikey179/vfsstream (v1.6.11): Extracting archive
  - Installing mockery/mockery (0.7.2): Extracting archive
  - Installing phpunit/php-token-stream (1.2.2): Extracting archive
  - Installing symfony/polyfill-ctype (v1.28.0): Extracting archive
  - Installing symfony/yaml (v2.8.52): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/phpunit-mock-objects (1.2.3): Extracting archive
  - Installing phpunit/php-timer (1.0.8): Extracting archive
  - Installing phpunit/php-file-iterator (1.4.5): Extracting archive
  - Installing phpunit/php-code-coverage (1.2.18): Extracting archive
  - Installing phpunit/phpunit (3.7.38): Extracting archive
  - Installing suin/php-expose (1.0): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
```

worningが出ている？（いったんスルー）
```
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by astandkaya** [comment]
下記コマンドでテスト実行
`./vendor/bin/phpunit`

**Comment by astandkaya** [comment]
phpunitが古い（？）
```
    "require-dev": {
        "phpunit/phpunit": "3.7.*",
        "mockery/mockery": "^0.7.2",
        "suin/php-expose": "^1.0",
        "mikey179/vfsstream": "^1.1"
    },
```

**Comment by astandkaya** [comment]
いったん↓に関してのPRを作成する。
https://github.com/oss-gate/workshop/issues/1710#issuecomment-1752290207

**Comment by daipom** [comment]
> いったん↓に関してのPRを作成する。 [#1710 (comment)](https://github.com/oss-gate/workshop/issues/1710#issuecomment-1752290207)

https://github.com/goodby/csv/pull/94
