### ISSUE TITLE
OSS Gate Workshop PHP Lovers: 2023-10-09: picopico: jestjs/jest: Work log

### ISSUE THREAD

**Issue by picopicos** [oss-gate/workshop#1715]

**Comment by picopicos** [comment]
https://github.com/sebastianbergmann/phpunit/

**Comment by picopicos** [comment]
https://github.com/jestjs/jest/issues

**Comment by picopicos** [comment]
`CONTRIBUTING.md`読了

**Comment by picopicos** [comment]
これを見ています。

https://github.com/jestjs/jest/issues/14601

```
~/projects/stackblitz-starters-7snujh 1s
❯ yarn jest
yarn run v1.22.19
$ /home/projects/stackblitz-starters-7snujh/node_modules/.bin/jest
 FAIL  packages/require-resolve-paths.test.js
  ● require-resolve-paths

    Expected value   undefined
    Received:
      undefined
    
    Message:
      Cannot resolve module '@foo/js' from paths ['/home/projects/stackblitz-starters-7snujh/packages'] from /home/projects/stackblitz-starters-7snujh/packages/require-resolve-paths.test.js

    Difference:

    Compared values have no visual difference.Error:

      1 | it('require-resolve-paths', () => {
      2 |   const paths = [__dirname];
    > 3 |   const result = require.resolve('@foo/js', { paths });
        |                          ^
      4 |
      5 |   expect(typeof result).toBe('string');
      6 |   expect(result).toMatch(/\/src\/\@foo\/js\/index.js$/);

      at new ModuleNotFoundError (../node_modules/jest-resolve/build/ModuleNotFoundError.js:79:5)
      at Object.resolve (require-resolve-paths.test.js:3:26)

 PASS  packages/require-resolve.test.js

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 failed, 1 passed, 2 total
Snapshots:   0 total
Time:        3.25 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by picopicos** [comment]
`require.resolve()`を使った時にJestの設定の[moduleNameMapper](https://jestjs.io/ja/docs/configuration#modulenamemapper-objectstring-string--arraystring)が解決出来ない問題。

`moduleNameMapper`は正規表現でテストの際にモジュール依存を別ファイルにマップさせるオプションで、テスト時にモジュールをスタブしたい時に使うことが出来る。

**Comment by picopicos** [comment]
[require.resolve()](https://nodejs.org/api/modules.html#requireresolverequest-options)はNode.jsの提供する標準関数で、モジュールパスから`filename`を取得する関数。


Jestのランタイムで`require`が`moduleNameMapper`の設定によって解決されている処理があると思うので、その処理を見てみる。

**Comment by picopicos** [comment]
`paths`を指定した場合に通らない。

`paths`を指定している場合のテストを見たら、そのPRがあったので、それを見てみる。

https://github.com/jestjs/jest/pull/11943

**Comment by muno92** [comment]
該当処理が追加された時のPRを突き止める所まで出来ていてすごいです

**Comment by picopicos** [comment]
`require.resolve()`の`options.path`をJestランタイムでサポートするPRを見つけたが、`moduleNameMapper`の議論は特に無かった。 https://github.com/jestjs/jest/pull/6471

【今後の方針】
バグか仕様かは分からないが、一度修正したものをissueに貼って掲示してみる。
もし仕様であれば、その振る舞いを検証するテストが書かれていないので、テストを書いて再度送る。
