### ISSUE TITLE
OSS Gate Workshop: online: 2023-12-09: obregonia1: ridgepole: Work log

### ISSUE THREAD

**Issue by obregonia1** [oss-gate/workshop#1744]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by obregonia1** [comment]
https://github.com/ridgepole/ridgepole
https://github.com/vifreefly/kimuraframework
https://github.com/rubocop/rubocop

**Comment by obregonia1** [comment]
ridgepole をやる

**Comment by obregonia1** [comment]
ライセンスは MIT License

**Comment by obregonia1** [comment]
```
$ gem install ridgepole
```

**Comment by obregonia1** [comment]
https://github.com/ridgepole/ridgepole#help
help の項目に `$ ridgepole -h` の実行結果が載っているがコマンド自体は省略されている(不要？)

**Comment by obregonia1** [comment]
```
$ mkdir oss-gate
$ cd oss-gate
$ git init
```

**Comment by obregonia1** [comment]
config.yml 作成
```yaml
adapter: mysql2
encoding: utf8
database: blog
username: root
```

**Comment by obregonia1** [comment]
コマンドがエラーになる
```
$ ridgepole -c config.yml --export -o Schemafile

/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/dependency.rb:311:in `to_specs': Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? Could not find 'mysql2' (~> 0.5) among 244 total gem(s) (LoadError)
Checked in 'GEM_PATH=/Users/kentaro/.gem/ruby/3.1.0:/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0' , execute `gem env` for more information
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/dependency.rb:323:in `to_spec'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/mysql2_adapter.rb:6:in `<top (required)>'
	from <internal:/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:268:in `resolve_pool_config'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_handling.rb:52:in `establish_connection'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ridgepole-2.0.1/lib/ridgepole/client.rb:8:in `initialize'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ridgepole-2.0.1/bin/ridgepole:181:in `new'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ridgepole-2.0.1/bin/ridgepole:181:in `<top (required)>'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/bin/ridgepole:25:in `load'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/bin/ridgepole:25:in `<main>'
/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'mysql2' (~> 0.5) among 244 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/kentaro/.gem/ruby/3.1.0:/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0' , execute `gem env` for more information
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/dependency.rb:323:in `to_spec'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/mysql2_adapter.rb:6:in `<top (required)>'
	from <internal:/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:268:in `resolve_pool_config'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/connection_handler.rb:129:in `establish_connection'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_handling.rb:52:in `establish_connection'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ridgepole-2.0.1/lib/ridgepole/client.rb:8:in `initialize'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ridgepole-2.0.1/bin/ridgepole:181:in `new'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/ridgepole-2.0.1/bin/ridgepole:181:in `<top (required)>'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/bin/ridgepole:25:in `load'
	from /Users/kentaro/.asdf/installs/ruby/3.1.2/bin/ridgepole:25:in `<main>'
```

**Comment by obregonia1** [comment]
```
$ gem i mysql2
```

**Comment by obregonia1** [comment]
```
$ ridgepole -c config.yml --export -o Schemafile
[ERROR] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
	/Users/kentaro/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/activerecord-7.0.4/lib/active_record/connection_adapters/mysql2_adapter.rb:53:in `rescue in new_client'
```
mysql サーバーが立ち上がってない？

**Comment by obregonia1** [comment]
```
$ brew services start mysql
```

**Comment by obregonia1** [comment]
Schemafile 作成
```
create_table "articles", force: :cascade do |t|
  t.string   "title"
  t.text     "text"
  t.datetime "created_at"
  t.datetime "updated_at"
end
```

**Comment by obregonia1** [comment]
rails アプリを作成
```
rails new oss-gate
```

**Comment by obregonia1** [comment]
```
$ cd oss-gate
$ bundle install
$ bin/rails db:create
```

**Comment by obregonia1** [comment]
sqlite で作ってしまったので config.yml 変更
```
- adapter: mysql2
+ adapter: sqlite3
```

**Comment by obregonia1** [comment]
```
$ ridgepole -c config.yml --export -o Schemafile
Export Schema to `Schemafile`
```

**Comment by obregonia1** [comment]
```
$ git add .
$ git commit -m 'first commit'  -a
```

**Comment by obregonia1** [comment]
sqlite は使えないみたいなので rails アプリを作り直す
```
$ rails new oss-gate -d mysql
$ bundle install
$ bin/rails db:create
```

**Comment by obregonia1** [comment]
一旦 articles テーブル作成
```
$ rails generate migration CreateArticles
      invoke  active_record
      create    db/migrate/20231209072937_create_articles.rb
```

```
$ vi db/migrate/20231209072937_create_articles.rb

class CreateArticles < ActiveRecord::Migration[7.0]
  def change
    create_table :articles do |t|
      t.string :title
      t.text :body

      t.timestamps
    end
  end
end
```

```
$ rails db:migrate
```

**Comment by obregonia1** [comment]
DB のスキーマをもとに Schemafile を生成
```
$ ridgepole -c config.yml --export -o Schemafile
Export Schema to `Schemafile`
```
```
$ cat Schemafile

# -*- mode: ruby -*-
# vi: set ft=ruby :
create_table "articles", charset: "utf8mb4", collation: "utf8mb4_0900_ai_ci", force: :cascade do |t|
  t.string "title"
  t.text "body"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
end
```

**Comment by obregonia1** [comment]
```
$ git add .
$ git commit -m 'first commit'  -a
```

**Comment by obregonia1** [comment]
カラムを追加する
```
$ vi Schemafile

  t.text 'body'
+  t.text 'author'
  t.datetime 'created_at', null: false
```

**Comment by obregonia1** [comment]
dry-run する
```
$ ridgepole -c config.yml --apply --dry-run

Apply `Schemafile` (dry-run)
add_column("articles", "author", :text, **{:after=>"body", :limit=>65535})

# ALTER TABLE `articles` ADD `author` text AFTER `body`
```
カラムが追加されている

**Comment by obregonia1** [comment]
apply する
```
$ ridgepole -c config.yml --apply

Apply `Schemafile`
-- add_column("articles", "author", :text, {:after=>"body", :limit=>65535})
   -> 0.0101s
```

**Comment by komagata** [comment]
sqliteは使えなさそうな雰囲気がありました。

**Comment by obregonia1** [comment]
@komagata 
ありがとうございます！

**Comment by obregonia1** [comment]
https://github.com/ridgepole/ridgepole/blob/2.0/lib/ridgepole/cli/config.rb
ここでアダプターを設定している

**Comment by komagata** [comment]
https://github.com/ridgepole/ridgepole/blob/4bdef4d16ea7660812f0eb86b87db1dd780712ea/lib/ridgepole/connection_adapters.rb#L5-L11

こう書いてあるのでMySQLとPostgreSQLのみ対応っぽいです。

**Comment by obregonia1** [comment]
なるほどー！ありがとうございます！

**Comment by obregonia1** [comment]
https://github.com/ridgepole/ridgepole#usage

例を以下のようにするとよさそう
```
$ cat config.yml
adapter: mysql2(or postgres)
encoding: utf8
database: blog
username: root
```

**Comment by obregonia1** [comment]
https://github.com/ridgepole/ridgepole/compare/2.0...obregonia1:ridgepole:2.0
プッシュしたので description を考える

**Comment by obregonia1** [comment]
- ヘルプを出力するためのコマンドを明示的に追加しました
- config.yml に記載するアダプターを mysql2 か postgresql のどちらかを書くように例示しました

**Comment by obregonia1** [comment]
ChatGPT に訳してもらった
- Explicitly added a command to output help.
- Illustrated in config.yml to write either mysql2 or postgresql as the adapter.

**Comment by obregonia1** [comment]
https://github.com/ridgepole/ridgepole/pull/457
PR 作成

**Comment by komagata** [comment]
@obregonia1 PRのタイトルを具体的に書いた方がいいかもです。

受け取ったプロジェクトの人からすると「README修正」というPRが来たという感じになってしまうので。

以前のワークショップの時のIssue/PRなどを参考にすると良いかもです〜。
https://github.com/oss-gate/workshop/wiki/Workshop%E3%81%AE%E6%88%90%E6%9E%9C%E7%89%A92023%E2%80%9009%E2%80%9030

**Comment by obregonia1** [comment]
テーブル名をリネームしてみる
```
$ vi Schemafile

- create_table 'articles' do |t|
+ create_table 'user_articles', renamed_from: 'articles' do |t|
```
```
$ ridgepole -c config.yml --apply --dry-run
Apply `Schemafile` (dry-run)
rename_table("articles", "user_articles")

# RENAME TABLE `articles` TO `user_articles`
```

**Comment by obregonia1** [comment]
@komagata 
了解しました🙆‍♂️

**Comment by komagata** [comment]
PRを受ける人の気持ちに立って考えると良いかもです。

いきなり「AAAを修正した」とだけくるといろいろ困るかもです。
元になるIssueがない場合は何故その変更が必要なのか（何が困るのか）などを丁寧に書いた方が良いと思います。

これは必須ではないですが、PRする側は変更を取り込んでもらう側なので、初めてIssueやPRを送る場合は感謝など言葉を付け加えてから始めると取り入れられやすいです。

**Comment by komagata** [comment]
この辺りとかも参考になると思います〜
https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/examples.md

**Comment by komagata** [comment]
設定ファイルの記載例にちょこっと追加するよりも、そもそも対応DBの記述をREADMEに文章で追加した方が僕らのように迷わないかもと思いました〜。
