### ISSUE TITLE
OSS Gate Workshop: techouse: 2024-04-18: FujiokaD: redis-rb: Work log

### ISSUE THREAD

**Issue by FujiokaD** [oss-gate/workshop#1809]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by FujiokaD** [comment]
最近redisを勉強する必要があるのでredisを見ていたら、サポーターの方からrubyで書かれたredis-rbというgemがあると聞いたのでちょうど良いと思い見てみる

**Comment by FujiokaD** [comment]
google で `redis rb` を検索して出てくる一番うえのリポジトリがそれっぽいのでこちらを見てみる
https://github.com/redis/redis-rb

**Comment by FujiokaD** [comment]
githubのLisenceにはMITライセンスと書いてあるのでOSSの定義で問題ない
https://github.com/redis/redis-rb/blob/master/LICENSE

**Comment by FujiokaD** [comment]
自分のローカル開発に使うディレクトリから新しくディレクトリを掘ってとりあえず Getting started の説明のまま従う


```
mkdir redis-rb-practice
cd redis-rb-practice  
gem install redis
```
出力

> Fetching redis-5.2.0.gem
> Fetching redis-client-0.22.1.gem
> Successfully installed redis-client-0.22.1
> Successfully installed redis-5.2.0
> Parsing documentation for redis-client-0.22.1
> Installing ri documentation for redis-client-0.22.1
> Parsing documentation for redis-5.2.0
> Installing ri documentation for redis-5.2.0
> Done installing documentation for redis-client, redis after 0 seconds
> 2 gems installed

**Comment by FujiokaD** [comment]
irbを使って説明のままredisの接続をしようとしたら例外が出た
irb(main):001> require "redis"
=> true
irb(main):002> redis = Redis.new
=> #<Redis client v5.2.0 for redis://localhost:6379>
irb(main):003> redis.set("mykey", "hello world")
/Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379) (Redis::CannotConnectError)
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:1214:in `connect_nonblock'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:56:in `connect_internal'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:137:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:642:in `block in tcp'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:227:in `each'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:227:in `foreach'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:632:in `tcp'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/ruby_connection.rb:119:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/ruby_connection.rb:51:in `initialize'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:746:in `new'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:746:in `block in connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/middlewares.rb:12:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:745:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:732:in `raw_connection'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:697:in `ensure_connected'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:292:in `call_v'
        ... 9 levels...
/Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379) (RedisClient::CannotConnectError)
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:1214:in `connect_nonblock'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:56:in `connect_internal'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:137:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:642:in `block in tcp'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:227:in `each'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:227:in `foreach'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:632:in `tcp'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/ruby_connection.rb:119:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/ruby_connection.rb:51:in `initialize'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:746:in `new'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:746:in `block in connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/middlewares.rb:12:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:745:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:732:in `raw_connection'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:697:in `ensure_connected'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:292:in `call_v'
        ... 9 levels...
/Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 127.0.0.1:6379 (Errno::ECONNREFUSED)
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:1214:in `connect_nonblock'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:56:in `connect_internal'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:137:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:642:in `block in tcp'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:227:in `each'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:227:in `foreach'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/3.0.0/socket.rb:632:in `tcp'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/ruby_connection.rb:119:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/ruby_connection.rb:51:in `initialize'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:746:in `new'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:746:in `block in connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client/middlewares.rb:12:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:745:in `connect'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:732:in `raw_connection'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:697:in `ensure_connected'
        from /Users/fujiokadaiki/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-client-0.22.1/lib/redis_client.rb:292:in `call_v'
        ... 9 levels...
irb(main):004>

**Comment by FujiokaD** [comment]
Connection refused - connect(2) for 127.0.0.1:6379 (redis://localhost:6379) (Redis::CannotConnectError)
の文言から自分の環境でTCPポートが埋まっているのではないかと考えた。

記憶の限りでポート6379を使っているのは開発環境で使用しているdockerによるものだと思いdockerの状況を`docker ps`で確認したが
Cannot connect to the Docker daemon at unix:///Users/fujiokadaiki/.docker/run/docker.sock. Is the docker daemon running?
と出る

**Comment by FujiokaD** [comment]
`lsof -i :6379`でポートの使用状況を確認するも何も出力が得られなかった

**Comment by FujiokaD** [comment]
このredis-rb は`A Ruby client that tries to match [Redis](https://redis.io/)' API one-to-one, while still providing an idiomatic interface.`とあり、rubyで書かれたクライアントのgemであることを認識していなかった

redisサーバーを立ち上げ上記のコマンドを叩くとできた
irb(main):001> require "redis"
=> true
irb(main):002> redis = Redis.new
=> #<Redis client v5.2.0 for redis://localhost:6379>
irb(main):003> redis.set("mykey", "hello world")
=> "OK"

**Comment by FujiokaD** [comment]
特段詰まっていなかったのでサポーターの方に助けをもらう
視点を変え最新版のものをcloneして見るという手法があると思いgithubのトップを見るとmainの最新版のCIが fail しているのが気になった

**Comment by FujiokaD** [comment]
CIの内容を見ると特に失敗しているテストはない様子だがErrorは出ている

<img width="1121" alt="スクリーンショット 2024-04-18 12 07 32" src="https://github.com/oss-gate/workshop/assets/82016394/5fdcb1fc-217b-41db-9792-a6b5b61f8ad7">
<img width="1037" alt="スクリーンショット 2024-04-18 12 07 46" src="https://github.com/oss-gate/workshop/assets/82016394/ad10ee17-0830-40f8-a238-86c88afb5187">

**Comment by FujiokaD** [comment]
githubの最新版はstableではないことがあるケースがあるので深追いせずにgetting startedに戻る

エラーハンドリングの欄
https://github.com/redis/redis-rb?tab=readme-ov-file#error-handling

自分はファイルでサンプルコードを動かしていたのだが、標準出力に何も表示されずそれだと例外が上がっているのかわからなかった
```
require "redis"

redis = Redis.new(:timeout => 1)

begin
  redis.ping
  
rescue Redis::BaseError => e
  e.inspect
# => #<Redis::CannotConnectError: Timed out connecting to Redis on 10.0.1.1:6380>
  e.message
# => Timed out connecting to Redis on 10.0.1.1:6380
end
```

**Comment by FujiokaD** [comment]
特に何も見つからないのでドキュメント見ながらコマンドを実行中
https://rubydoc.info/gems/redis/Redis

**Comment by FujiokaD** [comment]
redisに登録されているキー一覧を探すコマンド
`redis.keys`を見ると Find all keys matching the given pattern. と書いてある

patternというくらいだからきっと正規表現なのだろうと^hogeとかを記載してみて関係のないキーを除いたものを表示しようとするも空配列が返ってくる

インターネットを調べるとredisが受け付けている正規表現には制限があり、rubyのRegexpの記法ではサポートされていないものがあるみたい

実際にサーバーで叩かれているであろうコマンドの公式説明
https://redis.io/docs/latest/commands/keys/

> Supported glob-style patterns:
> 
> h?llo matches hello, hallo and hxllo
> h*llo matches hllo and heeeello
> h[ae]llo matches hello and hallo, but not hillo
> h[^e]llo matches hallo, hbllo, ... but not hello
> h[a-b]llo matches hallo and hbllo

the given patternとあると全ての内容が入力可能な印象を受けるため、このドキュメンテーションについて報告を立てる

**Comment by FujiokaD** [comment]
事象 
  ドキュメントの正規表現に対する記載が正確ではなくてわかりづらい
概要
  redisのキー一覧を全て取得するメソッドであるredis.keys(pattern='*')においてrdocの説明では Find all keys matching the given pattern.となっている。
しかし^hoge や $hoge などといった正規表現を入力しても対応するkeyの一覧を取得することができない
 これはpatternに入力できる表現はrubyの正規表現ではなく、redisが受け付けられる正規表現のみであると推測される
https://redis.io/docs/latest/commands/keys/
ドキュメントを見ればわかるようにrdocでの記載は pattern → pattern provided by redis 等にすべきなのではないか

**Comment by FujiokaD** [comment]
PR向けに清書

タイトル: ドキュメントの正規表現に対する記載が正確でない

[Redis::Commands::Keys#keys](https://rubydoc.info/gems/redis/Redis%2FCommands%2FKeys:keys) のrdocの説明には _Find all keys matching the given pattern._ と記載してある
pattern が許容できる正規表現が不明瞭であるため、redisが許容できる正規表現と修正するとわかりやすくなると考えている

patternが説明に利用されている箇所は vscode の文字検索機能を活用したところ

- Redis::Distributed#keys
- Redis::Distributed#psubscribe
- Redis::Distributed#punsubscribe
- Redis::Commands::Hashes#hscan
- Redis::Commands::Hashes#hscan_each
- Redis::Commands::Keys#scan
- Redis::Commands::Keys#scan_each
- Redis::Commands::Keys#keys
- Redis::Commands::Pubsub#psubscribe
- Redis::Commands::Pubsub#psubscribe_with_timeout
- Redis::Commands::Pubsub#punsubscribe
- Redis::Commands:: Sets#sscan
- Redis::Commands:: Sets#sscan_each
- Redis::Commands:: SortedSets#zscan
- Redis::Commands:: SortedSets#zscan_each

において単純な the pattern, the giving pattern と説明されている

redisの公式ドキュメントを確認するとコマンドごとに許容される正規表現も異なるため、正しい表現を利用することは重要なのではないか
Redis::Commands::Keys#keys では [^e], [a-b]が利用できるのに対して、Redis::Commands::Pubsub#psubscribeでは利用できない
redis Command > KEYS: https://redis.io/docs/latest/commands/keys/
redis Commnand > psubscribe: https://redis.io/docs/latest/commands/psubscribe/

上記の考えに同意いただけるのであれば修正したPRを作成したいと考えています

**Comment by FujiokaD** [comment]
機械翻訳

Title: Documentation is not accurate for regular expressions
The description of rdoc in [Redis::Commands::Keys#keys](https://rubydoc.info/gems/redis/Redis%2FCommands%2FKeys:keys) says Find all keys matching the given pattern.  
The regexes allowed by pattern are unclear, so we think it would be easier to understand if we correct them to the regexes allowed by redis.
The part where pattern is used in the explanation is where vscode's character search function is utilized.
Redis::Distributed#keys
Redis::Distributed#psubscribe
Redis::Distributed#punsubscribe
Redis::Commands::Hashes#hscan
Redis::Commands::Hashes#hscan_each
Redis::Commands::Keys#scan
Redis::Commands::Keys#scan_each
Redis::Commands::Keys#keys
Redis::Commands::Pubsub#psubscribe
Redis::Commands::Pubsub#psubscribe_with_timeout
Redis::Commands::Pubsub#punsubscribe
Redis::Commands::Sets#sscan
Redis::Commands:: Sets#sscan_each
Redis::Commands:: SortedSets#zscan
Redis::Commands:: SortedSets#zscan_each
The description "the pattern, the giving pattern" is explained in
If you check the official documentation of redis, you will find that the allowed regular expressions are different for each command, so it would be kind to the user to use the correct expression.
Example:)
Redis::Commands::Keys#keys allows [^e], [a-b] while Redis::Commands::Pubsub#psubscribe does not
redis Command > KEYS: https://redis.io/docs/latest/commands/keys/
redis Commnand > psubscribe: https://redis.io/docs/latest/commands/psubscribe/
I am willing to create a modified PR if you agree with the above idea

Translated with [DeepL.com](https://www.deepl.com/?utm_campaign=product&utm_source=web_translator&utm_medium=web&utm_content=copy_free_translation) (free version)

**Comment by FujiokaD** [comment]
https://github.com/redis/redis-rb/issues/1266
