### ISSUE TITLE
OSS Gate Workshop: techouse: 2024-04-18: Nozomi-Hijikata: NextUI: Work log

### ISSUE THREAD

**Issue by Nozomi-Hijikata** [oss-gate/workshop#1815]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by Nozomi-Hijikata** [comment]
過去にNextUIのバグを修正したPRをあげていたが、8ヶ月くらいauthorからレスポンスがない（他の方からレスポンスはいただいている）
最新バージョンでも既存バグが残っているようだ。
- https://github.com/nextui-org/nextui/pull/1805

**Comment by Nozomi-Hijikata** [comment]
その当時はIssueでコントロールされていなかった気がするが、2024/04/18現在Issue管理をしているようだ。
一旦Issueを立てた
- https://github.com/nextui-org/nextui/issues/2766

**Comment by Nozomi-Hijikata** [comment]
Issueを漁ってみる

**Comment by Nozomi-Hijikata** [comment]
[startup docsが更新されている](https://nextui.org/docs/guide/introduction)っぽいので、改めて順繰りに立ち上げてみる。
その中で気づいたことを残す。

**Comment by Nozomi-Hijikata** [comment]
https://react-spectrum.adobe.com/react-aria/
https://github.com/adobe/react-spectrum
adobeがreact componentのライブラリを公開しているぞ

**Comment by Nozomi-Hijikata** [comment]
内部的に、Framer motionを使ってる
https://www.framer.com/motion/

[CLIツールが登場している](https://nextui.org/docs/guide/cli)

**Comment by Nozomi-Hijikata** [comment]
Framer motionのIntroductionのページでエラーが出た。

<img width="1512" alt="スクリーンショット 2024-04-18 11 58 32" src="https://github.com/oss-gate/workshop/assets/116155762/355d925c-91fc-4a5c-9ac8-a9b2abe0782c">

ログ

``` 
19Third-party cookie will be blocked. Learn more in the Issues tab.
api.framer.com/site/users/me:1 
        
 Failed to load resource: the server responded with a status of 401 ()
client:49 [GSI_LOGGER]: Your client application may not display the Google One Tap in its default position. When FedCM becomes mandatory, One Tap only displays in the default position. Refer to the migration guide to update your code accordingly and opt-in to FedCM to test your changes. Learn more: https://developers.google.com/identity/gsi/web/guides/fedcm-migration?s=dc#layout
_.y @ client:49
client:49 [GSI_LOGGER]: Your client application uses one of the Google One Tap prompt UI status methods that may stop functioning when FedCM becomes mandatory. Refer to the migration guide to update your code accordingly and opt-in to FedCM to test your changes. Learn more: https://developers.google.com/identity/gsi/web/guides/fedcm-migration?s=dc#display_moment and https://developers.google.com/identity/gsi/web/guides/fedcm-migration?s=dc#skipped_moment
_.y @ client:49
examples/:1 Third-party sign in was disabled in browser Site Settings.
api.framer.com/auth/signin:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
api.framer.com/site/users/me:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
client:50 [GSI_LOGGER]: FedCM get() rejects with AbortError: signal is aborted without reason
_.z @ client:50
examples/:1 Third-party sign in was disabled in browser Site Settings.
framework-336caa3f6419768205fe.js:1 TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
at [slug]-eefd1fea1566058c1e89.js:1:14699
at Ii (framework-336caa3f6419768205fe.js:1:105602)
at t.unstable_runWithPriority (framework-336caa3f6419768205fe.js:1:130401)
at Wl (framework-336caa3f6419768205fe.js:1:45773)
at Oi (framework-336caa3f6419768205fe.js:1:105063)
at framework-336caa3f6419768205fe.js:1:104974
at D (framework-336caa3f6419768205fe.js:1:129460)
at w.port1.onmessage (framework-336caa3f6419768205fe.js:1:128182)
uu @ framework-336caa3f6419768205fe.js:1
main-a3d202dbe74dc08b5ac7.js:1 TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
at [slug]-eefd1fea1566058c1e89.js:1:14699
at Ii (framework-336caa3f6419768205fe.js:1:105602)
at t.unstable_runWithPriority (framework-336caa3f6419768205fe.js:1:130401)
at Wl (framework-336caa3f6419768205fe.js:1:45773)
at Oi (framework-336caa3f6419768205fe.js:1:105063)
at framework-336caa3f6419768205fe.js:1:104974
at D (framework-336caa3f6419768205fe.js:1:129460)
at w.port1.onmessage (framework-336caa3f6419768205fe.js:1:128182)
le @ main-a3d202dbe74dc08b5ac7.js:1
main-a3d202dbe74dc08b5ac7.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
le @ main-a3d202dbe74dc08b5ac7.js:1
api.framer.com/auth/signin:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
api.framer.com/site/users/me:1 
  
  
 Failed to load resource: the server responded with a status of 401 ()
client:50 [GSI_LOGGER]: FedCM get() rejects with AbortError: signal is aborted without reason
_.z @ client:50
introduction/:1 Third-party sign in was disabled in browser Site Settings.
client:50 [GSI_LOGGER]: FedCM get() rejects with NetworkError: Error retrieving a token.

```

**Comment by Nozomi-Hijikata** [comment]
Safariでもだめ。
<img width="1327" alt="スクリーンショット 2024-04-18 12 05 03" src="https://github.com/oss-gate/workshop/assets/116155762/ac081ff3-233b-4e3e-b3e4-3bd85fc7afbd">

**Comment by Nozomi-Hijikata** [comment]
Issueを立てた
https://github.com/framer/motion/issues/2628

**Comment by Nozomi-Hijikata** [comment]
https://nextuioss.featurebase.app/roadmap

roadmapを見れるようにしているのか。リッチだ

**Comment by Nozomi-Hijikata** [comment]
初期化のスタートアップを行う
CLIツールができてる
`npm install -g nextui` 


`nextui init my-nextui-app`

**Comment by Nozomi-Hijikata** [comment]
<img width="316" alt="スクリーンショット 2024-04-18 12 30 27" src="https://github.com/oss-gate/workshop/assets/116155762/50653b6b-47f9-44e2-af19-5a4959346415">

かっちょええ

**Comment by Nozomi-Hijikata** [comment]
createしたディレクトリで叩くとエラー
``` bash
 npm run dev

> next-app-template@0.0.1 dev
> next dev

sh: next: command not found
```

**Comment by Nozomi-Hijikata** [comment]
npm updateをトライ中

``` bash
npm WARN ERESOLVE overriding peer dependency

added 470 packages, and audited 471 packages in 29s

138 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by Nozomi-Hijikata** [comment]
``` bash
❯ npm run dev

> next-app-template@0.0.1 dev
> next dev

  ▲ Next.js 14.2.1
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 2.1s
```
worked!

**Comment by Nozomi-Hijikata** [comment]
``` bash
❯ nextui init s-app

NextUI CLI v0.1.5

✔ Select a template › Pages

✔ Template created successfully!

~/environment/oss-workshop
❯ cd s-app

~/environment/oss-workshop/s-app
❯ npm run dev

> next-pages-template@0.1.0 dev
> next dev

sh: next: command not found
```

pages routerでも再現

**Comment by Nozomi-Hijikata** [comment]
`npm update`をするだけだし、bugではないが、
updateをすることが場合によっては必要であることを明記した方がよくないか？

**Comment by Nozomi-Hijikata** [comment]
v1だと bundle時点で除去
> NextUI uses tree-shaking so the unused modules will not be included in the bundle during the build process and each component is exported separately.

v2だと必要なcomponentをaddする形式に変更

**Comment by Nozomi-Hijikata** [comment]
https://nextui.org/docs/guide/upgrade-to-v2

ここにv1とv2の差分がありそう

**Comment by Nozomi-Hijikata** [comment]
`nextui init`コマンドだとほとんどがUNMET
``` bash
❯ npm list --depth=0
npm ERR! code ELSPROBLEMS
npm ERR! missing: @nextui-org/button@^2.0.28, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/code@^2.0.25, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/input@^2.1.18, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/kbd@^2.0.26, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/link@^2.0.27, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/navbar@^2.0.28, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/snippet@^2.0.32, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/switch@^2.0.26, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/system@2.1.0, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/theme@2.2.0, required by next-app-template@0.0.1
npm ERR! missing: @react-aria/ssr@^3.9.2, required by next-app-template@0.0.1
npm ERR! missing: @react-aria/visually-hidden@^3.8.10, required by next-app-template@0.0.1
npm ERR! missing: @types/node@20.5.7, required by next-app-template@0.0.1
npm ERR! missing: @types/react-dom@18.2.7, required by next-app-template@0.0.1
npm ERR! missing: @types/react@18.2.21, required by next-app-template@0.0.1
npm ERR! missing: autoprefixer@10.4.19, required by next-app-template@0.0.1
npm ERR! missing: clsx@^2.0.0, required by next-app-template@0.0.1
npm ERR! missing: eslint-config-next@14.2.1, required by next-app-template@0.0.1
npm ERR! missing: eslint@8.48.0, required by next-app-template@0.0.1
npm ERR! missing: framer-motion@^11.1.1, required by next-app-template@0.0.1
npm ERR! missing: intl-messageformat@^10.5.0, required by next-app-template@0.0.1
npm ERR! missing: next-themes@^0.2.1, required by next-app-template@0.0.1
npm ERR! missing: next@14.2.1, required by next-app-template@0.0.1
npm ERR! missing: postcss@8.4.38, required by next-app-template@0.0.1
npm ERR! missing: react-dom@18.2.0, required by next-app-template@0.0.1
npm ERR! missing: react@18.2.0, required by next-app-template@0.0.1
npm ERR! missing: tailwind-variants@^0.1.20, required by next-app-template@0.0.1
npm ERR! missing: tailwindcss@3.4.3, required by next-app-template@0.0.1
npm ERR! missing: typescript@5.0.4, required by next-app-template@0.0.1
next-app-template@0.0.1 /Users/hijikatanozomi/environment/oss-workshop/new-nextui-app
├── UNMET DEPENDENCY @nextui-org/button@^2.0.28
├── UNMET DEPENDENCY @nextui-org/code@^2.0.25
├── UNMET DEPENDENCY @nextui-org/input@^2.1.18
├── UNMET DEPENDENCY @nextui-org/kbd@^2.0.26
├── UNMET DEPENDENCY @nextui-org/link@^2.0.27
├── UNMET DEPENDENCY @nextui-org/navbar@^2.0.28
├── UNMET DEPENDENCY @nextui-org/snippet@^2.0.32
├── UNMET DEPENDENCY @nextui-org/switch@^2.0.26
├── UNMET DEPENDENCY @nextui-org/system@2.1.0
├── UNMET DEPENDENCY @nextui-org/theme@2.2.0
├── UNMET DEPENDENCY @react-aria/ssr@^3.9.2
├── UNMET DEPENDENCY @react-aria/visually-hidden@^3.8.10
├── UNMET DEPENDENCY @types/node@20.5.7
├── UNMET DEPENDENCY @types/react-dom@18.2.7
├── UNMET DEPENDENCY @types/react@18.2.21
├── UNMET DEPENDENCY autoprefixer@10.4.19
├── UNMET DEPENDENCY clsx@^2.0.0
├── UNMET DEPENDENCY eslint-config-next@14.2.1
├── UNMET DEPENDENCY eslint@8.48.0
├── UNMET DEPENDENCY framer-motion@^11.1.1
├── UNMET DEPENDENCY intl-messageformat@^10.5.0
├── UNMET DEPENDENCY next-themes@^0.2.1
├── UNMET DEPENDENCY next@14.2.1
├── UNMET DEPENDENCY postcss@8.4.38
├── UNMET DEPENDENCY react-dom@18.2.0
├── UNMET DEPENDENCY react@18.2.0
├── UNMET DEPENDENCY tailwind-variants@^0.1.20
├── UNMET DEPENDENCY tailwindcss@3.4.3
└── UNMET DEPENDENCY typescript@5.0.4


npm ERR! A complete log of this run can be found in: /Users/hijikatanozomi/.npm/_logs/2024-04-18T05_23_03_039Z-debug-0.log

~/environment/oss-workshop/new-nextui-app
❯

```

**Comment by Nozomi-Hijikata** [comment]
[next-app-template](https://github.com/nextui-org/next-app-template)で求められているversionを満たしていないのか。
↑はNextUIのtemplateになるパッケージ

**Comment by Nozomi-Hijikata** [comment]
てことは、`npm install`でいいわけか

**Comment by Nozomi-Hijikata** [comment]
``` bash
 npm list --depth=0
next-app-template@0.0.1 /Users/hijikatanozomi/environment/oss-workshop/new-nextui-app
├── @nextui-org/button@2.0.28
├── @nextui-org/code@2.0.25
├── @nextui-org/input@2.1.18
├── @nextui-org/kbd@2.0.26
├── @nextui-org/link@2.0.27
├── @nextui-org/navbar@2.0.28
├── @nextui-org/snippet@2.0.32
├── @nextui-org/switch@2.0.26
├── @nextui-org/system@2.1.0
├── @nextui-org/theme@2.2.0
├── @react-aria/ssr@3.9.2
├── @react-aria/visually-hidden@3.8.10
├── @types/node@20.5.7
├── @types/react-dom@18.2.7
├── @types/react@18.2.21
├── autoprefixer@10.4.19
├── clsx@2.0.0
├── eslint-config-next@14.2.1
├── eslint@8.48.0
├── framer-motion@11.1.1
├── intl-messageformat@10.5.5
├── next-themes@0.2.1
├── next@14.2.1
├── postcss@8.4.38
├── react-dom@18.2.0
├── react@18.2.0
├── tailwind-variants@0.1.20
├── tailwindcss@3.4.3
└── typescript@5.0.4
```

great

**Comment by Nozomi-Hijikata** [comment]
改めてnpm installが入っている方が良い気がする

**Comment by Nozomi-Hijikata** [comment]
PR作ろう

**Comment by Nozomi-Hijikata** [comment]
`.mdx`ってなんだ、

JSX + markdown!!

**Comment by Nozomi-Hijikata** [comment]
https://mdxjs.com/

**Comment by Nozomi-Hijikata** [comment]
PR立てた
- https://github.com/nextui-org/nextui/pull/2769
