### ISSUE TITLE
OSS Gate Workshop: online: 2024-06-08: kuraryu: wheel: Work log

### ISSUE THREAD

**Issue by mochi22** [oss-gate/workshop#1834]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by mochi22** [comment]
軽く使ったことがあるOSS。
https://github.com/PyCQA/flake8
https://github.com/psf/black
https://github.com/pola-rs/polars
https://github.com/PyCQA/isort
https://github.com/plotly/plotly.py

**Comment by mochi22** [comment]
Starsの数やWheelの数が少なめなのでこれで探してみる
https://github.com/pypa/wheel?tab=readme-ov-file

**Comment by mochi22** [comment]
LicenseはMITでOK
https://github.com/pypa/wheel/blob/main/LICENSE.txt
MIT License

**Comment by mochi22** [comment]
QuickStartに従ってやってみる
https://wheel.readthedocs.io/en/stable/quickstart.html

**Comment by mochi22** [comment]
インストールはうまくいった。

> python -m pip install build
Requirement already satisfied: build in c:\users\ryu91\appdata\local\programs\python\python310\lib\site-packages (1.2.1)
Requirement already satisfied: colorama in c:\users\ryu91\appdata\local\programs\python\python310\lib\site-packages (from build) (0.4.6)
Requirement already satisfied: tomli>=1.1.0 in c:\users\ryu91\appdata\local\programs\python\python310\lib\site-packages (from build) (2.0.1)
Requirement already satisfied: pyproject_hooks in c:\users\ryu91\appdata\local\programs\python\python310\lib\site-packages (from build) (1.1.0)
Requirement already satisfied: packaging>=19.1 in c:\users\ryu91\appdata\local\programs\python\python310\lib\site-packages (from build) (24.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by mochi22** [comment]
手順通りにやろうとしたら怒られた。pythonのproject内で実行しないとエラーになるようだ。

> python -m build --wheel
* Creating isolated environment: venv+pip...
ERROR Source C:\Users\ryu91\webapp\go-clean does not appear to be a Python project: no pyproject.toml or setup.py

**Comment by mochi22** [comment]
現在気になった点
- QuickStartの手順が簡素すぎる気がした。
- 新規でPython project環境で実行する必要があり、その辺の記載がない。
- エラーメッセージからpyproject.toml or setup.pyが必要だが、その記載がない

**Comment by mochi22** [comment]
下記内容で setup.pyファイルを作成。
```
from setuptools import setup, find_packages

setup(
    name="wheel_test",
    version="0.0.1",
    packages=find_packages(),
)
```

**Comment by mochi22** [comment]
以下実行すると、以下のディレクトリやwhlファイルが作成された。
build\bdist.win-amd64
dist\wheel_test-0.0.1-py3-none-any.whl
wheel_test.egg-info\dependency_links.txt
wheel_test.egg-info\PKG-INFO
wheel_test.egg-info\SOURCES.txt
wheel_test.egg-info\top_level.txt

> python -m build --wheel
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools >= 40.8.0
* Getting build dependencies for wheel...
running egg_info
creating wheel_test.egg-info
writing wheel_test.egg-info\PKG-INFO
writing dependency_links to wheel_test.egg-info\dependency_links.txt
writing top-level names to wheel_test.egg-info\top_level.txt
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
reading manifest file 'wheel_test.egg-info\SOURCES.txt'
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
* Installing packages in isolated environment:
  - wheel
* Building wheel...
running bdist_wheel
running build
installing to build\bdist.win-amd64\wheel
running install
running install_egg_info
running egg_info
writing wheel_test.egg-info\PKG-INFO
writing dependency_links to wheel_test.egg-info\dependency_links.txt
writing top-level names to wheel_test.egg-info\top_level.txt
reading manifest file 'wheel_test.egg-info\SOURCES.txt'
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
Copying wheel_test.egg-info to build\bdist.win-amd64\wheel\.\wheel_test-0.0.1-py3.10.egg-info
running install_scripts
creating build\bdist.win-amd64\wheel\wheel_test-0.0.1.dist-info\WHEEL
creating 'C:\Users\ryu91\kaggle\kaggle\sandbox\dist\.tmp-dert7q1t\wheel_test-0.0.1-py3-none-any.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'wheel_test-0.0.1.dist-info/METADATA'
adding 'wheel_test-0.0.1.dist-info/WHEEL'
adding 'wheel_test-0.0.1.dist-info/top_level.txt'
adding 'wheel_test-0.0.1.dist-info/RECORD'
removing build\bdist.win-amd64\wheel
Successfully built wheel_test-0.0.1-py3-none-any.whl

**Comment by mochi22** [comment]
下記コマンドで先ほど作成された.whlファイルをインストールした。

> pip install .\dist\wheel_test-0.0.1-py3-none-any.whl
Processing c:\users\ryu91\kaggle\kaggle\sandbox\dist\wheel_test-0.0.1-py3-none-any.whl
Installing collected packages: wheel-test
Successfully installed wheel-test-0.0.1

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by mochi22** [comment]
実際にインストールされたことが確認できた。
> pip list
```
wheel_test                   0.0.1
```

**Comment by mochi22** [comment]
現状気になってる点

- QuickStartの手順が簡素すぎる気がした。
- pyproject.toml or setup.pyが必要だが、その記載がない

**Comment by otegami** [comment]
決めた Project 名の更新ナイスです！

**Comment by otegami** [comment]
memo: サンプルプロジェクトの作成は、GitHub Actions を参考にすると良さそうかもです。
- https://github.com/pypa/wheel/blob/1e00742acc9fb33f6e71460c3844c2b66532af7f/.github/workflows/publish.yml#L21-L24

**Comment by mochi22** [comment]
Github Actionにあるflitを使うとsetup.pyなどが作れそうなので試してみる。
https://github.com/pypa/flit

**Comment by mochi22** [comment]
venvを使用して、試したログ
```
PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m venv .venv    
PS C:\Users\ryu91\kaggle\kaggle\sandbox> .\.venv\Scripts\activate
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip list
Package    Version
---------- -------
pip        22.2.2
setuptools 63.2.0

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip -V
pip 22.2.2 from C:\Users\ryu91\kaggle\kaggle\sandbox\.venv\lib\site-packages\pip (python 3.10)
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -V
Python 3.10.8
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m pip install build
Collecting build
  Using cached build-1.2.1-py3-none-any.whl (21 kB)
Collecting pyproject_hooks
  Using cached pyproject_hooks-1.1.0-py3-none-any.whl (9.2 kB)
Collecting tomli>=1.1.0
  Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting packaging>=19.1
  Using cached packaging-24.0-py3-none-any.whl (53 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: tomli, pyproject_hooks, packaging, colorama, build
Successfully installed build-1.2.1 colorama-0.4.6 packaging-24.0 pyproject_hooks-1.1.0 tomli-2.0.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip list
Package         Version
--------------- -------
build           1.2.1
colorama        0.4.6
packaging       24.0
pip             22.2.2
pyproject_hooks 1.1.0
setuptools      63.2.0
tomli           2.0.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m build --wheel
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools >= 40.8.0
* Getting build dependencies for wheel...
running egg_info
creating wheel_test.egg-info
writing wheel_test.egg-info\PKG-INFO
writing dependency_links to wheel_test.egg-info\dependency_links.txt
writing top-level names to wheel_test.egg-info\top_level.txt
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
reading manifest file 'wheel_test.egg-info\SOURCES.txt'
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
* Installing packages in isolated environment:
  - wheel
* Building wheel...
running bdist_wheel
running build
installing to build\bdist.win-amd64\wheel
running install
running install_egg_info
running egg_info
writing wheel_test.egg-info\PKG-INFO
writing dependency_links to wheel_test.egg-info\dependency_links.txt
writing top-level names to wheel_test.egg-info\top_level.txt
reading manifest file 'wheel_test.egg-info\SOURCES.txt'
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
Copying wheel_test.egg-info to build\bdist.win-amd64\wheel\.\wheel_test-0.0.1-py3.10.egg-info
running install_scripts
creating build\bdist.win-amd64\wheel\wheel_test-0.0.1.dist-info\WHEEL
creating 'C:\Users\ryu91\kaggle\kaggle\sandbox\dist\.tmp-hj8gl2nr\wheel_test-0.0.1-py3-none-any.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'wheel_test-0.0.1.dist-info/METADATA'
adding 'wheel_test-0.0.1.dist-info/WHEEL'
adding 'wheel_test-0.0.1.dist-info/top_level.txt'
adding 'wheel_test-0.0.1.dist-info/RECORD'
removing build\bdist.win-amd64\wheel
Successfully built wheel_test-0.0.1-py3-none-any.whl
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip list
Package         Version
--------------- -------
build           1.2.1
colorama        0.4.6
packaging       24.0
pip             22.2.2
pyproject_hooks 1.1.0
setuptools      63.2.0
tomli           2.0.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip install dist\wheel_test-0.0.1-py3-none-any.whl
Processing c:\users\ryu91\kaggle\kaggle\sandbox\dist\wheel_test-0.0.1-py3-none-any.whl
Installing collected packages: wheel-test
Successfully installed wheel-test-0.0.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip list
Package         Version
--------------- -------
build           1.2.1
colorama        0.4.6
packaging       24.0
pip             22.2.2
pyproject_hooks 1.1.0
setuptools      63.2.0
tomli           2.0.1
wheel_test      0.0.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by mochi22** [comment]
venv環境で```python -m pip install build```でインストールした直後の環境。

- Python 3.10.8
- OS: Windows
エディション	Windows 11 Home
バージョン	23H2


- packages
```
Package         Version
--------------- -------
build           1.2.1
colorama        0.4.6
packaging       24.0
pip             22.2.2
pyproject_hooks 1.1.0
setuptools      63.2.0
tomli           2.0.1
```

**Comment by mochi22** [comment]
まず、仮想環境作ってから以下の資料に沿ってインストールする。
https://github.com/pypa/flit

具体的には、下記コマンド実行した。
```
PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m venv .venv
PS C:\Users\ryu91\kaggle\kaggle\sandbox> .\.venv\Scripts\activate
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python3 -m pip install flit
Python 
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip list                   
Package    Version
---------- -------
pip        22.2.2
setuptools 63.2.0

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m pip install flit 
Collecting flit
  Downloading flit-3.9.0-py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.9/49.9 kB 2.5 MB/s eta 0:00:00
Collecting flit_core>=3.9.0
  Downloading flit_core-3.9.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB ? eta 0:00:00
Collecting tomli-w
  Downloading tomli_w-1.0.0-py3-none-any.whl (6.0 kB)
Collecting requests
  Downloading requests-2.32.3-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 3.4 MB/s eta 0:00:00
Collecting docutils
  Downloading docutils-0.21.2-py3-none-any.whl (587 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.4/587.4 kB 18.6 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.6.2-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.4/164.4 kB 10.3 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.3/100.3 kB 6.0 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.7-py3-none-any.whl (66 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB ? eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Installing collected packages: urllib3, tomli-w, idna, flit_core, docutils, charset-normalizer, certifi, requests, flit
Successfully installed certifi-2024.6.2 charset-normalizer-3.3.2 docutils-0.21.2 flit-3.9.0 flit_core-3.9.0 idna-3.7 requests-2.32.3 tomli-w-1.0.0 urllib3-2.2.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip list
Package            Version
------------------ --------
certifi            2024.6.2
charset-normalizer 3.3.2
docutils           0.21.2
flit               3.9.0
flit_core          3.9.0
idna               3.7
pip                22.2.2
requests           2.32.3
setuptools         63.2.0
tomli_w            1.0.0
urllib3            2.2.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
```

**Comment by mochi22** [comment]
次に、以下のファイルを作成する。
```test_flit_module.py
"""An amazing sample package!"""

__version__ = "0.1"
```

**Comment by mochi22** [comment]
flit init を実行して、pyproject.tomlを作成する。
このとき、Module name と一致するファイルが後程必要になる。
```
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> flit init
Module name: test_flit_module
Author: kuraryu
Author email:
Home page:
Choose a license (see http://choosealicense.com/ for more info)
1. MIT - simple and permissive
2. Apache - explicitly grants patent rights
3. GPL - ensures that code based on this is shared with the same terms
4. Skip - choose a license later
Enter 1-4: 4

Written pyproject.toml; edit that file to add optional extra info.
````


pyproject.toml
````
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "test_flit_module"
authors = [{name = "kuraryu"}]
dynamic = ["version", "description"]

```

**Comment by mochi22** [comment]
python -m pip install buildコマンドでwheelをインストールする。

その後、python -m build --wheel実行時に、Module name と一致するファイルがないと、下記エラーになる
````
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m build --wheel
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - flit_core >=3.2,<4
* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "C:\Users\ryu91\kaggle\kaggle\sandbox\.venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
    main()
  File "C:\Users\ryu91\kaggle\kaggle\sandbox\.venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
  File "C:\Users\ryu91\kaggle\kaggle\sandbox\.venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 134, in get_requires_for_build_wheel
    return hook(config_settings)
  File "C:\Users\ryu91\AppData\Local\Temp\build-env-q483hbn5\lib\site-packages\flit_core\buildapi.py", line 31, in get_requires_for_build_wheel
    module = Module(info.module, Path.cwd())
  File "C:\Users\ryu91\AppData\Local\Temp\build-env-q483hbn5\lib\site-packages\flit_core\common.py", line 59, in __init__
    raise ValueError("No file/folder found for module {}".format(name))
ValueError: No file/folder found for module test_flit_module

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by mochi22** [comment]
Module name と一致するファイルがあれば、下記のように成功する。
```
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m build --wheel
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - flit_core >=3.2,<4
* Getting build dependencies for wheel...
* Building wheel...
Successfully built test_flit_module-0.1-py2.py3-none-any.whl
```

**Comment by mochi22** [comment]
.whlファイルをpip install できた。
```
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip install dist\test_flit_module-0.1-py2.py3-none-any.whl
Processing c:\users\ryu91\kaggle\kaggle\sandbox\dist\test_flit_module-0.1-py2.py3-none-any.whl
Installing collected packages: test-flit-module
Successfully installed test-flit-module-0.1

[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> pip list
Package            Version
------------------ --------
build              1.2.1
certifi            2024.6.2
charset-normalizer 3.3.2
colorama           0.4.6
docutils           0.21.2
flit               3.9.0
flit_core          3.9.0
idna               3.7
packaging          24.0
pip                22.2.2
pyproject_hooks    1.1.0
requests           2.32.3
setuptools         63.2.0
test_flit_module   0.1
tomli              2.0.1
tomli_w            1.0.0
urllib3            2.2.1
```

**Comment by mochi22** [comment]
以下のように find_packagesなくても動作した。
```
from setuptools import setup, find_packages

setup(
    name="wheel_test",
    version="0.0.1",
    # packages=find_packages(),
)
```

```
(.venv) PS C:\Users\ryu91\kaggle\kaggle\sandbox> python -m build --wheel                     
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools >= 40.8.0
* Getting build dependencies for wheel...
running egg_info
creating wheel_test.egg-info
writing wheel_test.egg-info\PKG-INFO
writing dependency_links to wheel_test.egg-info\dependency_links.txt
writing top-level names to wheel_test.egg-info\top_level.txt
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
reading manifest file 'wheel_test.egg-info\SOURCES.txt'
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
* Installing packages in isolated environment:
  - wheel
* Building wheel...
running bdist_wheel
running build
running build_py
creating build
creating build\lib
copying test_flit_module.py -> build\lib
installing to build\bdist.win-amd64\wheel
running install
running install_lib
creating build\bdist.win-amd64
creating build\bdist.win-amd64\wheel
copying build\lib\test_flit_module.py -> build\bdist.win-amd64\wheel\.
running install_egg_info
running egg_info
writing wheel_test.egg-info\PKG-INFO
writing dependency_links to wheel_test.egg-info\dependency_links.txt
writing top-level names to wheel_test.egg-info\top_level.txt
reading manifest file 'wheel_test.egg-info\SOURCES.txt'
writing manifest file 'wheel_test.egg-info\SOURCES.txt'
Copying wheel_test.egg-info to build\bdist.win-amd64\wheel\.\wheel_test-0.0.1-py3.10.egg-info
running install_scripts
creating build\bdist.win-amd64\wheel\wheel_test-0.0.1.dist-info\WHEEL
creating 'C:\Users\ryu91\kaggle\kaggle\sandbox\dist\.tmp-pg0p5uv8\wheel_test-0.0.1-py3-none-any.whl' and adding 'build\bdist.win-amd64\wheel' to it
adding 'test_flit_module.py'
adding 'wheel_test-0.0.1.dist-info/METADATA'
adding 'wheel_test-0.0.1.dist-info/WHEEL'
adding 'wheel_test-0.0.1.dist-info/top_level.txt'
adding 'wheel_test-0.0.1.dist-info/RECORD'
removing build\bdist.win-amd64\wheel
Successfully built wheel_test-0.0.1-py3-none-any.whl
```

**Comment by mochi22** [comment]
- pyproject.toml と setup.py が両方あるときに、どちらが優先されるのかなどの記載がない。(動作的にはpyproject.tomlが優先されそう)
- QuickStartの記載が少ない。setup.pyの例とかほしいかも

**Comment by mochi22** [comment]
## これからの方向
QuickStartの記載が少なくて、setup.pyなどの具体例があった方がうれしいといったフィードバックを行う

**Comment by otegami** [comment]
セクションの書き方。
- https://github.com/groonga/groonga/pull/1754#issuecomment-2041881014

**Comment by mochi22** [comment]
特にContribute.mdなどはない。
以下の記載より、きちんと説明すれば形式は問わなそう。
https://wheel.readthedocs.io/en/stable/development.html#pull-requests
Getting Involved
The wheel project welcomes help in the following ways:

Making Pull Requests for code, tests, or docs.

Commenting on open issues and pull requests.

Helping to answer questions on the [mailing list](https://mail.python.org/mailman/listinfo/distutils-sig).

**Comment by mochi22** [comment]
大枠は以下でよさそう。

1. 問題の概要
QuickStartだとうまくいかない

2. 再現方法


3. 期待する結果
QuickStart みただけでうまく動作してほしい

4. 原因の説明
setup.py とかについて記載がなくエラーになった。
setup.py の書き方とか知らないので、検索する必要があった。

5. 解決方法
QuickStart のdoc改善する

**Comment by mochi22** [comment]
一つずつきちんと書いていく。

**Comment by mochi22** [comment]
1. 問題の概要
QuickStart の手順では必要なファイルについて記載がなく、エラーになった。

```
(.venv) PS C:\Users\ryu91\sandbox> python -m build --wheel
* Creating isolated environment: venv+pip...
ERROR Source C:\Users\ryu91\sandbox does not appear to be a Python project: no pyproject.toml or setup.py
```

**Comment by otegami** [comment]
```console
% mkdir sandbox && cd sandbox
% python -m ..
```

**Comment by mochi22** [comment]
2. 再現方法

以下の環境で試したところ、エラーになった。
```
Python 3.10.8

OS: Windows
エディション Windows 11 Home
バージョン 23H2
```


再現手順は下記コマンド実行。
1. 事前準備で仮想環境を立てた
``` console
> mkdir sandbox
> cd sandbox
> python -m venv .venv    
> .\.venv\Scripts\activate            
```

2. ここからは、QuickStart 通りに実行
https://wheel.readthedocs.io/en/stable/quickstart.html
``` console
> python -m pip install build
> python -m build --wheel
```

**Comment by mochi22** [comment]
3. 実際の結果

下記エラーが発生した。

```
> python -m build --wheel
* Creating isolated environment: venv+pip...
ERROR Source C:\Users\ryu91\sandbox does not appear to be a Python project: no pyproject.toml or setup.py
```

### 期待する結果
エラーが発生せずにpython -m build --wheelコマンドを実行できる

**Comment by mochi22** [comment]
4. 原因の説明

setup.py や pyproject.toml が必要なことがドキュメントに記載がなくエラーになった。

**Comment by mochi22** [comment]
5. 解決方法

解決方法としては、QuickStart にsetup.py や pyproject.toml が必要なことや具体的な例を記載する。

**Comment by mochi22** [comment]
6. 改善方法

QuickStart にsetup.py や pyproject.toml が必要なことや具体的な例を記載する。

例としては、以下のような setup.py を記載する。
```
from setuptools import setup

setup(
    name="wheel_test",
    version="0.0.1",
)
```

**Comment by mochi22** [comment]
### まとめ

1. 問題の概要
QuickStart の手順では必要なファイルについて記載がなく、エラーになった。
```
(.venv) PS C:\Users\ryu91\sandbox> python -m build --wheel
* Creating isolated environment: venv+pip...
ERROR Source C:\Users\ryu91\sandbox does not appear to be a Python project: no pyproject.toml or setup.py
```

2. 再現方法
以下の環境で試したところ、エラーになった。
```
Python 3.10.8

OS: Windows
エディション Windows 11 Home
バージョン 23H2
```

再現手順は下記コマンド実行。

事前準備で仮想環境を立てた
```
> mkdir sandbox
> cd sandbox
> python -m venv .venv    
> .\.venv\Scripts\activate            
```
ここからは、QuickStart 通りに実行
https://wheel.readthedocs.io/en/stable/quickstart.html
```
> python -m pip install build
> python -m build --wheel
```

3. 実際の結果
下記エラーが発生した。
```
> python -m build --wheel
* Creating isolated environment: venv+pip...
ERROR Source C:\Users\ryu91\sandbox does not appear to be a Python project: no pyproject.toml or setup.py
```
4. 期待する結果
エラーが発生せずにpython -m build --wheelコマンドを実行できる


5. 原因の説明
setup.py や pyproject.toml が必要なことがドキュメントに記載がなくエラーになった。

6. 解決方法
実行環境の配下に setup.py や pyproject.toml を作成する。

7. 改善方法
QuickStart にsetup.py や pyproject.toml が必要なことや具体的な例を記載する。

改善例としては、To build a wheel for your project:の前に以下のような setup.py などを作成しておくことを記載する。
```
from setuptools import setup

setup(
    name="wheel_test",
    version="0.0.1",
)
```

**Comment by daipom** [comment]
Python公式のtomlの説明

https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#writing-pyproject-toml

**Comment by mochi22** [comment]
### enversion

## Overview
When I followed the Quicstart instructions, I got the following error:
```
(.venv) PS C:\Users\ryu91\sandbox> python -m build --wheel
* Creating isolated environment: venv+pip...
ERROR Source C:\Users\ryu91\sandbox does not appear to be a Python project: no pyproject.toml or setup.py
```

## How to reproduce
- my environment
```
Python 3.10.8

OS: Windows
Edition Windows 11 Home
Version 23H2
```

- run the following command:

1. set up a virtual environment
```
> mkdir sandbox
> cd sandbox
> python -m venv .venv    
> .\.venv\Scripts\activate            
```

2. follow the [QuickStart instructions](https://wheel.readthedocs.io/en/stable/quickstart.html)
```
> python -m pip install build
> python -m build --wheel
```

## Actual Result
The following error occurred.
```
> python -m build --wheel
* Creating isolated environment: venv+pip...
ERROR Source C:\Users\ryu91\sandbox does not appear to be a Python project: no pyproject.toml or setup.py
```
## Expected Result
We are able to run the `python -m build --wheel` command without any errors.


## Cause
This error occurred because setup.py or pyproject.toml did not exist.

## Solution
Create setup.py and pyproject.toml under the execution environment.

## Suggestion
Specific examples of setup.py or pyproject.toml are provided in QuickStart.
"To build a wheel for your project" alone doesn't tell you the minimum requirements for a beginner.

なので、下記のように記載するのはいかがでしょうか。




If you don't have a project, create a setup.py file like this:
1. touch setup.py
2. run following command
```
cat <<EOF > setup.py
from setuptools import setup

setup(
    name="wheel_test",
    version="0.0.1",
)
EOF
```
