### ISSUE TITLE
OSS Gateワークショップ2016-03-26: ngram: Rroonga: 作業ログ

### ISSUE THREAD

**Issue by ngram** [oss-gate/workshop#19]
作業ログは、参加者が、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * 参加者は作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * 参加者が困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
  * 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by ngram** [comment]
認証Proxy環境下でインストールに失敗するので、それを修正するのが目標です。

**Comment by ngram** [comment]
* 作業：インストールを開始
* 思っていること：認証Proxyなしでインストールしてみる

* 備考：下記環境で作業中
  * Windows8.1 (64bit)

下記のREADMEを読んでインストール作業
https://github.com/ranguba/rroonga

**Comment by ngram** [comment]
* 作業：インストールに失敗
* 思っていること：Devkitが未インストールだった。以下エラーメッセージ。

```
Fetching: rroonga-6.0.0.gem (100%)
ERROR:  Error installing rroonga:
        The 'rroonga' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

C:\Users\ngram>ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
```

**Comment by ngram** [comment]
* 作業：DevKitをインストール
* 思っていること：DevKitをダウンロードしてインストールする。

* 備考：マニュアルは下記を参照。
https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

バイナリは以下のものを利用
DevKit-mingw64-64-4.7.2-20130224-1432-sfx

**Comment by ngram** [comment]
* 作業：もう一度インストールしたが失敗
* 思っていること：x86_64版のDevKitを利用したためかも？

* 備考：以下にログを記載。

```
C:\bin\Ruby21-DevKit>ruby dk.rb init
[INFO] found RubyInstaller v2.1.5 at C:/bin/Ruby21

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.

C:\bin\Ruby21-DevKit>ruby dk.rb install
[INFO] Updating convenience notice gem override for 'C:/bin/Ruby21'
[INFO] Installing 'C:/bin/Ruby21/lib/ruby/site_ruby/devkit.rb'
```

```
C:\bin\Ruby21-DevKit>gem install rroonga
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing rroonga:
        ERROR: Failed to build gem native extension.

    C:/bin/Ruby21/bin/ruby.exe extconf.rb
checking for GCC... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/bin/Ruby21/bin/ruby
C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to gen
erate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:571:in `block in try_compile'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:524:in `with_werror'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:571:in `try_compile'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:811:in `macro_defined?'
        from extconf.rb:39:in `block in <main>'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'

        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in po
stpone'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:321:in `open'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
        from C:/bin/Ruby21/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
        from extconf.rb:38:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/bin/Ruby21/lib/ruby/gems/2.1.0/gems/rroong
a-6.0.0 for inspection.
Results logged to C:/bin/Ruby21/lib/ruby/gems/2.1.0/extensions/x86-mingw32/2.1.0
/rroonga-6.0.0/gem_make.out
```

**Comment by ngram** [comment]
* 作業：DevKit(32bit版)をインストール
* 思っていること：32bit版バイナリをダウンロードしてきてインストール

* 備考：下記ファイルを利用
  * DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe

**Comment by ngram** [comment]
* 作業：Devkit(32bit版)インストールに失敗
* 思っていること：64bit版のインストール情報を削除しないといけない雰囲気

* 備考：ログ
```
C:\bin\Ruby21-Devkit32>ruby dk.rb init
[INFO] found RubyInstaller v2.1.5 at C:/bin/Ruby21

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.

C:\bin\Ruby21-Devkit32>ruby dk.rb install
[INFO] Skipping existing gem override for 'C:/bin/Ruby21'
[WARN] Skipping existing DevKit helper library for 'C:/bin/Ruby21'
```

**Comment by ngram** [comment]
* 作業：Devkit(64bit版)の情報を削除
* 思っていること：手作業で削除が必要な模様

* 備考：下記を参照
  * http://xusuprogram.blog.fc2.com/blog-entry-28.html
  * C:\bin\Ruby21\lib\ruby\site_ruby\devkit.rb を削除

**Comment by ngram** [comment]
* 作業：DevKit(32bit版)の再インストール
* 思っていること：出来たような雰囲気

* 備考：ログ

```
C:\bin\Ruby21-Devkit32>ruby dk.rb init
[INFO] found RubyInstaller v2.1.5 at C:/bin/Ruby21

Initialization complete! Please review and modify the auto-generated
'config.yml' file to ensure it contains the root directories to all
of the installed Rubies you want enhanced by the DevKit.

C:\bin\Ruby21-Devkit32>ruby dk.rb install
[INFO] Skipping existing gem override for 'C:/bin/Ruby21'
[INFO] Installing 'C:/bin/Ruby21/lib/ruby/site_ruby/devkit.rb'
```

**Comment by ngram** [comment]
* 作業：インストール成功
* 思っていること：rroongaが使える環境になった

* 備考：ログ
```
C:\bin\Ruby21-Devkit32>gem install rroonga
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed rroonga-6.0.0
Parsing documentation for rroonga-6.0.0
Installing ri documentation for rroonga-6.0.0
Done installing documentation for rroonga after 9 seconds
1 gem installed
```

**Comment by ngram** [comment]
* 作業：Rrroongaの動作確認
* 思っていること：インストールしたものが動作するかチュートリアルで確認

* 備考：下記のURLを参照中
  * http://ranguba.org/rroonga/ja/file.tutorial.html

**Comment by kou** [comment]
あれ！？ `gem install rroonga` とするとバイナリーがインストールできるはずなんですけど。。。！

**Comment by ngram** [comment]
> あれ！？ gem install rroonga とするとバイナリーがインストールできるはずなんですけど。。。！

Windowsで認証Proxyを通じてインストールする場合に、うまくいかないはずです。
これから実際にWindows上で再現できる環境を作成します。

**Comment by kou** [comment]
なるほど！

**Comment by ngram** [comment]
作業：Rrroongaの動作確認完了
思っていること：チュートリアルが動作可能なことを確認

備考：ログ

```ruby
irb(main):001:0> require 'groonga'
=> true
irb(main):002:0> Groonga::Database.create(:path => "./test.db")
=> #<Groonga::Database id: <nil>, name: (anonymous), path: <./test.db>, domain:(nil), range: (nil), flags: <>>
irb(main):003:0> Groonga::Schema.create_table("Items", :type => :hash)
=> [#<Groonga::Schema::TableDefinition:0x279d080 @name="Items", @definitions=[], @options={:context=>#<Groonga::Context encoding: <:utf8>, database: <#<Groonga::Database id: <nil>, name: (anonymous), path: <./test.db>, domain: (nil), range: (nil), flags: <>>>>, :type=>:hash}, @table_type=Groonga::Hash>]
irb(main):004:0> items = Groonga["Items"]
=> #<Groonga::Hash id: <256>, name: <Items>, path: <./test.db.0000100>, domain:<ShortText>, range: (nil), flags: <>, size: <0>, encoding: <:utf8>, default_tokenizer: (nil), token_filters: [], normalizer: (nil)>
irb(main):005:0> items.size
=> 0
irb(main):006:0> items.add("http://en.wikipedia.org/wiki/Ruby")
=> #<Groonga::Record:0x28263c0 @table=#<Groonga::Hash id: <256>, name: <Items>,path: <./test.db.0000100>, domain: <ShortText>, range: (nil), flags: <>, size: <1>, encoding: <:utf8>, default_tokenizer: (nil), token_filters: [], normalizer:(nil)>, @id=1, @added=true, attributes: {"_id"=>1, "_key"=>"http://en.wikipedia.org/wiki/Ruby"}>
irb(main):007:0> items.size
=> 1
irb(main):008:0>
```

**Comment by ngram** [comment]
* 作業：Rroongaのアインストール
* 思っていること：gemを削除する

* 備考：ログ
```
C:\bin\Ruby21-Devkit32>gem uninstall rroonga
Remove executables:
        groonga-database-inspect, grndump, grntest-log-analyze, groonga-index-du
mp

in addition to the gem? [Yn]  n
Executables and scripts will remain installed.
Successfully uninstalled rroonga-6.0.0
```
groongaのフォルダが以下に残っていたので念のため削除
```
C:\bin\Ruby21\lib\ruby\gems\2.1.0\gems
```

**Comment by ngram** [comment]
* 作業：WEBrickで認証Proxyを作成
* 思っていること：再現環境を作成

**Comment by ngram** [comment]
* 作業：認証Proxyでの不具合再現を確認
* 思っていること：認証あり・なしの場合でインストール可否が変わるはずなのでテストする

* 備考：ログ
```
C:\Users\ngram>gem install rroonga --verbose
...
 97% [143/146]  lib/groonga/statistic-measurer.rb
 98% [144/146]  lib/groonga/sub-records.rb
 99% [145/146]  lib/groonga/table.rb
100% [146/146]  lib/rroonga.rb

Installing ri documentation for rroonga-6.0.0
Done installing documentation for rroonga after 10 seconds
1 gem installed
```

**Comment by ngram** [comment]
* 作業：不具合を修正するコードを作成する
* 思っていること：不具合修正後、gemを作成してローカルインストールで動作確認

* 備考：必要なgem
  * yard, rake-compiler, packnga

* gem作成手順
  * ranguba/rroongaをforkしてclone
  * % gem build rroonga.gemspec

**Comment by tSU-RooT** [comment]
PRまでは行かないようなので、とりあえずIssueを立てることに。

**Comment by ngram** [comment]
* 作業：Issueを立ててPullRequestを行う
* 思っていること：GitHubでの作業の流れを確認する

* 備考：結果
https://github.com/ranguba/rroonga/pull/129

**Comment by kou** [comment]
おつかれさまでした！参加した感想をブログとかにまとめてくれるとOSS Gateワークショップの普及につながってうれしいです！
（次回からはフィードバックしたメンターの人にその場でcloseしてもらうようにしよう。おつかれ！とか言いながら。）
