### ISSUE TITLE
OSS Gate Workshop: tokyo: 2024-12-14: daipom: RR: Work log

### ISSUE THREAD

**Issue by daipom** [oss-gate/workshop#1900]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by daipom** [comment]
今日やるOSS全然思い付いてません！

**Comment by daipom** [comment]
OSS何にしよう。最近触っているのは....

**Comment by daipom** [comment]
最近Rubyのテストフレームワークで気になることがあったので、それを題材にしてみたい

**Comment by daipom** [comment]
https://github.com/rr/rr

このRRというライブラリーを最近よく使っていて、気になる動きがありました。

**Comment by daipom** [comment]
https://github.com/rr/rr/blob/master/README.md#license

> RR is available under the [MIT license](https://github.com/rr/rr/blob/master/LICENSE).

https://github.com/rr/rr/blob/master/LICENSE

この辺りを見るにMITラインセス。

これは https://opensource.org/license/mit なので、
オープンソースです。

**Comment by daipom** [comment]
今日はRRを見てみます

**Comment by daipom** [comment]
まずはREADMEを読む

https://github.com/rr/rr/blob/master/README.md

**Comment by daipom** [comment]
このあたりのドキュメントも見ながら動かしてみます

https://github.com/rr/rr/blob/master/README.md#learning-more

**Comment by daipom** [comment]
`dont_allow`が次のように動きます

```rb
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class TestObject
  def foo
    p "foo"
  end

  def bar
    p "bar"
  end
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    testObj = TestObject.new
    dont_allow(testObj).foo

    testObj.bar
  end
end
```

**Comment by daipom** [comment]
```
ruby .\test2.rb
Loaded suite ./test2
Started
"bar"
Finished in 0.0018346 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------1 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------545.08 tests/s, 0.00 assertions/s
```

**Comment by daipom** [comment]
`foo`を呼ぶようにするとちゃんとテストが落ちる

```rb
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class TestObject
  def foo
    p "foo"
  end

  def bar
    p "bar"
  end
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    testObj = TestObject.new
    dont_allow(testObj).foo

    testObj.foo
  end
end
```

```
 ruby .\test2.rb
Loaded suite ./test2
Started
F
==============================================================================================================================================================================================================================================Failure: test_a(SampleTest):
  Called 1 time.
  Expected 0 times.
./test2.rb:24:in `test_a'
     21:     testObj = TestObject.new
     22:     dont_allow(testObj).foo
     23:
  => 24:     testObj.foo
     25:   end
     26: end
==============================================================================================================================================================================================================================================Finished in 0.0067466 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------1 tests, 0 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------148.22 tests/s, 0.00 assertions/s
```

**Comment by daipom** [comment]
なぜか次のテストが失敗する、意味不明

```rb
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class TestObject
  def foo
    p "foo"
  end

  def bar
    p "bar"
  end
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    testObj = TestObject.new
    dont_allow(testObj).foo

    testObj.bar
  end

  def test_b
    ObjectSpace.each_object do |obj|
      obj.class
    end
  end
end
```

**Comment by daipom** [comment]
```
 ruby .\test2.rb
Loaded suite ./test2
Started
"bar"
F
==============================================================================================================================================================================================================================================Failure: test_b(SampleTest):
  Called 1 time.
  Expected 0 times.
./test2.rb:29:in `block in test_b'
     26:
     27:   def test_b
     28:     ObjectSpace.each_object do |obj|
  => 29:       obj.class
     30:     end
     31:   end
     32: end
./test2.rb:28:in `each_object'
./test2.rb:28:in `test_b'
==============================================================================================================================================================================================================================================Finished in 0.0116508 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------2 tests, 0 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------171.66 tests/s, 0.00 assertions/s
```

**Comment by daipom** [comment]
これを報告したい。

このライブラリーの機能を使うことで、関係ない他のテストが失敗するようになるのはおかしいはず。

**Comment by daipom** [comment]
既存のissueにはdont_allowのものはない。

https://github.com/rr/rr/issues?q=is%3Aissue+dont_allow+is%3Aclosed

**Comment by daipom** [comment]
https://github.com/rr/rr/issues/102
