### ISSUE TITLE
OSS Gateワークショップ2016-03-26: koichiro: focuslight: 作業ログ

### ISSUE THREAD

**Issue by koichiro** [oss-gate/workshop#25]
作業ログは、参加者が、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * 参加者は作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いて参加者にフィードバックをする。

メンターは次のようなフィードバックをします。これは、参加者とは違う視点から参加者の行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * 参加者が気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * 参加者が困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をして参加者が整理できていない行動や考えを整理してくれます。
  * 参加者が「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * 参加者が次にどの方向に進めばよいかを整理してくれます。

このように、参加者の作業をメンター視点で一緒に整理し、参加者の今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「参加者にとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、参加者が重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by koichiro** [comment]
環境構築からスタート
https://github.com/focuslight/focuslight

**Comment by koichiro** [comment]
rubyインストール
```
koichiro@falshion ~/tmp % rbenv install 2.3.0
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...
Installed ruby-2.3.0 to /Users/koichiro/.rbenv/versions/2.3.0
```

**Comment by koichiro** [comment]
bundler
```
koichiro@falshion ~/tmp % gem install bundler
Fetching: bundler-1.11.2.gem (100%)
Successfully installed bundler-1.11.2
Parsing documentation for bundler-1.11.2
Installing ri documentation for bundler-1.11.2
Done installing documentation for bundler after 3 seconds
1 gem installed
```

**Comment by koichiro** [comment]
gem install

```
% gem install focuslight
Fetching: raindrops-0.16.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed raindrops-0.16.0
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: kgio-2.10.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed kgio-2.10.0
Fetching: unicorn-5.0.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed unicorn-5.0.1
Fetching: get_process_mem-0.2.0.gem (100%)
Successfully installed get_process_mem-0.2.0
Fetching: unicorn-worker-killer-0.4.4.gem (100%)
Successfully installed unicorn-worker-killer-0.4.4
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: sqlite3-1.3.11.gem (100%)
Building native extensions.  This could take a while...
Successfully installed sqlite3-1.3.11
Fetching: tilt-2.0.2.gem (100%)
Successfully installed tilt-2.0.2
Fetching: rack-protection-1.5.3.gem (100%)
Successfully installed rack-protection-1.5.3
Fetching: sinatra-1.4.7.gem (100%)
Successfully installed sinatra-1.4.7
Fetching: rack-test-0.6.3.gem (100%)
Successfully installed rack-test-0.6.3
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: backports-3.6.8.gem (100%)
Successfully installed backports-3.6.8
Fetching: sinatra-contrib-1.4.6.gem (100%)
Successfully installed sinatra-contrib-1.4.6
Fetching: sequel-4.32.0.gem (100%)
Successfully installed sequel-4.32.0
Fetching: ffi-1.9.10.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.10
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-4.2.6.gem (100%)
Successfully installed activesupport-4.2.6
Fetching: rrd-ffi-0.2.14.gem (100%)
Successfully installed rrd-ffi-0.2.14
Fetching: mysql2-0.4.3.gem (100%)
Building native extensions.  This could take a while...
Successfully installed mysql2-0.4.3
Fetching: librrd-1.0.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed librrd-1.0.4
Fetching: foreman-0.78.0.gem (100%)
Successfully installed foreman-0.78.0
Fetching: erubis-2.7.0.gem (100%)
Successfully installed erubis-2.7.0
Fetching: dotenv-2.1.0.gem (100%)
Successfully installed dotenv-2.1.0
Fetching: focuslight-0.1.4.gem (100%)
Successfully installed focuslight-0.1.4
Parsing documentation for raindrops-0.16.0
Installing ri documentation for raindrops-0.16.0
Parsing documentation for rack-1.6.4
Installing ri documentation for rack-1.6.4
Parsing documentation for kgio-2.10.0
Installing ri documentation for kgio-2.10.0
Parsing documentation for unicorn-5.0.1
Installing ri documentation for unicorn-5.0.1
Parsing documentation for get_process_mem-0.2.0
Installing ri documentation for get_process_mem-0.2.0
Parsing documentation for unicorn-worker-killer-0.4.4
Installing ri documentation for unicorn-worker-killer-0.4.4
Parsing documentation for thor-0.19.1
Installing ri documentation for thor-0.19.1
Parsing documentation for sqlite3-1.3.11
Installing ri documentation for sqlite3-1.3.11
Parsing documentation for tilt-2.0.2
Installing ri documentation for tilt-2.0.2
Parsing documentation for rack-protection-1.5.3
Installing ri documentation for rack-protection-1.5.3
Parsing documentation for sinatra-1.4.7
Installing ri documentation for sinatra-1.4.7
Parsing documentation for rack-test-0.6.3
Installing ri documentation for rack-test-0.6.3
Parsing documentation for multi_json-1.11.2
Installing ri documentation for multi_json-1.11.2
Parsing documentation for backports-3.6.8
Installing ri documentation for backports-3.6.8
Parsing documentation for sinatra-contrib-1.4.6
Installing ri documentation for sinatra-contrib-1.4.6
Parsing documentation for sequel-4.32.0
Installing ri documentation for sequel-4.32.0
Parsing documentation for ffi-1.9.10
Installing ri documentation for ffi-1.9.10
Parsing documentation for thread_safe-0.3.5
Installing ri documentation for thread_safe-0.3.5
Parsing documentation for tzinfo-1.2.2
Installing ri documentation for tzinfo-1.2.2
Parsing documentation for i18n-0.7.0
Installing ri documentation for i18n-0.7.0
Parsing documentation for activesupport-4.2.6
Installing ri documentation for activesupport-4.2.6
Parsing documentation for rrd-ffi-0.2.14
Installing ri documentation for rrd-ffi-0.2.14
Parsing documentation for mysql2-0.4.3
Installing ri documentation for mysql2-0.4.3
Parsing documentation for librrd-1.0.4
Installing ri documentation for librrd-1.0.4
Parsing documentation for foreman-0.78.0
Installing ri documentation for foreman-0.78.0
Parsing documentation for erubis-2.7.0
Installing ri documentation for erubis-2.7.0
Parsing documentation for dotenv-2.1.0
Installing ri documentation for dotenv-2.1.0
Parsing documentation for focuslight-0.1.4
Installing ri documentation for focuslight-0.1.4
Done installing documentation for raindrops, rack, kgio, unicorn, get_process_mem, unicorn-worker-killer, thor, sqlite3, tilt, rack-protection, sinatra, rack-test, multi_json, backports, sinatra-contrib, sequel, ffi, thread_safe, tzinfo, i18n, activesupport, rrd-ffi, mysql2, librrd, foreman, erubis, dotenv, focuslight after 255 seconds
28 gems installed
```

**Comment by koichiro** [comment]
focuslightインストール

```
% rehash
% focuslight new
% cd focuslight
% ls -la
total 12
drwxr-xr-x  6 koichiro  staff  204  3 26 11:27 ./
drwxr-xr-x  3 koichiro  staff  102  3 26 11:27 ../
-rw-r--r--  1 koichiro  staff  338  3 26 11:27 .env
-rw-r--r--  1 koichiro  staff  100  3 26 11:27 Procfile
-rw-r--r--  1 koichiro  staff  346  3 26 11:27 config.ru
drwxr-xr-x  2 koichiro  staff   68  3 26 11:27 log/
 % focuslight init
 % focuslight start
11:27:44 web.1     | started with pid 9115
11:27:44 worker1.1 | started with pid 9116
11:27:44 worker2.1 | started with pid 9117
11:27:44 web.1     | I, [2016-03-26T11:27:44.306185 #9115]  INFO -- : listening on addr=0.0.0.0:5125 fd=9
11:27:44 web.1     | I, [2016-03-26T11:27:44.306304 #9115]  INFO -- : worker=0 spawning...
11:27:44 web.1     | I, [2016-03-26T11:27:44.307409 #9115]  INFO -- : master process ready
11:27:44 web.1     | I, [2016-03-26T11:27:44.308573 #9118]  INFO -- : worker=0 spawned pid=9118
11:27:44 web.1     | I, [2016-03-26T11:27:44.309004 #9118]  INFO -- : Refreshing Gem list
11:27:44 web.1     | I, [2016-03-26T11:27:44.803235 #9118]  INFO -- : worker=0 ready
```

**Comment by koichiro** [comment]
データ投入
```
curl -F number=30 http://localhost:5125/api/socialgame/member/register
```

グラフがでない
![image](https://cloud.githubusercontent.com/assets/9646/14057551/c314b092-f346-11e5-88e5-6e9d95fe3294.png)

エラー
```
11:34:29 web.1     | 2016-03-26 11:34:29 - RuntimeError - RRDtool returns error to draw graph, error: option -u - Cannot convert '' to float:
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/focuslight-0.1.4/lib/focuslight/rrd.rb:255:in `graph'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/focuslight-0.1.4/lib/focuslight/web.rb:433:in `block in <class:Web>'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:52:in `process_client'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:92:in `process_client'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/bin/unicorn:23:in `load'
11:34:29 web.1     | 	/Users/koichiro/.rbenv/versions/2.3.0/bin/unicorn:23:in `<main>'
```

**Comment by koichiro** [comment]
`:upper_limit` `:lower_limit` のargsが空文字でわたってくるのが問題っぽい

**Comment by koichiro** [comment]
web.rbのグラフ表示のデフォルト値を数値すると表示できた

```
diff --git a/lib/focuslight/web.rb b/lib/focuslight/web.rb
index 6dce3d0..784ec56 100644
--- a/lib/focuslight/web.rb
+++ b/lib/focuslight/web.rb
@@ -391,8 +391,8 @@ class Focuslight::Web < Sinatra::Base
     notitle: { default: 'false', rule: rule(:bool) },
     xgrid: { default: '' },
     ygrid: { default: '' },
-    upper_limit: { default: '' },
-    lower_limit: { default: '' },
+    upper_limit: { default: 2 },
+    lower_limit: { default: 0 },
     rigid: { default: 'false', rule: rule(:bool) },
     sumup: { default: 'false', rule: rule(:bool) },
     step: { excludable: true, rule: rule(:uint) },
```

**Comment by koichiro** [comment]
rrd.rbにある `upper_limit` のデフォルト値は２になっている。

```
  rrdoptions = [
      tmpfile.path,
      '-w', width,
      '-h', height,
      '-a', 'PNG',
      '-l', 0, #minimum
      '-u', 2, #maximum
```

一方 web.rb のデフォルト値は2になってる。

```
graph_rendering_request_spec = {
  ...
    upper_limit: { default: 2 },
    lower_limit: { default: 0 },
...
```

２をデフォルトにすればよさそう。

**Comment by koichiro** [comment]
web.rbのグラフ表示のデフォルト値を数値すると表示できた

```
diff --git a/lib/focuslight/web.rb b/lib/focuslight/web.rb
index 6dce3d0..784ec56 100644
--- a/lib/focuslight/web.rb
+++ b/lib/focuslight/web.rb
@@ -391,8 +391,8 @@ class Focuslight::Web < Sinatra::Base
     notitle: { default: 'false', rule: rule(:bool) },
     xgrid: { default: '' },
     ygrid: { default: '' },
-    upper_limit: { default: '' },
-    lower_limit: { default: '' },
+    upper_limit: { default: 2 },
+    lower_limit: { default: 0 },
     rigid: { default: 'false', rule: rule(:bool) },
     sumup: { default: 'false', rule: rule(:bool) },
     step: { excludable: true, rule: rule(:uint) },
```

**Comment by koichiro** [comment]
https://github.com/focuslight/focuslight/pull/32

**Comment by kou** [comment]
おつかれさまでした！
