### ISSUE TITLE
OSS Gate Workshop: Osaka: 2017-04-22: yoichi: fluent-plugin-slack: Work log

### ISSUE THREAD

**Issue by yoichi** [oss-gate/workshop#387]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by yoichi** [comment]
https://github.com/sowawa/fluent-plugin-slack
によるとライセンスは
Apache License, Version 2.0
で
https://opensource.org/licenses/alphabetical
にある。 OSSだ。

**Comment by yoichi** [comment]
https://github.com/sowawa/fluent-plugin-slack
のInstallationに
$ fluent-gem install fluent-plugin-slack
とあるが、

~$ fluent-gem
zsh: command not found: fluent-gem
インストールするための fluent-gem が入ってない。

**Comment by yoichi** [comment]
fluent-gemで検索して
http://docs.fluentd.org/v0.12/articles/plugin-management
にたどり着いた。
If Using td-agent, Use /usr/sbin/td-agent-gem
とあるので、td-agent-gemかも。

~$ td-agent-gem
zsh: command not found: td-agent-gem
あれ、ない。

**Comment by yoichi** [comment]
td-agent-gem install で検索すると、日本語の
http://blogcdn.rutake.com/techmemo/2016/02/26/td-agent-%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B%E3%81%A8%E3%81%8D%E3%81%AFtd-agent-gem%E3%82%92%E5%88%A9/
を見つけた。見ると /opt にあるみたい。

~$ ls /opt/td-agent/usr/sbin
td-agent*     td-agent-gem* td-agent-ui*
あった！

**Comment by yoichi** [comment]
~$ /opt/td-agent/usr/sbin/td-agent-gem install fluent-plugin-slack
Fetching: fluent-plugin-slack-0.6.4.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/td-agent/embedded/lib/ruby/gems/2.1.0/ directory.

エラーになった！

**Comment by yoichi** [comment]
sudo したらインストールできた！

~$ /opt/td-agent/usr/sbin/td-agent-gem install fluent-plugin-slack
Fetching: fluent-plugin-slack-0.6.4.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /opt/td-agent/embedded/lib/ruby/gems/2.1.0/ directory.
~$ ls -ld /opt/td-agent/embedded/lib/ruby/gems/2.1.0/
drwxr-xr-x  8 root  wheel  272 12 25  2015 /opt/td-agent/embedded/lib/ruby/gems/2.1.0//
~$ sudo /opt/td-agent/usr/sbin/td-agent-gem install fluent-plugin-slack
Password:
Fetching: fluent-plugin-slack-0.6.4.gem (100%)
Successfully installed fluent-plugin-slack-0.6.4
Parsing documentation for fluent-plugin-slack-0.6.4
Installing ri documentation for fluent-plugin-slack-0.6.4
Done installing documentation for fluent-plugin-slack after 0 seconds
1 gem installed

**Comment by yoichi** [comment]
https://github.com/sowawa/fluent-plugin-slack
みて、Usageが３つもある。どれがいい？

* Incoming Webhook
* Slackbot
* Web API

Incoming Webhookって何？調べたら
http://qiita.com/vmmhypervisor/items/18c99624a84df8b31008
が見つかった。簡単そう。それでやってみる

**Comment by yoichi** [comment]
qiitaの通り、
https://slack.com/services/new/incoming-webhook
にアクセスして、ログイン。

slackでテスト用チャンネルを作って、それを指定したらURLできた。

**Comment by yoichi** [comment]
~$ sudo vi /etc/td-agent/td-agent.conf
で、https://github.com/sowawa/fluent-plugin-slack の設定例から

* webhook_url
* channel
* username

を書き換えたものを入れた。

**Comment by yoichi** [comment]
pythonからポストしてみる。
https://github.com/fluent/fluent-logger-python
の手順を参考に。

~$ python
Python 2.7.13 (default, Feb 25 2017, 09:47:40)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fluent import sender
>>> logger = sender.FluentSender('slack')
>>> logger.emit('follow', {'from': 'userA', 'to': 'userB'})
True
>>> logger.emit('slack', {'from': 'userA', 'to': 'userB'})
True

やってみたが、slack側に出てこない。

**Comment by yoichi** [comment]
/var/log/td-agent/td-agent.logをみると
2017-04-22 14:09:40 +0900 [warn]: no patterns matched tag="slack.follow"
2017-04-22 14:10:39 +0900 [warn]: no patterns matched tag="slack.slack"

machのパターンが違ってる。slack.* にしてみると、
/var/log/td-agent/td-agent.logには出なくなったが、やっぱりslackにはメッセージが出ない。

**Comment by iderihatakeshi** [comment]
よろしくお願いします。

**Comment by yoichi** [comment]
slackのwebhook設定のページに curl での手順があったのでそれで試す。

**Comment by yoichi** [comment]
td-agent.confのチャンネル名設定で # がついてないので付けてみたが変わらず。
https://github.com/sowawa/fluent-plugin-slack にも
channel to send messages (without first '#')
と書いてあるので # なしでただしそう。設定戻す。

**Comment by yoichi** [comment]
python から、match しない tag でログ書いてみたが、td-agent.log に no patterns matched のログが出ない。そもそも td-agent がうまく動作しなくなってる？

**Comment by yoichi** [comment]
sudo launchctl unload /Library/LaunchDaemons/td-agent.plist
sudo launchctl load /Library/LaunchDaemons/td-agent.plist
で再起動して、マッチしないパターンでpythonからpostしたら、no patterns matched のログが出た。
マッチするパターンでも投げてみると、td-agent.logにエラーログがでた：

```
2017-04-22 14:37:31 +0900 [warn]: emit transaction failed: error_class=IndexError error="string not matched" tag="slack.test"
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/mixin.rb:163:in `[]='
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/mixin.rb:163:in `filter_record'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/mixin.rb:188:in `filter_record'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/mixin.rb:89:in `block in format_stream'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event.rb:54:in `call'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event.rb:54:in `each'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/mixin.rb:87:in `format_stream'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:250:in `emit'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event_router.rb:88:in `emit_stream'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event_router.rb:79:in `emit'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:174:in `on_message'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:248:in `call'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:248:in `block in on_read_msgpack'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:247:in `feed_each'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:247:in `on_read_msgpack'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:233:in `call'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:233:in `on_read'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/io.rb:123:in `on_readable'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/io.rb:186:in `on_readable'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run_once'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run'
  2017-04-22 14:37:31 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_forward.rb:96:in `run'
2017-04-22 14:37:31 +0900 [error]: forward error error=#<IndexError: string not matched> error_class=IndexError
  2017-04-22 14:37:31 +0900 [error]: suppressed same stacktrace
```

**Comment by yoichi** [comment]
```
from fluent import sender
logger = sender.FluentSender('slack')
logger.emit('test', {'text': 'test message via fluentd'})
```
→ td-agent.logに
```
2017-04-22 14:43:01 +0900 [warn]: out_slack: the specified key 'message' not found in record. [{"text"=>"test message via fluentd", "time"=>"14:42:09", "tag"=>"slack.test"}]
2017-04-22 14:43:01 +0900 [info]: out_slack: post_message {:channel=>"#ossgate-test", :text=>"\n", :username=>"webhookbot", :icon_emoji=>":ghost:", :mrkdwn=>true, :link_names=>true}
```
slackには空文字のメッセージが届いた。

```
from fluent import sender
logger = sender.FluentSender('slack')
logger.emit('test', {'message': 'test message via fluentd'})
```
にしたら、slackに "test message via fluentd" がpostされた。

**Comment by yoichi** [comment]
```
from fluent import sender
logger = sender.FluentSender('slack')
logger.emit('test', 'test message via fluentd in text')
```
だと最初のIndexErrorになる。（最初はこのコードでポストして試してた。）

**Comment by yoichi** [comment]
message をキーにしないといけないのは、
https://github.com/sowawa/fluent-plugin-slack
の例にも書いてあるので仕様っぽい。

いただいた疑問点。
* 文字数制限はある？
* テキスト以外も送れる？

**Comment by yoichi** [comment]
フィードバック案。

td-agent.confに書ける設定はpostするjsonのbodyにも書けそう（要事実確認）
静的な設定の他、post単位で設定を変えたい場合に使える。

https://github.com/sowawa/fluent-plugin-slack
のドキュメントには少なくとも書いてない。post例は {"message": "text message body"} のみ。

確認の上、

* ドキュメントに書いてないだけならドキュメントに書く。
* 機能としてないのであれば、欲しいので実装する。

をしたい。

**Comment by yoichi** [comment]
事実関係確認のため、試しに

```
from fluent import sender
logger = sender.FluentSender('slack')
logger.emit('test', {'message': 'test message via fluentd', 'username': 'overwritten by message body'})
```

を送信してみたが、td-agent.logには
```
2017-04-22 15:46:25 +0900 [info]: out_slack: post_message {:channel=>"#ossgate-test", :text=>"test message via fluentd\n", :username=>"webhookbot", :icon_emoji=>":ghost:", :mrkdwn=>true, :link_names=>true}
```

と出てusernameはtd-agent.confに書かれたものが使われている。機能としてない？

**Comment by yoichi** [comment]
それっぽいissueがある。
https://github.com/sowawa/fluent-plugin-slack/issues/33
Ability to use more than one slack plugin with custom icons/username options

https://github.com/sowawa/fluent-plugin-slack/pull/32
を投げて、駄目となって、代わりにissueを立てて放置されているぽい。

何故駄目だったのか見る。

**Comment by yoichi** [comment]
上記のpull-requestとの関係は不明なので要確認→後で調べる。
ここでは、その機能がなかったという前提で、機能追加を要望として出すissueの文案をつくってみる。

(まず日本語で)

題名: td-agent.conf の設定をメッセージ単位で上書きしたい

XXX: 「メッセージ」という用語は適切？後で調べる。

本文:
td-agent.confで設定できる項目に、username, icon_emoji があるが、
一つの td-agent インスタンスの中で、メッセージ単位で、切り替えたい場合があります。
送信するjsonの属性として指定されたものでそれらを上書きするように拡張することはできないでしょうか？

**Comment by yoichi** [comment]
試しにさっき見つけたPRのパッチを試してみる。
どこにファイル配置されてるのか調べる。

**Comment by yoichi** [comment]
PRを取ってくるのは .git/config に
fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
を足して git pull する。上書きして動作見たが変わらなかった。別の目的の変更だったのかな。

**Comment by yoichi** [comment]
そもそもtd-agent.conf内でtag単位で設定を分けられるので、メッセージ単位で切り替えるというような思想ではないのかも。

**Comment by yoichi** [comment]
フィードバックポイントを再度探し直し。
https://github.com/sowawa/fluent-plugin-slack 
の例で、slackという単語がtagのキーと、type とで使われている。別の単語にしたほうがわかりやすい気がする。

**Comment by yoichi** [comment]
そもそもtd-agent.confの "@type slack" という行の @ は何を意味している？example.confでは @ なしで "type slack" と書かれている。

**Comment by yoichi** [comment]
http://docs.fluentd.org/v0.12/articles/config-file の例では @ がついてる。

**Comment by iderihatakeshi** [comment]
http://qiita.com/repeatedly/items/e882fdb46dfe85d9556f @type とtypeについて

**Comment by yoichi** [comment]
example.confでも @ を付けたほうがよさそう。
https://github.com/sowawa/fluent-plugin-slack/commit/aa6ac233c3258638e9e4f3063e434e1c9ce8180e
の適用漏れ。

**Comment by yoichi** [comment]
PRおくった。
https://github.com/sowawa/fluent-plugin-slack/pull/36

**Comment by yoichi** [comment]
コミットログでわかるだろうと、PRの本文を最初書かなかった。
大丈夫じゃないかも、書いておいて悪いことはないというコメントいただいて、確かにそうだと思ったので追記した。

**Comment by yoichi** [comment]
Ruby わかっていないのでソースの内容を理解できていない。
プラグインのソースはそれほど大きくなし、実際使ってみたものなので Rubyの勉強の題材としてよいかもと思った。

**Comment by ShinjiEnoki** [comment]
よろしくお願いします！

**Comment by yoichi** [comment]
気になること。

* td-agent.confの更新の反映のために、td-agent再起動は必要なのか？（仕様上）
* 必要なら、プラグイン入れて設定する手順の付近に情報があったら助かる。

**Comment by yoichi** [comment]
うまく動くようになった後も、ポストしてるのにtd-agent.logにも出ず、ポストもされないケースがあったような気がする。ログをロストする問題があるのかもしれない。

**Comment by ShinjiEnoki** [comment]
やや手こずった印象です。
少し複雑なプログラムということかも知れませんが...
Slackの通し手順があればわかりやすいかもと思いました。

**Comment by yoichi** [comment]
> https://github.com/sowawa/fluent-plugin-slack
> のInstallationに
> $ fluent-gem install fluent-plugin-slack
> とあるが、

他のプラグインで
https://github.com/fluent/fluent-plugin-rewrite-tag-filter
だとInstallationに複数のパターンが書かれていた。
