### ISSUE TITLE
OSS Gate Workshop: Sapporo: 2017-06-17: pomu0326: nextCloud: Work log

### ISSUE THREAD

**Issue by pomu0326** [oss-gate/workshop#441]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by iakio** [comment]
宜しくお願いします！

**Comment by pomu0326** [comment]
nextCloud をインストールしてみたい

**Comment by pomu0326** [comment]
インストールドキュメントはここ
https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html

**Comment by pomu0326** [comment]
まずは linux 環境が必要。どのディストリビューションでやる？

**Comment by pomu0326** [comment]
snap パッケージって何？https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#installing-via-snap-packages

**Comment by pomu0326** [comment]
snap コマンドが必要そう

**Comment by pomu0326** [comment]
apache, mariadb, php 各種モジュールのインストールが必要

**Comment by pomu0326** [comment]
とりあえず動かしたいだけだから、すでに用意されている docker イメージから立ち上げる
https://hub.docker.com/_/nextcloud/

**Comment by pomu0326** [comment]
コマンド実行！`docker run -d -p 8080:80 nextcloud`

**Comment by pomu0326** [comment]
まずは起動確認 OK!

**Comment by pomu0326** [comment]
使い方を調べる

**Comment by pomu0326** [comment]
https://docs.nextcloud.com/server/12/admin_manual/installation/installation_wizard.html
初回設定の使い方はここ

**Comment by pomu0326** [comment]
デフォルト設定のまま 管理者ユーザーとパスワードを入力して登録してみる。

**Comment by pomu0326** [comment]
ログインできました。

**Comment by pomu0326** [comment]
docker だとかんたんに起動できたけど、フルで環境作ろうと思うと大変かも？

**Comment by pomu0326** [comment]
ビデオチャット機能があるようなので、その機能を有効にしてみる
https://nextcloud.com/webrtc/

プラグインとして実装されているようなので、プラグインの管理ドキュメントを読んでみる。
https://docs.nextcloud.com/server/12/admin_manual/installation/apps_management_installation.html

**Comment by pomu0326** [comment]
デフォルトではこのプラグインはないようなので、別途プラグインを追加する必要がある。
https://apps.nextcloud.com/apps/spreed

**Comment by pomu0326** [comment]
![image](https://user-images.githubusercontent.com/8056227/27250390-3772f858-5369-11e7-9192-5627e26af72a.png)
video call ボタンをクリックしたら内部エラー

**Comment by pomu0326** [comment]
ちょいとログを探してみる

**Comment by pomu0326** [comment]
json 形式のログが plain では読みづらいので jq コマンドインストール

**Comment by pomu0326** [comment]
エラーログ
```
{
  "reqId": "aKXuZ2nrVTdzhqVyxbGH",
  "level": 3,
  "time": "2017-06-17T05:27:35+00:00",
  "remoteAddr": "172.17.0.1",
  "user": "admin",
  "app": "index",
  "method": "GET",
  "url": "/index.php/settings/apps/list?category=disabled",
  "message": "Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT \\\"uid\\\", \\\"displayname\\\" FROM \\\"oc_users\\\" WHERE LOWER(\\\"uid\\\") = LOWER(?)' with params [\\\"admin\\\"]:\\n\\nSQLSTATE[HY000]: General error: 17 database schema has changed\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT \\\"uid\\\", \\\"...', Array)\\n#2 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/db\\/statementwrapper.php(70): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Database.php(249): OC_DB_StatementWrapper->execute(Array)\\n#4 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Database.php(303): OC\\\\User\\\\Database->loadUser('admin')\\n#5 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Manager.php(133): OC\\\\User\\\\Database->userExists('admin')\\n#6 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Session.php(219): OC\\\\User\\\\Manager->get('admin')\\n#7 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(319): OC\\\\User\\\\Session->getUser()\\n#8 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(110): OC_App::getEnabledApps()\\n#9 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/user.php(128): OC_App::loadApps(Array)\\n#10 \\/var\\/www\\/html\\/lib\\/base.php(739): OC_User::setupBackends()\\n#11 \\/var\\/www\\/html\\/lib\\/base.php(1082): OC::init()\\n#12 \\/var\\/www\\/html\\/index.php(38): require_once('\\/var\\/www\\/html\\/l...')\\n#13 {main}\",\"File\":\"\\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractSQLiteDriver.php\",\"Line\":85}",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38",
  "version": "12.0.0.29"
}
{
  "reqId": "0ZAOklJow3fRbhu4qO5G",
  "level": 3,
  "time": "2017-06-17T05:27:36+00:00",
  "remoteAddr": "172.17.0.1",
  "user": "admin",
  "app": "index",
  "method": "POST",
  "url": "/index.php/settings/ajax/enableapp.php",
  "message": "Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT \\\"uid\\\", \\\"displayname\\\" FROM \\\"oc_users\\\" WHERE LOWER(\\\"uid\\\") = LOWER(?)' with params [\\\"admin\\\"]:\\n\\nSQLSTATE[HY000]: General error: 17 database schema has changed\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT \\\"uid\\\", \\\"...', Array)\\n#2 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/db\\/statementwrapper.php(70): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Database.php(249): OC_DB_StatementWrapper->execute(Array)\\n#4 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Database.php(303): OC\\\\User\\\\Database->loadUser('admin')\\n#5 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Manager.php(133): OC\\\\User\\\\Database->userExists('admin')\\n#6 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Session.php(219): OC\\\\User\\\\Manager->get('admin')\\n#7 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(319): OC\\\\User\\\\Session->getUser()\\n#8 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(110): OC_App::getEnabledApps()\\n#9 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/user.php(128): OC_App::loadApps(Array)\\n#10 \\/var\\/www\\/html\\/lib\\/base.php(739): OC_User::setupBackends()\\n#11 \\/var\\/www\\/html\\/lib\\/base.php(1082): OC::init()\\n#12 \\/var\\/www\\/html\\/index.php(38): require_once('\\/var\\/www\\/html\\/l...')\\n#13 {main}\",\"File\":\"\\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractSQLiteDriver.php\",\"Line\":85}",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38",
  "version": "12.0.0.29"
}
{
  "reqId": "89ceUuzWfq2YxZ46MFLM",
  "level": 3,
  "time": "2017-06-17T05:27:36+00:00",
  "remoteAddr": "172.17.0.1",
  "user": "admin",
  "app": "index",
  "method": "GET",
  "url": "/index.php",
  "message": "Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT \\\"uid\\\", \\\"displayname\\\" FROM \\\"oc_users\\\" WHERE LOWER(\\\"uid\\\") = LOWER(?)' with params [\\\"admin\\\"]:\\n\\nSQLSTATE[HY000]: General error: 17 database schema has changed\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT \\\"uid\\\", \\\"...', Array)\\n#2 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/db\\/statementwrapper.php(70): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Database.php(249): OC_DB_StatementWrapper->execute(Array)\\n#4 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Database.php(303): OC\\\\User\\\\Database->loadUser('admin')\\n#5 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Manager.php(133): OC\\\\User\\\\Database->userExists('admin')\\n#6 \\/var\\/www\\/html\\/lib\\/private\\/User\\/Session.php(219): OC\\\\User\\\\Manager->get('admin')\\n#7 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(319): OC\\\\User\\\\Session->getUser()\\n#8 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/app.php(110): OC_App::getEnabledApps()\\n#9 \\/var\\/www\\/html\\/lib\\/private\\/legacy\\/user.php(128): OC_App::loadApps(Array)\\n#10 \\/var\\/www\\/html\\/lib\\/base.php(739): OC_User::setupBackends()\\n#11 \\/var\\/www\\/html\\/lib\\/base.php(1082): OC::init()\\n#12 \\/var\\/www\\/html\\/index.php(38): require_once('\\/var\\/www\\/html\\/l...')\\n#13 {main}\",\"File\":\"\\/var\\/www\\/html\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractSQLiteDriver.php\",\"Line\":85}",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38",
  "version": "12.0.0.29"
}
```

**Comment by pomu0326** [comment]
ログ参照元 `/var/www/html/data/nextcloud.log`

**Comment by pomu0326** [comment]
apache 側のアクセスログ
```
172.17.0.1 - - [17/Jun/2017:05:27:32 +0000] "GET /index.php HTTP/1.1" 500 5519 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38"
172.17.0.1 - - [17/Jun/2017:05:27:36 +0000] "GET /core/css/guest.css?v=2b3ba31c3e5d41de6f94372ea5cff05a-0 HTTP/1.1" 200 4760 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38"
172.17.0.1 - - [17/Jun/2017:05:27:35 +0000] "GET /index.php/apps/files HTTP/1.1" 200 6329 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.90 Safari/537.36 Vivaldi/1.91.867.38"
```

**Comment by pomu0326** [comment]
2要素認証も適用してみる
https://github.com/nextcloud/twofactor_totp#readme

**Comment by pomu0326** [comment]
`有効にする` ボタンをクリック
![image](https://user-images.githubusercontent.com/8056227/27250500-b6b958d4-536c-11e7-9fb1-d9f78ca0fd78.png)

**Comment by pomu0326** [comment]
インストールの進捗がすごくわかりづらい

↓↓ インストール中の画面
![image](https://user-images.githubusercontent.com/8056227/27250503-d049ef2a-536c-11e7-8e23-6a53f15316bf.png)

**Comment by pomu0326** [comment]
個人設定の画面から TOTP を有効化
![image](https://user-images.githubusercontent.com/8056227/27250525-567837e6-536d-11e7-8779-d7a4ce76d18a.png)

**Comment by pomu0326** [comment]
TOTP アプリが必要っぽい

**Comment by pomu0326** [comment]
Google Play で TOTP で検索しても出てこない。おすすめの TOTP アプリの記載があると嬉しいかも。

**Comment by pomu0326** [comment]
google の TOTP クライアントで試しに登録してみた。
ログイン時に TOTP 認証コードが聞かれて、クライアントに表示されるコードを入力することでログインできることを確認。

**Comment by pomu0326** [comment]
nextcloud のコントリビュートガイド
https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md

**Comment by pomu0326** [comment]
documentation レポ
https://github.com/nextcloud/documentation

**Comment by pomu0326** [comment]
"Administration Manual" の中に、Docker でのインストレーションを説明するセクションがほしい。

## Expect
Administration Manual の Installation セクションのサブセクションとして "installing from docker" のようなものがほしい。
内容は https://github.com/nextcloud/docker の README レベルでかまわない。

## Actual
Administration Manual から Docker を使った installation の説明に辿れるパスすらない。

## 理由
私はすぐに nextcloud を触ってみたいが、"Installation on Linux" の説明は難しすぎる。
その後 docker で立ち上げてみたらすぐに出来たので、これが Administartion Manual に記述されていると素晴らしいと思った。

**Comment by pomu0326** [comment]
英語

I'd like a section explaining the installation with Docker in the Administration Manual.


## Expect
I want something like "installing from docker" as a subsection of the Installation section of "Administration Manual".The content can be at the README level of https://github.com/nextcloud/docker.

## Actual
There is no pass which can follow the explanation of installation using Docker from "Administration Manual".

## Because
I would like to use nextcloud immediately, but the explanation of "Installation on Linux" is too difficult. After that, I started it with docker, so I made it immediately, so I thought it was wonderful if it was described in the Administartion Manual.

**Comment by pomu0326** [comment]
タイトル修正

I'd like a section explaining the installation with Docker in the Administration Manual.

=> Documentation for installation with docker

**Comment by pomu0326** [comment]
Issue 立てました！
https://github.com/nextcloud/documentation/issues/505

**Comment by tricknotes** [comment]
本日はおつかれさまでした！
よかったらまた参加してみてくださいね！
