### ISSUE TITLE
OSS Gate Workshop:Osaka: 2017-08-12:yukihirop:rails: Work log

### ISSUE THREAD

**Issue by yukihirop** [oss-gate/workshop#522]

**Comment by yukihirop** [comment]
* CONTRIBUTE.mdを読む
    * `Security Poricy` に目を通している

**Comment by yukihirop** [comment]
railsのGemfile使っているgemが以外に少なくてびっくりした。

**Comment by yukihirop** [comment]
rails、rubocopを使っているみたい。
Gemfile、文字列展開の無い場合でダブルクォート使っているが、シングルクォートで警告がでないのは
rubocopでexcludeしているからかな？

**Comment by yukihirop** [comment]
あー、逆にダブルクォート使えよってしてるのね
```.rubocop.yml
# Check quotes usage according to lint rule below.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
```

**Comment by yukihirop** [comment]
railsより自分が普段扱っているリポジトリの方が複雑なような気がしてきた。
（ソースコードはrailsの方が複雑だろうけど)

**Comment by yukihirop** [comment]
minitest初めて触ったー
`bundle exec rake test`で実行するのね

**Comment by yukihirop** [comment]
`redis-server` が起動してないから、動かないテストがあったらしい？？
```
Error:
RedisAdapterTest::Hiredis#test_channel_prefix:
Redis::CommandError: ERR Client sent AUTH, but no password is set
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:121:in `call'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:102:in `block in connect'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:100:in `connect'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:276:in `with_socket_timeout'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:133:in `call_loop'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/subscribe.rb:43:in `subscription'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/subscribe.rb:12:in `subscribe'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:2765:in `_subscription'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:2143:in `block in subscribe'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
    /Users/fukudayukihiro/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:2142:in `subscribe'
    /Users/fukudayukihiro/RubymineProjects/rails/actioncable/lib/action_cable/subscription_adapter/redis.rb:81:in `block in listen'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis/client.rb:293:in `with_reconnect'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:64:in `block in with_reconnect'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
    /Users/fukudayukihiro/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:63:in `with_reconnect'
    /Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/redis-3.3.3/lib/redis.rb:70:in `without_reconnect'
    /Users/fukudayukihiro/RubymineProjects/rails/actioncable/lib/action_cable/subscription_adapter/redis.rb:78:in `listen'
    /Users/fukudayukihiro/RubymineProjects/rails/actioncable/lib/action_cable/subscription_adapter/redis.rb:152:in `block in ensure_listener_running'

```

**Comment by yukihirop** [comment]
`bundle exec rake test` ではしらせたテストのログが残る場所ってどこ？

**Comment by yukihirop** [comment]
`bundle exec rake test` の標準入力と標準出力を別につくったlogファイルにリダイレクトさせればよい

**Comment by yukihirop** [comment]
`bundle exec rake test  2>&1 > log/test.log`

**Comment by yukihirop** [comment]
railsにテストがいくつあるか数える方法
`find $(find . -name 'test' -type d -maxdepth 2) -type f | wc -l`

**Comment by yukihirop** [comment]
特定のテストを実行させる場合
```
cd activerecord
$ bundle exec ruby -I test test/cases/adapter_test.rb
Using sqlite3
Run options: --seed 24136

# Running:

...........................

Finished in 0.290243s, 93.0255 runs/s, 275.6312 assertions/s.
27 runs, 80 assertions, 0 failures, 0 errors, 0 skips

```

RAILS_ENV=developmentになってテストされているので注意

**Comment by yukihirop** [comment]
最新のrailsではテストを実行する時は、

```
cd activerecord
bundle exec rails test test/cases/adapter_test.rb
```
とかにすれば、RAILS_ENV=testで実行してくれる

bundle exec は Gemfile.lockに従ってバージョンを固定した上で実行してくれる

**Comment by yukihirop** [comment]
`.yardopts` はソースコードに書いたコメントからdocを起こす時のフォーマットとかのオプション指定
をしているファイル

**Comment by yukihirop** [comment]
`.gitattributes` はなんで入れているのだろう
`.codeclimate.yml` でカバレッジも図っているのね

**Comment by yukihirop** [comment]
何かソースコードを追加したときの影響範囲が大丈夫かは、いじったディレクトリ(activerecordならactiverecord)のテストを全て走らせて通ったら、とりあえずOKって判断する。
あとは、git pushしてtravisに確かめてもらうしか無い。

**Comment by yukihirop** [comment]
```
Finished in 0.000842s, 2375.4577 runs/s, 3563.1866 assertions/s.
2 runs, 3 assertions, 0 failures, 0 errors, 0 skips
** Execute test
rake aborted!
Errors in activerecord, actioncable
/Users/fukudayukihiro/RubymineProjects/rails/Rakefile:29:in `block (2 levels) in <top (required)>'
/Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/fukudayukihiro/.rbenv/versions/2.4.1/bin/bundle:22:in `load'
/Users/fukudayukihiro/.rbenv/versions/2.4.1/bin/bundle:22:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)

```

rails全部テスト走らせてみた、`activerecord` と `actioncable` にErrorが出てるのが判明

**Comment by yukihirop** [comment]
`bundle exec rake test ` でminitestを走らせる時、ファイルを指定するやり方が知りたい。

**Comment by yukihirop** [comment]
`bundle exec rake test_sqlite3 TEST=`
みたいな感じでテストが実行できる

**Comment by daddygongon** [comment]
振り返りでお話しさせていただいた西谷です．
1 errorが出た
1 個別テスト
ですね．どちらもネタとして重要ですよね．

**Comment by yalab** [comment]
ファイル単体で test を動かす方法のドキュメントを追加してあげると良いですね

**Comment by yukihirop** [comment]
rake testで単体でテストは知らせられないかなーって各ディレクトリのRakefileを読んでいた時、
その方法は、ソースコードのコメントとして書いてあったが、肝心のドキュメント[RUNNING_UNIT_TESTS.rdoc](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/RUNNING_UNIT_TESTS.rdoc)には書いていなかったので追加しようと考えた。

ソースコードを読まないドキュメントから読む開発者には役に立つと思う。

[activerecord/RUNNING_UNIT_TESTS.rdoc](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/RUNNING_UNIT_TESTS.rdoc)
```diff 
== Running the Tests

To run a specific test:

  $ bundle exec ruby -Itest test/cases/base_test.rb -n method_name

To run a set of tests:

  $ bundle exec ruby -Itest test/cases/base_test.rb

+ To run a single test suite
+
+   rake test TEST=path/to/test.rb
```

どうでしょうか？

**Comment by daddygongon** [comment]
bundle exec rake test TEST=path/to/test.rb
のほうがいいかも．ちょっと試してみてください．

**Comment by yukihirop** [comment]
了解です！

**Comment by yalab** [comment]
ファイル単体で特定の adapter で test する方法は https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/RUNNING_UNIT_TESTS.rdoc#config-file に

```
$ ARCONN=postgresql bundle exec ruby -Itest test/cases/base_test.rb
```

と載っているので、この下に rake の task として実行するには

**Comment by yukihirop** [comment]
メンターさんと話し合った結果、 `rake test TEST=path/to/test.rb` はざっくりしすぎているので、
こういう困ったことが起きて、○○のように改善したら上手く行ったので、○○をドキュメントに書いたら、開発者の役に立つのではないか？という趣旨で書くようにしたらどうかとあったので、↑のように具体的な場合で書きます！

**Comment by daddygongon** [comment]
あ．そっちのほうがいいです．いろいろな意見があるでしょうから．自分の窮状を訴えて，こんな人もユーザにいるのやというのをまずは知らしめましょう．

**Comment by yukihirop** [comment]
`bundle exec rake test:postgresql TEST=test/cases/base_test.rb`

[activerecord/RUNNING_UNIT_TESTS.rdoc](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/RUNNING_UNIT_TESTS.rdoc)
```diff
== Config File

If +test/config.yml+ is present, then its parameters are obeyed; otherwise, the
parameters in +test/config.example.yml+ are.

You can override the +connections:+ parameter in either file using the +ARCONN+
(Active Record CONNection) environment variable:

  $ ARCONN=postgresql bundle exec ruby -Itest test/cases/base_test.rb

Or

+ $ bundle exec rake test:postgresql TEST=test/cases/base_test.rb

You can specify a custom location for the config file using the +ARCONFIG+
environment variable.
```

**Comment by yalab** [comment]
それだけでも載ってる価値はあると思うので後は pull req を投げる時になぜそれを載せたいのかの説明を補ってあげるとより良いです。

**Comment by yukihirop** [comment]
どうやってコミットメッセージを書くかは実際に、`git log` でしらべる。
これは `lessドキュメント` で開いているので、例えば「document」で調べたい場合は、
`/document` とすると見ることが出来る。

どうやらドキュメントの変更の場合は、commitメッセージに `[ci skip]` と書いたらいいらしい

**Comment by yukihirop** [comment]
コミットメッセージコレで行きます！

`Add document that you rake test single file by using DB(ex. postgresql) [ci skip]`

**Comment by yalab** [comment]
やりましょう！

**Comment by yukihirop** [comment]
以下の内容をプルリクに書きたいと思います。

```shell
$ bundle exec rake test:postgresql TEST=test/cases/base_test.rb
/Users/fukudayukihiro/.rbenv/versions/2.4.1/bin/ruby -w -I"lib:test" -I"/Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib" "/Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/cases/base_test.rb" 
Using postgresql
Run options: --seed 4420

# Running:

...................................................................................................................................................

Finished in 2.544319s, 57.7758 runs/s, 135.9892 assertions/s.
147 runs, 346 assertions, 0 failures, 0 errors, 0 skips

```

**Comment by yukihirop** [comment]
プルリクの内容を考えます。

**Comment by yukihirop** [comment]
* I want to `rake test by using DB(ex. postgresql)` for single file.
* When I see [activerecord/RUNNING_UNIT_TESTS.rdoc](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activerecord/RUNNING_UNIT_TESTS.rdoc),  I can not found.
* I add document.

I try like that:

```shell
$ bundle exec rake test:postgresql TEST=test/cases/base_test.rb
/Users/fukudayukihiro/.rbenv/versions/2.4.1/bin/ruby -w -I"lib:test" -I"/Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib" "/Users/fukudayukihiro/RubymineProjects/rails/vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/cases/base_test.rb" 
Using postgresql
Run options: --seed 4420

# Running:

...................................................................................................................................................

Finished in 2.544319s, 57.7758 runs/s, 135.9892 assertions/s.
147 runs, 346 assertions, 0 failures, 0 errors, 0 skips

```

**Comment by yukihirop** [comment]
railsにプルリク出しました
https://github.com/rails/rails/pull/30206

**Comment by yalab** [comment]
👍

**Comment by gh640** [comment]
とてもわかりやすくご説明いただきありがとうございます。お疲れさまでした！

**Comment by yukihirop** [comment]
リアクションありがとうございます。

**Comment by murajun1978** [comment]
お疲れ様でした！
closeしますが、引き続きここを使っても大丈夫です！
チャットのURLは https://gitter.im/oss-gate/devel です！
