### ISSUE TITLE
OSS Gateワークショップ 2016-06-10: speee-nakajima: gon: 作業ログ

### ISSUE THREAD

**Issue by speee-nakajima** [oss-gate/workshop#53]
OSS Gate へようこそ。

Workshop では一人ずつ GitHub issue を立ててそこで作業ログを残していきながら進めます。
過去のビギナーのものはこちらで見られます。 https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed

## この issue 作成時点でまずやること

- この issue のタイトルを「OSS Gateワークショップ ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: 作業ログ」の形式でつけてください
- OSS 名が未定の場合はタイトルは後からでも変えられるので、とりあえず未定などでも OK です

## 作業開始してからやること

以下を参考にしながらやってみます。

https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md

## 作業ログについての説明（わからなくなったら都度読み返してください）

作業ログは、ビギナーが、このワークショップを通して得るものをより増やすために重要になります。なぜなら作業ログがメンターからのフィードバックをより充実させるからです。

作業ログを元にメンターと「ふりかえり」をするタイミングがあります。「ふりかえり」では次のことをします。

  * ビギナーは作業ログの内容を順にメンターに説明する。
  * メンターは説明を聞いてビギナーにフィードバックをする。

メンターは次のようなフィードバックをします。これは、ビギナーとは違う視点からビギナーの行動を観察することおよびメンターの経験があるからできることです。（「ふりかえり」の前にこんなフィードバックをよろしくお願いします！とお願いすると効果が高まるので実践してみましょう。）

  * ビギナーが気づかずにやっていたよい行動に気づくきかっけを与え、今後もその行動を継続するように促します。
  * ビギナーが困っていることについて、解決策を一緒に考えてくれます。
  * 適切な質問をしてビギナーが整理できていない行動や考えを整理してくれます。
  * ビギナーが「問題」だと認識していないこと（「問題発見」は難しい！）をメンターの視点から「問題」だと見つけてくれます。「問題」がはっきりしたら直しましょう。
  * ビギナーが次にどの方向に進めばよいかを整理してくれます。

このように、ビギナーの作業をメンター視点で一緒に整理し、ビギナーの今後の行動に活かす活動がここでいう「ふりかえり」です。そのため、「ビギナーにとって」ログに残すべきかどうか、という視点ではなく、「とりあえずログに残す」という視点でログを残してください。これは、ビギナーが重要だと判断しなくてもメンターの視点から見たら大事なこともあるからです。

ログに残すときは次のようなときです。

  * 違う作業を始めたとき（インストールを始めた、動作確認を始めた、テストを始めた、とか）
  * 詰まったとき（インストール時にエラーがでた、ビルドが失敗した、とか）
  * issueを出したとき
  * pull requestを出したとき

ログに残すことは次のことです。「備考」以外は作業の邪魔にならないように一言でよいです。備考は作業に役立つので必要な分だけ書いてください。

  * 作業（やること、やっていること、やったこと。）
  * 思っていること（そのときどう思っているか。）
  * 備考（必要な付加情報。）

ログはコメントとして追記していってください。テンプレートは次の通りです。

    * 作業（ここにやること、やっていること、やったことを書く）
    * 思っていること：（今どう思っているかを書く）

    備考：（必要なら必要なだけ書く。必要ないなら書かなくてもよい。）

例1（備考なし）：

    * 作業：インストールを始めた
    * 思っていること：ドキュメント通りに進めれば大丈夫だろう

例2：

    * 作業：インストールが失敗した
    * 思っていること：ドキュメントに手順が足りない？

    備考：エラーメッセージは次の通り

    ```text
    XXX is not found
    ```

    必要なファイルが足りないのかなぁ。

**Comment by speee-nakajima** [comment]
* READMEを読む
* PR送るとしたら英語で送らないといけないから失敗したかも

**Comment by speee-nakajima** [comment]
* まずはこのissue読みだった
* 忘れてた

**Comment by speee-nakajima** [comment]
* READMEを読む
* PR送るとしたら英語で送らないといけないから失敗したかも

**Comment by speee-nakajima** [comment]
* README読み中
* リンクにアクセスしたがネットが重い...

**Comment by speee-nakajima** [comment]
* README -> [gon.watch](http://railscasts.com/episodes/324-passing-data-to-javascript)
* なにかヒントがあると思ったが最初はこのままREADMEを読んだほうがいいかも...

**Comment by speee-nakajima** [comment]
* README -> An example of typical use
* 文字で何するか書いてあるけどコードで書いてほしい

**Comment by speee-nakajima** [comment]
* README -> 1. Write variables by
* `:user_id => 1,` rubocop でいつも怒られるやつ

**Comment by speee-nakajima** [comment]
* README -> 1. Write variables by
* `gon.push(any_object)` any_objectどこやねん

**Comment by speee-nakajima** [comment]
* README
* > With the gon.watch feature you can easily renew data in gon variables!
知らんかった

**Comment by speee-nakajima** [comment]
* README
* `AMD compatible version` AMDってなんぞ CPU?

**Comment by speee-nakajima** [comment]
* README
* かと言ってソースがいきなりgemありきでインストール手順がなさそう

**Comment by speee-nakajima** [comment]
* README
* いきなりcontroller と viewに入っていったのでとりあえず動かすというまで読み解くのがちょっと面倒

**Comment by speee-nakajima** [comment]
* README
* 
```
gem 'gon'
gem 'rabl-rails'
```
来たのがいきなり rabl-rails 版ｗ

**Comment by speee-nakajima** [comment]
* rabl-railsをやってみる
* せっかく出てきたからやってみるか...
``` shell
mkdir -p ossws/gon
```

```Gemfile
gem 'gon'
gem 'rabl-rails'
```

```shell
bundle
```

** エラー
```
Your Gemfile has no gem server sources. If you need gems that are not already on your
machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'rabl-rails' in any of the gem sources listed in your Gemfile or
available on this machine.
```

**Comment by speee-nakajima** [comment]
* rabl-railsやってみる
* Gemfileを変更
```Gemfile
source 'https://rubygems.org'
gem 'gon'
gem 'rabl-rails'
```

```shell
bundle
```

nokogiriさんきたで

```log
Fetching gem metadata from https://rubygems.org/................
Fetching version metadata from https://rubygems.org/..
Resolving dependencies....
Installing rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Installing minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Installing mini_portile2 2.1.0
Installing pkg-config 1.1.7
Using rack 1.6.4
Installing multi_json 1.12.1
Installing request_store 1.3.1
Using thor 0.19.1
Using bundler 1.11.2
Using tzinfo 1.2.2
Installing nokogiri 1.6.8 with native extensions
Using rack-test 0.6.3
Installing activesupport 4.2.6
Using loofah 2.0.3
Using rails-deprecated_sanitizer 1.0.3
Installing rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Installing actionview 4.2.6
Installing actionpack 4.2.6
Using gon 6.0.1
Installing railties 4.2.6
Installing rabl-rails 0.4.3
Bundle complete! 2 Gemfile dependencies, 27 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

成功して良かった
nokogiriの不安感やばい

**Comment by speee-nakajima** [comment]
* rabl-rails 読む
* 俺は `gon` を使いたいんだ...

**Comment by speee-nakajima** [comment]
* rabl-rails
* `Rails 3+ templating system with JSON, XML and Plist support.` 便利そうだけどRails3だ

**Comment by speee-nakajima** [comment]
* railsアプリケーション作る
* 俺は `gon` を使いたいだけなんだ
まあ `Your Rails variables in your JS` だししょうがない気もする

**Comment by speee-nakajima** [comment]
* rails アプリケーションを作る
* 
```shell
mkdir test_app
cd test_app
vi Gemfile
```

```Gemfile
Using pkg-config 1.1.7
source 'https://rubygems.org'
gem 'rails'
```

```shell
bundle
```

```log
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 1.6.4
Installing mime-types-data 3.2016.0521
Using arel 6.0.3
Using bundler 1.11.2
Installing concurrent-ruby 1.0.2
Using thor 0.19.1
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Installing mime-types 3.1
Installing sprockets 3.6.0
Using activesupport 4.2.6
Using loofah 2.0.3
Installing mail 2.6.4
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Installing activemodel 4.2.6
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Installing activejob 4.2.6
Installing activerecord 4.2.6
Using actionview 4.2.6
Using actionpack 4.2.6
Installing actionmailer 4.2.6
Using railties 4.2.6
Installing sprockets-rails 3.0.4
Installing rails 4.2.6
Bundle complete! 1 Gemfile dependency, 36 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

```shell
bundle exec rails new .
```

```
       exist
      create  README.rdoc
      create  Rakefile
      create  config.ru
      create  .gitignore
    conflict  Gemfile
Overwrite /Users/satoshi.nakajima/work/ossws/gon/test_app/Gemfile? (enter "h" for help) [Ynaqdh] Y
       force  Gemfile
      create  app
      create  app/assets/javascripts/application.js
      create  app/assets/stylesheets/application.css
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/views/layouts/application.html.erb
      create  app/assets/images/.keep
      create  app/mailers/.keep
      create  app/models/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/bundle
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/secrets.yml
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/session_store.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/favicon.ico
      create  public/robots.txt
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/test_helper.rb
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor/assets/javascripts
      create  vendor/assets/javascripts/.keep
      create  vendor/assets/stylesheets
      create  vendor/assets/stylesheets/.keep
         run  bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.1.2
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using rack 1.6.4
Using mime-types-data 3.2016.0521
Using arel 6.0.3
Using debug_inspector 0.0.2
Using bundler 1.11.2
Installing byebug 9.0.5 with native extensions
Installing coffee-script-source 1.10.0
Installing execjs 2.7.0
Using thor 0.19.1
Using concurrent-ruby 1.0.2
Using multi_json 1.12.1
Installing sass 3.4.22
Installing tilt 2.0.5
Installing spring 1.7.1
Installing sqlite3 1.3.11 with native extensions
Installing rdoc 4.2.2
Using tzinfo 1.2.2
Using nokogiri 1.6.8
Using rack-test 0.6.3
Using mime-types 3.1
Using binding_of_caller 0.7.2
Using coffee-script 2.4.1
Installing uglifier 3.0.0
Using sprockets 3.6.0
Using sdoc 0.4.1
Using activesupport 4.2.6
Using loofah 2.0.3
Using mail 2.6.4
Using rails-deprecated_sanitizer 1.0.3
Using globalid 0.3.6
Using activemodel 4.2.6
Installing jbuilder 2.5.0
Using rails-html-sanitizer 1.0.3
Using rails-dom-testing 1.0.7
Using activejob 4.2.6
Using activerecord 4.2.6
Using actionview 4.2.6
Using actionpack 4.2.6
Using actionmailer 4.2.6
Using railties 4.2.6
Using sprockets-rails 3.0.4
Installing coffee-rails 4.1.1
Installing jquery-rails 4.1.1
Using rails 4.2.6
Using sass-rails 5.0.4
Installing web-console 2.3.0
Installing turbolinks 2.5.3
Bundle complete! 12 Gemfile dependencies, 56 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
         run  bundle exec spring binstub --all
* bin/rake: spring inserted
* bin/rails: spring inserted
```
膨大なファイルできたやつ

**Comment by speee-nakajima** [comment]
* gon rabl-rails いれる
* 
rails ありきだからGemfileに追記する形で書いてあるのか...

```Gemfile
gem 'gon'
gem 'rabl-rails'
```

**Comment by speee-nakajima** [comment]
* 普通の rails で gon を動かす
* rabl読むの辛いから普通のrailsで動かすために上に戻ってその通り書いてみる
* 最初から普通のrailsで動かすための一通りの手順を入れてほしい(rails入っている前提でなく...)

**Comment by speee-nakajima** [comment]
* rails アプリケーションを作る
* 確認用のcontrollerとviewを作る

```shell
vi app/views/application.html.erb
```

下記LINEを追加
一度使ったことあるからなんとなく入れることもわかるけど一発でわかるのだろうか？
でも、このまままるっとコピっても動くからよし？
```application.html.erb
<%= Gon::Base.render_data %>
```

# controllerを作る
```
bundle exec rails g controller test

Running via Spring preloader in process 41486
      create  app/controllers/test_controller.rb
      invoke  erb
      create    app/views/test
      invoke  test_unit
      create    test/controllers/test_controller_test.rb
      invoke  helper
      create    app/helpers/test_helper.rb
      invoke    test_unit
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/test.coffee
      invoke    scss
      create      app/assets/stylesheets/test.scss
```

```test_controller.rb
@your_int = 123
@your_array = [1,2]
@your_hash = {'a' => 1, 'b' => 2}
gon.your_int = @your_int
gon.your_other_int = 345 + gon.your_int
gon.your_array = @your_array
gon.your_array << gon.your_int
gon.your_hash = @your_hash

gon.all_variables # > {:your_int => 123, :your_other_int => 468, :your_array => [1, 2, 123], :your_hash => {'a' => 1, 'b' => 2}}
gon.your_array # > [1, 2, 123]

gon.clear # gon.all_variables now is {}
```

**Comment by speee-nakajima** [comment]
* rails アプリケーション上でgonを動かす
* routes と view を作るの忘れてた

```config/route.rb
...
get '/test' => 'test#index'
```

```test/index.erb
test
```

**Comment by speee-nakajima** [comment]
* rails アプリケーション動いた
* そのままコピペすると `gon.clear` が入っているので何も出ないでちょっと困りそう

**Comment by speee-nakajima** [comment]
* rails アプリ動かしながら
* tutorial ぐらいあるとパっと動きが確認できるので助かる

**Comment by speee-nakajima** [comment]
* gon で rspec を動かしてみよう
* 
``` shell
bundle exec rspec

/Users/satoshi.nakajima/work/ossws/gon/gon/spec/gon/global_spec.rb:1:in `<top (required)>': uninitialized constant Gon::Global (NameError)
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `load'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/bin/rspec:23:in `load'
  from /Users/satoshi.nakajima/.rbenv/versions/2.2.3/bin/rspec:23:in `<main>'
```

なんだろうか

**Comment by speee-nakajima** [comment]
* rspec 動かす
* contributing 書いてほしい

**Comment by speee-nakajima** [comment]
* rspecを動かす
* gem の spec はこう動かすのか...
```
bundle exec rake spec
```

**Comment by speee-nakajima** [comment]
* issueの内容を考える(思案中)
*
```
初めに instration をつけてほしい
その中で rails と gon が使える簡単な example を入れてほしい
rails new から いれたいなーと思ったけど

Very good and detailed example and reasons to use is considered in railscast by Ryan Bates

があったっぽいできれば readme 上で完結したい
```

```
contributing を作って欲しい
```

**Comment by speee-nakajima** [comment]
* issueの内容を考える(思案中)
```
# or new syntax
gon.push({
  :user_id => 1,
  :user_role => "admin"
})
```
を
```
user_id: 1
```
とかに書き直す

**Comment by speee-nakajima** [comment]
* issueを考える
* そのまま書くと
```
gon.clear
```
が入ってて動きが不安

**Comment by speee-nakajima** [comment]
* issueの内容を考える

```
readme を読んでさっと確認したいので rails と gon を含んだものを example に載せてほしい
```

```
Usage のところで gon.clear が入っているがそのまま下の example と一緒に動かすと何も表示されずに困るのでコメントとかにしておいてほしい
```

**Comment by speee-nakajima** [comment]
- issue
- Usage のコードをそのまま貼り付けて動かすと何も値がでないので動くものをおいておいてほしい
`gon.clear` が問題だと思うのでコメントアウトしてもらえるとさっと動くので助かる

**Comment by speee-nakajima** [comment]
- issueを考える
開発者向け

rails の環境を構築して gon をドキュメント通りに導入して [Usage](https://github.com/gazay/gon#usage) のところを一通りコピーして実行すると `alert` で何かが表示されるのが期待されるが何も変数が表示されずに困った。

理由は controller のコードに `gon.clear` が最後に書かれているので起こった問題だった。

なので、 `gon.clear ` は便利な機能だと思うがコメントアウトなどで書いておいてもらえると嬉しい。

**Comment by speee-nakajima** [comment]
- issue を考える

rails の環境を構築して gon をドキュメント通りに導入して [Usage](https://github.com/gazay/gon#usage)のところを一通りコピーして実行すると `alert` で何かが表示されるのが期待されるが何も変数が表示されずに困った。
下記に作成手順を示します

```
mkdir test_app
cd test_app
vi Gemfile
```

``` Gemfile
source 'https://rubygems.org'
gem 'rails'
```

```
bundle

...

bundle exec rails new .

...

```

- Gemfileにgonを追加

``` Gemfile
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'gon'         # add

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

```
bundle

...

vi app/views/application.html.erb
```

``` application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
```

``` 
bundle exec rails g controller test

...

```

``` config/routes.rb
get '/test' => 'test#index'
```

``` test/index.erb
test
```

[Usage](https://github.com/gazay/gon#usage)のところを一通りコピーして実行すると `alert` で何かが表示されるのが期待されるが何も変数が表示されずに困った。

``` app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    @your_int = 123
    @your_array = [1,2]
    @your_hash = {'a' => 1, 'b' => 2}
    gon.your_int = @your_int
    gon.your_other_int = 345 + gon.your_int
    gon.your_array = @your_array
    gon.your_array << gon.your_int
    gon.your_hash = @your_hash

    gon.all_variables # > {:your_int => 123, :your_other_int => 468, :your_array => [1, 2, 123], :your_hash => {'a' => 1, 'b' => 2}}
    gon.your_array # > [1, 2, 123]

    gon.clear # gon.all_variables now is {}
  end
end
```

``` app/assets/javascripts/test.coffee
# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
alert(gon.your_int)
alert(gon.your_other_int)
alert(gon.your_array)
alert(gon.your_hash)
```

試しに `controller` のコードで `gon.clear` をコメントアウトしたら直った。

``` app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    @your_int = 123
    @your_array = [1,2]
    @your_hash = {'a' => 1, 'b' => 2}
    gon.your_int = @your_int
    gon.your_other_int = 345 + gon.your_int
    gon.your_array = @your_array
    gon.your_array << gon.your_int
    gon.your_hash = @your_hash

    gon.all_variables # > {:your_int => 123, :your_other_int => 468, :your_array => [1, 2, 123], :your_hash => {'a' => 1, 'b' => 2}}
    gon.your_array # > [1, 2, 123]

    #gon.clear # gon.all_variables now is {}
  end
end
```

なので、 `gon.clear` は便利な機能だと思うがコメントアウトなどで書いておいてもらえると嬉しい。

**Comment by speee-nakajima** [comment]
- 英語にしてみる

i build rails app with gon.
i installed gon using your documentation.
and, i copied code from [Usage](https://github.com/gazay/gon#usage).
i expected to display something variables in alert box.
but, display nothing.

show my steps below:

```
mkdir test_app
cd test_app
vi Gemfile
```

`Gemfile`
```
source 'https://rubygems.org'
gem 'rails'
```

``` 
bundle

...

bundle exec rails new .

...

```

- Gemfileにgonを追加

`Gemfile`
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'gon'         # add

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

```
bundle

...

vi app/views/application.html.erb
```

`application.html.erb`
```
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
```

``` 
bundle exec rails g controller test
...

```

`config/routes.rb`
```
get '/test' => 'test#index'
```

`test/index.erb`
```
test
```

`app/controllers/test_controller.rb`
```
class TestController < ApplicationController
  def index
    @your_int = 123
    @your_array = [1,2]
    @your_hash = {'a' => 1, 'b' => 2}
    gon.your_int = @your_int
    gon.your_other_int = 345 + gon.your_int
    gon.your_array = @your_array
    gon.your_array << gon.your_int
    gon.your_hash = @your_hash

    gon.all_variables # > {:your_int => 123, :your_other_int => 468, :your_array => [1, 2, 123], :your_hash => {'a' => 1, 'b' => 2}}
    gon.your_array # > [1, 2, 123]

    gon.clear # gon.all_variables now is {}
  end
end
```

`app/assets/javascripts/test.coffee`
```
# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
alert(gon.your_int)
alert(gon.your_other_int)
alert(gon.your_array)
alert(gon.your_hash)
```

i tried to commentout `gon.clear` line, modified.

`app/controllers/test_controller.rb`
```
#gon.clear # gon.all_variables now is {}
```

so, `gon.clear` is useful features!
but, i want to commentout `gon.clear` line in sample code.

**Comment by speee-nakajima** [comment]
rubyとrails のバージョンを書く

**Comment by speee-nakajima** [comment]
- issue を考える

## サンプルコードをコピーして実行したが動かなかった

rails の環境を構築して gon をドキュメント通りに導入して [Usage](https://github.com/gazay/gon#usage)のところを一通りコピーして実行すると `alert` で何かが表示されるのが期待されるが何も変数が表示されずに困った。

試しに `controller` の `gon.clear` をコメントアウトしたら表示されるようになったので、サンプルコード上では `gon.clear` をコメントアウトにしてほしい。

`version` には関係ないと思うが、記載します

```
rails: 4.2.6
ruby: 2.2.3
```

```
# gon.clear
```

下記に作成手順を示します。

```
mkdir test_app
cd test_app
vi Gemfile
```

`Gemfile`
```
source 'https://rubygems.org'
gem 'rails'
```

``` 
bundle

...

bundle exec rails new .

...

```

- Gemfileにgonを追加

`Gemfile`
```
gem 'gon'         # add
```

```
bundle

...

vi app/views/application.html.erb
```

`application.html.erb`
```
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
```

``` 
bundle exec rails g controller test
...

```

`config/routes.rb`
```
get '/test' => 'test#index'
```

`test/index.erb`
```
test
```

`app/controllers/test_controller.rb`
```
def index
  @your_int = 123
  @your_array = [1,2]
  @your_hash = {'a' => 1, 'b' => 2}
  gon.your_int = @your_int
  gon.your_other_int = 345 + gon.your_int
  gon.your_array = @your_array
  gon.your_array << gon.your_int
  gon.your_hash = @your_hash

  gon.all_variables # > {:your_int => 123, :your_other_int => 468, :your_array => [1, 2, 123], :your_hash => {'a' => 1, 'b' => 2}}
  gon.your_array # > [1, 2, 123]

  #gon.clear # gon.all_variables now is {}
end
```

`app/assets/javascripts/test.coffee`
```
alert(gon.your_int)
alert(gon.your_other_int)
alert(gon.your_array)
alert(gon.your_hash)
```

**Comment by speee-nakajima** [comment]
- issue を考える

## sample code do not run as expected
Hi.

I build rails app with gon.
I installed gon using your documentation.
and, I copied the code from Usage.
I expected to display something variables in alert box.
but, display nothing.

I tried to commentout `gon.clear` line, this issue is solved!
so, `gon.clear` is useful features!
but, I want to commentout `gon.clear` line in sample code like this.

```
@your_int = 123
@your_array = [1,2]
@your_hash = {'a' => 1, 'b' => 2}
gon.your_int = @your_int
gon.your_other_int = 345 + gon.your_int
gon.your_array = @your_array
gon.your_array << gon.your_int
gon.your_hash = @your_hash

gon.all_variables # > {:your_int => 123, :your_other_int => 468, :your_array => [1, 2, 123], :your_hash => {'a' => 1, 'b' => 2}}
gon.your_array # > [1, 2, 123]

#gon.clear # gon.all_variables now is {}
```

show ruby and rails versions.
```
rails: 4.2.6
ruby: 2.2.3
```

show my steps below:

```
mkdir test_app
cd test_app
vi Gemfile
```

`Gemfile`
```
source 'https://rubygems.org'
gem 'rails'
```

``` 
bundle

...

bundle exec rails new .

...

```

- Gemfileにgonを追加

`Gemfile`
```
gem 'gon'         # add
```

```
bundle

...

vi app/views/application.html.erb
```

`application.html.erb`
```
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= Gon::Base.render_data %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
```

``` 
bundle exec rails g controller test
...

```

`config/routes.rb`
```
get '/test' => 'test#index'
```

`test/index.erb`
```
test
```

`app/controllers/test_controller.rb`
```
def index
  @your_int = 123
  @your_array = [1,2]
  @your_hash = {'a' => 1, 'b' => 2}
  gon.your_int = @your_int
  gon.your_other_int = 345 + gon.your_int
  gon.your_array = @your_array
  gon.your_array << gon.your_int
  gon.your_hash = @your_hash

  gon.all_variables # > {:your_int => 123, :your_other_int => 468, :your_array => [1, 2, 123], :your_hash => {'a' => 1, 'b' => 2}}
  gon.your_array # > [1, 2, 123]

  gon.clear # gon.all_variables now is {}
end
```

`app/assets/javascripts/test.coffee`
```
alert(gon.your_int)
alert(gon.your_other_int)
alert(gon.your_array)
alert(gon.your_hash)
```

<img width="593" alt="2016-06-11 16 35 57" src="https://cloud.githubusercontent.com/assets/12843655/15984187/738e9404-2ffd-11e6-890c-83fa14852c61.png">

**Comment by kou** [comment]
お疲れさまでした！
