### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: onk: poppler: Work log

### ISSUE THREAD

**Issue by onk** [oss-gate/workshop#664]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by onk** [comment]
公式サイトを探すために「poppler gem」で検索して
一番上に出た rubygems.org のページを開いた
https://rubygems.org/gems/poppler/versions/3.0.7

**Comment by onk** [comment]
ライセンスを確認
rubygems.org のページの右側に LGPL v2 とあるので大丈夫！

**Comment by onk** [comment]
```
irb(main):001:0> require "poppler"
(null)-WARNING **: Failed to load shared library '@rpath/libpoppler-glib.8.dylib' referenced by the typelib: dlopen(@rpath/libpoppler-glib.8.dylib, 9): image not found
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:629:in `load_union_info'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:74:in `load_info'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:43:in `block in load'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `times'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `block in each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:42:in `load'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/poppler-3.2.1/lib/poppler.rb:35:in `<module:Poppler>'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/poppler-3.2.1/lib/poppler.rb:30:in `<top (required)>'
        from (irb):1:in `require'
        from (irb):1:in `irb_binding'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/workspace.rb:85:in `eval'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/workspace.rb:85:in `evaluate'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/context.rb:380:in `evaluate'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:491:in `block (2 levels) in eval_input'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:622:in `signal_status'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:488:in `block in eval_input'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `loop'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `catch'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:487:in `eval_input'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:428:in `block in run'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:427:in `catch'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:427:in `run'
        from /opt/rubies/2.5.0-dev/lib/ruby/2.5.0/irb.rb:383:in `start'
        from /opt/rubies/2.5.0-dev/bin/irb:11:in `<top (required)>'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
        from /Users/onaka/.gem/ruby/2.5.0/bin/bundle:23:in `load'
        from /Users/onaka/.gem/ruby/2.5.0/bin/bundle:23:in `<main>'
NameError: wrong constant name 3D
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:162:in `const_set'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:162:in `load_enum_value'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:187:in `block in load_enum_info'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:186:in `each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:186:in `load_enum_info'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/poppler-3.2.1/lib/poppler/loader.rb:57:in `load_enum_info'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:66:in `load_info'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:43:in `block in load'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:34:in `block (2 levels) in each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `times'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:33:in `block in each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/repository.rb:32:in `each'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/gobject-introspection-3.2.1/lib/gobject-introspection/loader.rb:42:in `load'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/poppler-3.2.1/lib/poppler.rb:35:in `<module:Poppler>'
        from /Users/onaka/.bundle/ruby/2.5.0/gems/poppler-3.2.1/lib/poppler.rb:30:in `<top (required)>'
... 2 levels...
        from /opt/rubies/2.5.0-dev/bin/irb:11:in `<top (required)>'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        from /Users/onaka/.gem/ruby/2.5.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
        from /Users/onaka/.gem/ruby/2.5.0/bin/bundle:23:in `load'
        from /Users/onaka/.gem/ruby/2.5.0/bin/bundle:23:in `<main>'
```

**Comment by onk** [comment]
Linux だと動くことを確認したが Mac だと require すらできない

**Comment by knokmki612** [comment]
進行役おつかれさまでした！
