### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2017-11-25: hash52: rails-admin: Work log

### ISSUE THREAD

**Issue by hash52** [oss-gate/workshop#668]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by hash52** [comment]
ライセンスを確認
MITライセンスなのでok
https://github.com/sferik/rails_admin/blob/master/LICENSE.md

**Comment by swamp09** [comment]
サポーターの沼田です。
よろしくお願いします！

**Comment by hash52** [comment]
よろしくお願いします

**Comment by hash52** [comment]
公式ドキュメントを読む
https://github.com/sferik/rails_admin

**Comment by hash52** [comment]
Installationに従ってInstall

※Railsプロジェクト前提なので、Railsチュートリアルのサンプルにrails-adminをインストールすることにする

`git clone https://github.com/yasslab/sample_apps.git
`
sample_apps/5_1_2/ch14 
に移動してRailsプロジェクトを動かす

```
bundle install --path vendor/bundler
rails db:migrate
```

テストが通ることを確認してサーバ実行
```
rails t
Finished in 9.628920s, 6.8544 runs/s, 35.3103 assertions/s.
66 runs, 340 assertions, 0 failures, 0 errors, 0 skips

rails s
```

アクセスできることを確認

**Comment by hash52** [comment]
Installationに従ってインストール

Gemfileに
gem 'rails_admin', '~> 1.2'

```
bundle install --path vendor/bundler
rails g rails_admin:install
Running via Spring preloader in process 38377
           ?  Where do you want to mount rails_admin? Press <enter> for [admin] >
```
そのままEnter
```
       route  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
      create  config/initializers/rails_admin.rb
```

`rails s
`/adminにアクセスすると管理画面が表示される

**Comment by hash52** [comment]
/admin/micropost
/admin/relationship
/admin/user

にアクセスすると
NoMethodError in RailsAdmin::MainController#index
undefined method `per' for #<ActiveRecord::Relation []>

**Comment by hash52** [comment]
公式ドキュメントをさらに読む

**Comment by hash52** [comment]
読んでもよくわからないので勘でやってみる

推測１: 初期データ入ってないからじゃね？
`rails db:seed`

結果変わらず。。

**Comment by hash52** [comment]
```
Started GET "/admin/relationship" for 127.0.0.1 at 2017-11-25 12:07:37 +0900
Processing by RailsAdmin::MainController#index as HTML
  Parameters: {"model_name"=>"relationship"}
  Relationship Load (0.2ms)  SELECT  "relationships".* FROM "relationships" LIMIT ? OFFSET ?  [["LIMIT", 11], ["OFFSET", 0]]
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
   (0.2ms)  SELECT COUNT(*) FROM "relationships"
Completed 500 Internal Server Error in 26ms (ActiveRecord: 0.0ms)



  CACHE Relationship Load (0.0ms)  SELECT  "relationships".* FROM "relationships" LIMIT ? OFFSET ?  [["LIMIT", 11], ["OFFSET", 0]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
  CACHE  (0.0ms)  SELECT COUNT(*) FROM "relationships"
NoMethodError (undefined method `per' for #<Relationship::ActiveRecord_Relation:0x00007fbc6a48f548>):

vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:125:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:95:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/lib/rails_admin/adapters/active_record.rb:36:in `all'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:131:in `get_collection'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:37:in `list_entries'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/lib/rails_admin/config/actions/index.rb:30:in `block (2 levels) in <class:Index>'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:22:in `index'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:186:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `block in instrument'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:124:in `process'
vendor/bundler/ruby/2.4.0/gems/actionview-5.1.2/lib/action_view/rendering.rb:30:in `process'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:522:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/railtie.rb:185:in `public_send'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/railtie.rb:185:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-pjax-1.0.0/lib/rack/pjax.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/remotipart-1.3.1/lib/remotipart/middleware.rb:32:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:556:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:28:in `block in call'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `catch'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundler/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:522:in `call'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by hash52** [comment]
perメソッドはkaminariのメソッドなので、

`gem 'kaminari'
`
をGemfileに追加

```
bundle --path vendor/install
rails s
```

結果変わらず

**Comment by onk** [comment]
Gemfile から will_paginate を取り除くと `http://localhost:3000/admin/relationship` を表示できました。
(どちらもページネート用のメソッドなので) rails_admin では共存できないんですかねぇ……。

**Comment by onk** [comment]
なんで分かったかというと

```
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:125:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:95:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/lib/rails_admin/adapters/active_record.rb:36:in `all'
```

の

```ruby
      def all(options = {}, scope = nil)
        scope ||= scoped
        scope = scope.includes(options[:include]) if options[:include]
        scope = scope.limit(options[:limit]) if options[:limit]
        scope = scope.where(primary_key => options[:bulk_ids]) if options[:bulk_ids]
        scope = query_scope(scope, options[:query]) if options[:query]
        scope = filter_scope(scope, options[:filters]) if options[:filters]
        if options[:page] && options[:per]
          scope = scope.send(Kaminari.config.page_method_name, options[:page]).per(options[:per])
        end
        scope = scope.reorder("#{options[:sort]} #{options[:sort_reverse] ? 'asc' : 'desc'}") if options[:sort]
        scope
      end
```

を見に行って、

`scope.send(Kaminari.config.page_method_name, options[:page])` が正しく kaminari の
`page` メソッドを呼んでいるなら、絶対に `per` メソッドが生えるのを知っていたので

https://github.com/kaminari/kaminari/blob/v1.1.1/kaminari-activerecord/lib/kaminari/activerecord/active_record_model_extension.rb#L11-L22
(ここの `include Kaminari::PageScopeMethods` で特異メソッドを定義しています)

他の gem が `page` メソッドを横取りしているのかな？と考えました。

あとはローカルのソースコードを見るように変えて `binding.pry` で止めて


```diff
diff --git a/5_1_2/ch14/Gemfile b/5_1_2/ch14/Gemfile
index c0d51f2..c9b1b9a 100644
--- a/5_1_2/ch14/Gemfile
+++ b/5_1_2/ch14/Gemfile
@@ -44,4 +44,5 @@ end
 
 # Windows環境ではtzinfo-dataというgemを含める必要があります
 gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
-gem "rails_admin"
+gem "pry-rails"
+gem "rails_admin", path: "~/src/github.com/sferik/rails_admin"
```

```
From: /Users/onaka/src/github.com/sferik/rails_admin/lib/rails_admin/adapters/active_record.rb @ line 35 RailsAdmin::Adapters::ActiveRecord#all:

    28: def all(options = {}, scope = nil)
    29:   scope ||= scoped
    30:   scope = scope.includes(options[:include]) if options[:include]
    31:   scope = scope.limit(options[:limit]) if options[:limit]
    32:   scope = scope.where(primary_key => options[:bulk_ids]) if options[:bulk_ids]
    33:   scope = query_scope(scope, options[:query]) if options[:query]
    34:   scope = filter_scope(scope, options[:filters]) if options[:filters]
 => 35:   binding.pry
    36:   if options[:page] && options[:per]
    37:     scope = scope.send(Kaminari.config.page_method_name, options[:page]).per(options[:per])
    38:   end
    39:   scope = scope.reorder("#{options[:sort]} #{options[:sort_reverse] ? 'asc' : 'desc'}") if options[:sort]
    40:   scope
    41: end
```

`show-source` (`$` にエイリアスが貼ってあります) を利用します。

```
[1] pry(#<RailsAdmin::AbstractModel>)> $ scope.page

From: /Users/onaka/.bundle/ruby/2.5.0/gems/will_paginate-3.1.5/lib/will_paginate/active_record.rb @ line 165:
Owner: WillPaginate::ActiveRecord::Pagination
Visibility: public
Number of lines: 19

def page(num)
  rel = if ::ActiveRecord::Relation === self
    self
  elsif !defined?(::ActiveRecord::Scoping) or ::ActiveRecord::Scoping::ClassMethods.method_defined? :with_scope
    # Active Record 3
    scoped
  else
    # Active Record 4
    all
  end

  rel = rel.extending(RelationMethods)
  pagenum = ::WillPaginate::PageNumber(num.nil? ? 1 : num)
  per_page = rel.limit_value || self.per_page
  rel = rel.offset(pagenum.to_offset(per_page).to_i)
  rel = rel.limit(per_page) unless rel.limit_value
  rel.current_page = pagenum
  rel
end
```

すると will_paginate が現れたので、これですねー。

**Comment by hash52** [comment]
日本語で書いてみる

**Comment by hash52** [comment]
##再現方法
`git clone https://github.com/yasslab/sample_apps.git
`
Gemfileに記述
`gem 'rails_admin', '~> 1.2'
`
```
bundle install --path vendor/bundler
rails db:migrate
```

Installationに沿ってコマンドを打つ
```
rails g rails_admin:install
rails s

```
/admin
にアクセスできる

/admin/micropost
/admin/relationship
/admin/user
にアクセスすると

```
Started GET "/admin/relationship" for 127.0.0.1 at 2017-11-25 12:07:37 +0900
Processing by RailsAdmin::MainController#index as HTML
  Parameters: {"model_name"=>"relationship"}
  Relationship Load (0.2ms)  SELECT  "relationships".* FROM "relationships" LIMIT ? OFFSET ?  [["LIMIT", 11], ["OFFSET", 0]]
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
   (0.2ms)  SELECT COUNT(*) FROM "relationships"
Completed 500 Internal Server Error in 26ms (ActiveRecord: 0.0ms)



  CACHE Relationship Load (0.0ms)  SELECT  "relationships".* FROM "relationships" LIMIT ? OFFSET ?  [["LIMIT", 11], ["OFFSET", 0]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 1
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
  CACHE  (0.0ms)  SELECT COUNT(*) FROM "relationships"
NoMethodError (undefined method `per' for #<Relationship::ActiveRecord_Relation:0x00007fbc6a48f548>):

vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:125:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:95:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/lib/rails_admin/adapters/active_record.rb:36:in `all'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:131:in `get_collection'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:37:in `list_entries'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/lib/rails_admin/config/actions/index.rb:30:in `block (2 levels) in <class:Index>'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:22:in `instance_eval'
vendor/bundler/ruby/2.4.0/gems/rails_admin-1.2.0/app/controllers/rails_admin/main_controller.rb:22:in `index'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:186:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:131:in `run_callbacks'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `block in instrument'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `instrument'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/abstract_controller/base.rb:124:in `process'
vendor/bundler/ruby/2.4.0/gems/actionview-5.1.2/lib/action_view/rendering.rb:30:in `process'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:522:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/railtie.rb:185:in `public_send'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/railtie.rb:185:in `method_missing'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:46:in `block in serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/routing/route_set.rb:832:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-pjax-1.0.0/lib/rack/pjax.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/remotipart-1.3.1/lib/remotipart/middleware.rb:32:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
vendor/bundler/ruby/2.4.0/gems/activerecord-5.1.2/lib/active_record/migration.rb:556:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:135:in `call_app'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:28:in `block in call'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `catch'
vendor/bundler/ruby/2.4.0/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/rack/logger.rb:24:in `call'
vendor/bundler/ruby/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
vendor/bundler/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundler/ruby/2.4.0/gems/actionpack-5.1.2/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
vendor/bundler/ruby/2.4.0/gems/railties-5.1.2/lib/rails/engine.rb:522:in `call'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
vendor/bundler/ruby/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by hash52** [comment]
解決方法
Gemfileの
`gem 'will_paginate',           '3.1.5'
`
を削除

**Comment by hash52** [comment]
結論
'will_paginate', '3.1.5'と競合してます

**Comment by hash52** [comment]
まとめ

issueとしなかった流れ
・wikiのトラブルシュートに書いてあるけど、これ、Readmeにせめてリンクあるべきじゃね？
・あ、でもwikiの頭に「トラブルシュート最初に読め」って書いてあったわ
・じゃ、いっか(私がおばかでした)で結局issueは出しませんでした

今回はissueを出さなかったけど、ユーザもドキュメント含めどうすれば使いやすくなるか考えるのがOSSなわけで、
開発者は凡人の目線がないので、（僕のような）素人が「使えませんでした」とissueを出そうか考えるのも立派な貢献のひとつ
ただ、素人だということを忘れずに、wikiとかちゃんと見ようね

**Comment by hash52** [comment]
ググる以外の公式ドキュメント

README
RDoc
Wikiのトラブルシュート
Issueのcloseされたもの
ここまで来て無ければソースコード

**Comment by knokmki612** [comment]
おつかれさまでした！

直近の東京で開催されるOSS Gateのイベントは以下のとおりです！

* 12月5日: [OSS Gateふりかえり2017-12](https://oss-gate.doorkeeper.jp/events/67519)
* 12月18日: 東京ミートアップ: 
* 1月27日: 東京ワークショップ: 

今後もOSS Gateのイベントは開催されるので、是非よかったらまた参加してみてください！
