### ISSUE TITLE
OSS Gate Meetup: Osaka: 2018-01-17: murajun1978: React: Work log

### ISSUE THREAD

**Issue by murajun1978** [oss-gate/workshop#711]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by murajun1978** [comment]
Reactを開発する手順を調べてみる

**Comment by murajun1978** [comment]
まずはReactのREADMEをみてみる
https://github.com/facebook/react

**Comment by murajun1978** [comment]
Contributing Guideなるものがあるので見てみる
https://reactjs.org/docs/how-to-contribute.html

**Comment by murajun1978** [comment]
Reactって最初のOSS Projectだったのか

**Comment by murajun1978** [comment]
Discardのチャットルームがあるみたいなので登録する

**Comment by murajun1978** [comment]
need-helpってルームあって、気軽に質問とかできそうだ

**Comment by murajun1978** [comment]
https://www.reactiflux.com/

**Comment by murajun1978** [comment]
Forkしてlocalにcloneする

**Comment by murajun1978** [comment]
`yarn install` でエラー

```
➜  react git:(master) yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "babel-eslint@^6.1.2".
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "eslint@^3.0.0".
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "eslint-plugin-react@^5.2.2".
warning " > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Current node version is not supported for development, expected "9.2.1" to satisfy "8.x".
    at Object.<anonymous> (/home/murajun1978/dev/react/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```

**Comment by murajun1978** [comment]
前提条件が書いてある
https://reactjs.org/docs/how-to-contribute.html#contribution-prerequisites

**Comment by murajun1978** [comment]
前提条件の項目を先に持ってくるほうがスムーズかも？

**Comment by murajun1978** [comment]
Nodeはv8以上でyarn v1.2以上

**Comment by murajun1978** [comment]
localの環境を確認

**Comment by murajun1978** [comment]
```
➜  react git:(master) ✗ node -v
v9.2.1
➜  react git:(master) ✗ yarn -v
1.3.2
```

**Comment by murajun1978** [comment]
条件はみたしている

**Comment by murajun1978** [comment]
再度、 `yarn install`

**Comment by murajun1978** [comment]
```
➜  react git:(master) ✗ yarn 
yarn install v1.3.2
[1/4] Resolving packages...
success Already up-to-date.
$ node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Current node version is not supported for development, expected "9.2.1" to satisfy "8.x".
    at Object.<anonymous> (/home/murajun1978/dev/react/node_modules/fbjs-scripts/node/check-dev-engines.js:39:3)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by murajun1978** [comment]
`AssertionError [ERR_ASSERTION]: Current node version is not supported for development, expected "9.2.1" to satisfy "8.x".` 

nodeをv8のlatestにして再挑戦

**Comment by murajun1978** [comment]
```
➜  react git:(master) ✗ n 8.9.4

     install : node-v8.9.4
       mkdir : /home/murajun1978/n/n/versions/node/8.9.4
       fetch : https://nodejs.org/dist/v8.9.4/node-v8.9.4-linux-x64.tar.gz
######################################################################## 100.0%
   installed : v8.9.4
```

僕はnodeのバージョン管理には [n](https://github.com/tj/n) を使ってる

**Comment by murajun1978** [comment]
```
➜  react git:(master) ✗ node -v
v8.9.4
```

OK

**Comment by murajun1978** [comment]
再度、 `yarn install`

**Comment by murajun1978** [comment]
```
➜  react git:(master) ✗ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "babel-eslint@^6.1.2".
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "eslint@^3.0.0".
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "eslint-plugin-react@^5.2.2".
warning " > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
$ node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
Done in 3.94s.
```

**Comment by murajun1978** [comment]
インストール成功した

**Comment by murajun1978** [comment]
Development Workflowを読む
https://reactjs.org/docs/how-to-contribute.html#development-workflow

**Comment by murajun1978** [comment]
`yarn debug-test` って scriptがあってテストをデバックできるのか

**Comment by murajun1978** [comment]
Chrome devtoolでデバックできるのか

**Comment by murajun1978** [comment]
`yarn build` ですべてのpackageをビルドできる

**Comment by murajun1978** [comment]
ローカル環境で動作確認したい場合は `yarn link` を使うとよいとのこと

**Comment by murajun1978** [comment]
https://yarnpkg.com/lang/en/docs/cli/link/

**Comment by murajun1978** [comment]
```
➜  react git:(master) ✗ la build/node_modules/
total 36K
drwxrwxr-x 9 murajun1978 murajun1978 4.0K  1月 17 20:46 ./
drwxrwxr-x 8 murajun1978 murajun1978 4.0K  1月 17 20:46 ../
drwxrwxr-x 4 murajun1978 murajun1978 4.0K  1月 17 20:46 react/
drwxrwxr-x 4 murajun1978 murajun1978 4.0K  1月 17 20:46 react-art/
drwxrwxr-x 3 murajun1978 murajun1978 4.0K  1月 17 20:46 react-call-return/
drwxrwxr-x 4 murajun1978 murajun1978 4.0K  1月 17 20:46 react-dom/
drwxrwxr-x 3 murajun1978 murajun1978 4.0K  1月 17 20:46 react-noop-renderer/
drwxrwxr-x 3 murajun1978 murajun1978 4.0K  1月 17 20:46 react-reconciler/
drwxrwxr-x 3 murajun1978 murajun1978 4.0K  1月 17 20:46 react-test-renderer/
```

**Comment by murajun1978** [comment]
```
cd ~/path_to_your_react_clone/build/node_modules/react
yarn link
cd ~/path_to_your_react_clone/build/node_modules/react-dom
yarn link
cd /path/to/your/project
yarn link react react-dom`
```

**Comment by murajun1978** [comment]
なるほど！

**Comment by murajun1978** [comment]
ここまでで開発=>デバックできそうだ :smile:

**Comment by murajun1978** [comment]
Style guildも目を通す
https://reactjs.org/docs/how-to-contribute.html#style-guide

**Comment by murajun1978** [comment]
入門動画 :movie_camera:

**Comment by murajun1978** [comment]
次はCodebase Overviewを見る
https://reactjs.org/docs/codebase-overview.html
