### ISSUE TITLE
OSS Gate Workshop: Akatsuki: 2018-03-26: johro: zaif-ruby: Work log

### ISSUE THREAD

**Issue by johro** [oss-gate/workshop#776]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${アカウント名}: ${OSS名}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by sachaos** [comment]
👍

**Comment by 3nan3** [comment]
日付間違えとるで

**Comment by johro** [comment]
https://github.com/palon7/zaif-ruby/blob/master/README.md
の`Installation`を実行していく

**Comment by johro** [comment]
その前にプロジェクトを作っておく
`rails new zaif_rails`

**Comment by johro** [comment]
上記の補足
`Add this line to your application's Gemfile:`と書いてあったので思考停止してrails newした

**Comment by johro** [comment]
railsプロジェクトを立てる必要はなかったので
bundle initして生成したgemfileに`gem 'zaif'`を書いてbundleする

**Comment by johro** [comment]
入った
```rb
$ bundle
The latest bundler is 1.16.1, but you are currently running 1.15.4.
To update, run `gem install bundler`
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by johro** [comment]
Usageに書いてあるコードをを試す

**Comment by johro** [comment]
bundle力がない
```rb
be ruby zaif-sample.rb
zaif-sample.rb:1:in `require': cannot load such file -- zaif (LoadError)
	from zaif-sample.rb:1:in `<main>'
```

**Comment by johro** [comment]
zaif-rubyが入っているのか確認
```rb
$ bundle info zaif
The latest bundler is 1.16.1, but you are currently running 1.15.4.
To update, run `gem install bundler`
Could not find gem 'zaif'.
```
入ってませんでした

**Comment by johro** [comment]
```rb
$ bundle install
The latest bundler is 1.16.1, but you are currently running 1.15.4.
To update, run `gem install bundler`
Fetching gem metadata from https://rubygems.org/.
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using bundler 1.15.4
Fetching zaif 0.0.2
Installing zaif 0.0.2
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

[takaya.ninagawa ~/RubyPractice [master *%>]]
$ bundle info zaif
The latest bundler is 1.16.1, but you are currently running 1.15.4.
To update, run `gem install bundler`
  * zaif (0.0.2)
	Summary: Zaif API wrapper.
	Homepage: https://github.com/palon7/zaif-ruby
	Path: /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2
```
入ったことを確認

**Comment by johro** [comment]
実行
```rb
$ be ruby zaif-sample.rb
zaif-sample.rb:3:in `<main>': uninitialized constant ZAIF_KEY (NameError)
```

**Comment by johro** [comment]
しんさんからお借りしたKEYを使って実行する

**Comment by johro** [comment]
はい
```rb
$ be ruby zaif-sample.rb
/Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `initialize': execution expired (Net::OpenTimeout)
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `open'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:201:in `post_ssl'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:107:in `trade'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:114:in `bid'
	from zaif-sample.rb:7:in `<main>'
```

**Comment by johro** [comment]
ruby execution expired (Net::OpenTimeout)でググる

**Comment by johro** [comment]
一番上に出てきた
https://qiita.com/yutackall/items/5c502a0afc4c27e6d90d
を読む

**Comment by johro** [comment]
もう一度実行したら異なるエラーが出てきた
```rb
be ruby zaif-sample.rb
/Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:207:in `block in post_ssl': trade temporarily unavailable. (Zaif::APIErrorException)
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:201:in `post_ssl'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:107:in `trade'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:114:in `bid'
	from zaif-sample.rb:7:in `<main>'
```

**Comment by johro** [comment]
trade temporarily unavailable (Zaif::APIErrorException)でググる

**Comment by johro** [comment]
一番上に出てきた
http://techbureau-api-document.readthedocs.io/ja/latest/faq/2_error_message.html
を読む

**Comment by johro** [comment]
上記サイト曰く
```
trade temporarily unavailable.
取引が一時的に停止されています。
```
とのこと

**Comment by johro** [comment]
```rb
require 'zaif'

api = Zaif::API.new(:api_key => ZAIF_API_KEY, :api_secret => ZAIF_API_SECRET)

api.get_info
```
で実行してみる

**Comment by johro** [comment]
1回目
```rb
$ be ruby zaif-sample.rb
/Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1407:in `request'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:202:in `block in post_ssl'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:201:in `post_ssl'
	from /Users/takaya.ninagawa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zaif-0.0.2/lib/zaif.rb:73:in `get_info'
	from zaif-sample.rb:9:in `<main>'
```

2回目
```
$ be ruby zaif-sample.rb
{"funds"=>{"jpy"=>1.951, "btc"=>0.0, "xem"=>0.0, "mona"=>0.0, "BCH"=>0.0, "ETH"=>0.0}, "deposit"=>{"mona"=>0.0, "jpy"=>7.951, "BCH"=>0.0, "ETH"=>0.0, "btc"=>0.0, "xem"=>0.0}, "rights"=>{"info"=>1, "trade"=>1, "withdraw"=>1, "personal_info"=>1, "id_info"=>1}, "trade_count"=>65, "open_orders"=>1, "server_time"=>1522043601}
```

**Comment by johro** [comment]
自分のまとめを作る

**Comment by johro** [comment]
まとめ

Usageのサンプルコードは実際に売買をするのに注意書きがなく気軽に試せないコードになっています。

サンプルコードを試すユーザーが気軽に実行できるようなコードも別で用意し、実際に売買をやり取りするコードには注意書きをした方が良いのではないでしょうか。


# Usage
```rb
EX 1）
require 'zaif'

api = Zaif::API.new(:api_key => ZAIF_API_KEY, :api_secret => ZAIF_API_SECRET)

info = api.get_info

p info
```

```rb
EX 2）
# 注意
# このコードは実際に売買を行います

require 'zaif'

api = Zaif::API.new(:api_key => ZAIF_API_KEY, :api_secret => ZAIF_API_SECRET)

api.bid("btc", 30760, 0.0001)
api.ask("btc", 30320, 0.0001)

info = api.get_info

p info
```

**Comment by kou** [comment]
お疲れ様でした！
引き続きやっていきましょう！
