### ISSUE TITLE
OSS Gate Workshop: Tokyo: 2018-09-08: BuiDuyen: AWS-PHP: Work log

### ISSUE THREAD

**Issue by BuiThiLuongDuyen** [oss-gate/workshop#950]
This is a work log of a "OSS Gate workshop".
"OSS Gate workshop" is an activity to increase OSS developers.
Here's been discussed in Japanese. Thanks.

## 作業ログ作成時の説明

以下のテンプレートを埋めてタイトルに設定します。埋め方例はスクロールすると見えてきます。

    OSS Gate Workshop: ${LOCATION}: ${YEAR}-${MONTH}-${DAY}: ${ACCOUNT_NAME}: ${OSS_NAME}: Work log

タイトル例↓：

    OSS Gate Workshop: Tokyo: 2017-01-16: kou: Rabbit: Work log

## OSS Gateワークショップ関連情報

  * [スライド](https://slide.rabbit-shocker.org/authors/oss-gate/)：ワークショップの進行に使っているスライドがあります。
  * [チャット](https://gitter.im/oss-gate/devel)：OSS開発に関することならなんでも相談できます。ワークショップが終わった後もオンラインで相談しながら継続的にOSSの開発に参加しましょう！
  * [シナリオ](https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md)：ワークショップの目的・内容・進め方の詳細が書いています。
  * [過去のビギナーの作業ログ](https://github.com/oss-gate/workshop/issues?q=is%3Aissue+is%3Aclosed+"OSS+Gate+Workshop"+in%3Atitle)：他の人の作業ログから学べることがいろいろあるはずです。

**Comment by BuiThiLuongDuyen** [comment]
https://awslabs.github.io/aws-cdk/getting-started.html 
を参考するインストール

**Comment by BuiThiLuongDuyen** [comment]
GitHub
https://github.com/awslabs/aws-cdk

**Comment by BuiThiLuongDuyen** [comment]
```
 mkdir oss-gate
 cd oss-gate
 npm install -g aws-cdk
 cdk --version
```

**Comment by BuiThiLuongDuyen** [comment]
```
cdk --version
```
でバーションを調べたらエラーが出た

```
/Users/usr0200547/.nvm/versions/node/v6.11.0/lib/node_modules/aws-cdk/bin/cdk.js:30
async function parseCommandLineArguments() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/usr0200547/.nvm/versions/node/v6.11.0/lib/node_modules/aws-cdk/bin/cdk:2:1)
```

**Comment by BuiThiLuongDuyen** [comment]
nvm でnpmをインストールしたので、npmバーションをあげるためにnvmを最新にしないといけなかった
```
nvm ls-remote
nvm install v8.11.4
nvm use v8.11.4
```
無事にcdkバーションを確認できた

**Comment by BuiThiLuongDuyen** [comment]
```
mkdir hello-cdk
cd hello-cdk/
git init
npm init -y
npm install @aws-cdk/cdk
```

**Comment by BuiThiLuongDuyen** [comment]
```
npm run build 
```
をしたらできなかった
```
npm ERR! missing script: build
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/usr0200547/.npm/_logs/2018-09-08T05_49_33_566Z-debug.log
```

**Comment by BuiThiLuongDuyen** [comment]
```
npm install tsc -g
```
したら`ERR!` がなくして `WARN`になった。追加出たっぽい

**Comment by BuiThiLuongDuyen** [comment]
typescriptパッケージをグローバルインストールする
```
npm install typescript -g
```

**Comment by BuiThiLuongDuyen** [comment]
```
npm run build
```
エラーの一部→ tsc がなかったようですが、
```
17 verbose argv "/Users/usr0200547/.nvm/versions/node/v8.11.4/bin/node" "/Users/usr0200547/.nvm/versions/node/v8.11.4/bin/npm" "run" "build"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error hello-cdk@1.0.0 build: `tsc`
22 error Exit status 1
23 error Failed at the hello-cdk@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by BuiThiLuongDuyen** [comment]
## AWS-CDKをインストールして実行できなかった


Github https://github.com/awslabs/aws-cdk 
https://awslabs.github.io/aws-cdk/getting-started.html
を参考にしてインストールをしました。
まず、aws-cdkをnpm で以下のコマンドでインストールをしました。
`npm install -g aws-cdk`
しかしcdkバーションを確認したらエラーが出ました。
```
cdk --version
> /Users/usr0200547/.nvm/versions/node/v6.11.0/lib/node_modules/aws-cdk/bin/cdk.js:30
async function parseCommandLineArguments() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/usr0200547/.nvm/versions/node/v6.11.0/lib/node_modules/aws-cdk/bin/cdk:2:1)
```

現在のnpm バージョンは6.11.xxxでしたが、上記にも書いてあったようにnode.jsは8.11.x以上が必須でした。仕様書をちゃんとみませんでした。
node.jsをupdateをしました。
元々入ったnode.jsはnvmパッケージでインスートしましたため、nvmパッケージをupdateして、node.jsを最新にしたら無事に確認できました。

その後に仕様書通りに以下のコマンドを実装しました。
使うディレクトリを作成して, `package.json`を作る。

```
mkdir hello-cdk
cd hello-cdk
git init
npm init -y # creates package.json
```
tsconfig.jsonを作りました。

```
{
    "compilerOptions": {
        "target": "es2018",
        "module": "commonjs"
    }
}
```
package.jsonにtypescriptを実行するパッケージを追加しました。
```
{
    "scripts": {
        "build": "tsc",
        "watch": "tsc -w"
    }
}
```
aws-cdk/cdk とtypes/nodeをインストールしました。
```
npm install @aws-cdk/cdk @types/node
```
空のappクラスを作る
```
import cdk = require('@aws-cdk/cdk');

class MyApp extends cdk.App {
    constructor(argv: string[]) {
        super(argv);
    }
}

process.stdout.write(new MyApp(process.argv).run());
```
ここまで実行して
```
npm run build
```
をビルドしたらエラーが流れました。
エラーログの一部は以下です。
```
17 verbose argv "/Users/usr0200547/.nvm/versions/node/v8.11.4/bin/node" "/Users/usr0200547/.nvm/versions/node/v8.11.4/bin/npm" "run" "build"
18 verbose node v8.11.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error hello-cdk@1.0.0 build: `tsc`
22 error Exit status 1
23 error Failed at the hello-cdk@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
```
tscがないと言われたようで、仕様書に探ってみましたが、見つかりませんでした。
調べたら
```
npm install -g typescript
```
でインストールできました。
```
npm run build

> hello-cdk@1.0.0 build /Users/usr0200547/GmoMedia/oss-gate/hello-cdk
> tsc
```
```
tsc -v
Version 3.0.3
```
